### ISSUE TITLE
cryptography==0.8 breaks client

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#1012]
Follow-up from https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203405#c17. It seems that our `cryptography>=0.8` requirement is too weak. After `pip install cryptography==0.8` the following error is thrown:

```
Traceback (most recent call last):
  File "/root/letsencrypt/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0.dev0', 'console_scripts', 'letsencrypt')()
  File "/root/letsencrypt/letsencrypt/cli.py", line 1002, in main
    return args.func(args, config, plugins)
  File "/root/letsencrypt/letsencrypt/cli.py", line 376, in auth
    le_client = _init_le_client(args, config, authenticator, installer)
  File "/root/letsencrypt/letsencrypt/cli.py", line 160, in _init_le_client
    acc, acme = _determine_account(args, config)
  File "/root/letsencrypt/letsencrypt/cli.py", line 147, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/letsencrypt/letsencrypt/client.py", line 98, in register
    acc = account.Account(regr, key)
  File "/root/letsencrypt/letsencrypt/account.py", line 60, in __init__
    format=serialization.PublicFormat.SubjectPublicKeyInfo)
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 614, in public_bytes
    self._rsa_cdata
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1199, in _public_key_bytes
    raise ValueError("Only PEM encoding is supported by this backend")
ValueError: Only PEM encoding is supported by this backend
```

**Comment by zkanda** [comment]
Hello,

I think you can just convert from `DER` to `PEM` and vice versa, how about supporting both? I'm not sure what's the better choice of the two though.
