### ISSUE TITLE
letsencrypt-auto / pip versioning errors if you have ever installed the nginx plugin

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1072]
I've seen this on two systems that were used for pre-release dev work:

```
pde@damoclid:~/letsencrypt/letsencrypt$ ./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: sudo /home/pde/.local/share/letsencrypt/bin/letsencrypt --help
An unexpected error occurred.
VersionConflict: (acme 0.0.0.dev20151020 (/home/pde/.local/share/letsencrypt/lib/python2.7/site-packages), Requirement.parse('acme==0.0.0.dev20151008'))
Please see the logfile 'letsencrypt.log' for more details.
```

```
pde@damoclid:~/letsencrypt/letsencrypt$ cat letsencrypt.log 
Traceback (most recent call last):
  File "/home/pde/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1030, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 161, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 31, in __init__
    self.plugin_cls = entry_point.load()
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/pde/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (acme 0.0.0.dev20151020 (/home/pde/.local/share/letsencrypt/lib/python2.7/site-packages), Requirement.parse('acme==0.0.0.dev20151008'))

```
`rm -rf ~/.local/share/letsencrypt` didn't fix this.  Manually pip upgrading or pip uninstalling `letsencrypt-nginx` didn't seem to fix this.   But doing both of those things together did.

**Comment by kuba** [comment]
`rm -rf ~/.local/share/letsencrypt` should certainly fix it, it did for me when I first encountered this issue.

Root cause is that we don't try to "update" `letsencrypt-nginx` in recent versions of the script. Quickest way to "fix" is `~/.local/share/letsencrypt pip uninstall letsencrypt-nginx`.

As long as we don't remove any other packages we should be fine.

**Comment by pde** [comment]
This was a real bug in letsencrypt-auto.
