### ISSUE TITLE
letsencrypt-auto fails with PythonDialogBug on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by kvannotten** [letsencrypt/letsencrypt#1154]
Running the app I get: 
```
root@webproxy:~/letsencrypt# ./letsencrypt-auto -vvvv
-vvvv
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt-apache in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: zope.interface in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: acme==0.0.0.dev20151024 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: requests in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: six in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: mock in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: ConfigArgParse in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt-apache)
Requirement already up-to-date: pyasn1 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: werkzeug in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: idna>=2.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: enum34 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pycparser in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt -vvvv
Error in sys.excepthook:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1006, in _handle_exception
    "".join(traceback.format_exception(exc_type, exc_value, trace)))
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/log.py", line 64, in emit
    self.width + self.PADDING_WIDTH)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 2675, in infobox
    kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
dialog.PythonDialogBug

Original exception was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1058, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 988, in setup_logging
    logger.debug("Root logging level set at %d", level)
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/log.py", line 64, in emit
    self.width + self.PADDING_WIDTH)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 2675, in infobox
    kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
dialog.PythonDialogBug
```

Kernel version:
```
root@webproxy:~/letsencrypt# uname -r
3.13.0-66-generic
```

Ubuntu version:
```
root@webproxy:~/letsencrypt# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
Letsencrypt version is just a fresh clone from git at the time of writing commit: 9b94d1c5a49d7dc7d2093d6d2663d48744ac0125. 
Tried several versions of the letsencrypt-auto command; but they all seem to fail. 

If I run this: ```./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth```
I get the following:
```
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory auth
authenticator could not be determined or is not installed
```

With the -vvvv argument I get the PythonDialogBug again. 

I looked through the issues, but didn't seem to find one that resembled to my problem.

Oh also, I tried on two different VMs, both the same version of ubuntu however. I also tried setting the LC_ALL env variable to en_US.UTF-8 to eliminate any locale issues with 'dialog'. 

I suspect I'm just doing something stupid, but any help would be appreciated :-)

**Comment by kuba** [comment]
As a quickfix, can you try if `./letsencrypt-auto --text -vvvvvv` works? This should disable `dialog` and proceed with text interface.

Can you please paste output of `dialog --version`?

**Comment by kvannotten** [comment]
This seems to work indeed. 

Version of dialog:
```
# dialog --version
Version: 1.2-20130928
```

**Comment by kuba** [comment]
I'm on Digital Ocean droplet with:

```
root@le-ubuntu-14:~/letsencrypt# dialog --version
Version: 1.2-20130928
root@le-ubuntu-14:~/letsencrypt# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

and I cannot reproduce this problem :(

Any thoughts?

**Comment by kuba** [comment]
@kvannotten, also, when you try without `-vvvv`, do you see `PythonDialogBug` in `/var/log/letsencrypt/letsencrypt.log`?

**Comment by kvannotten** [comment]
Without the -vvvv I have the following content in /var/log/letsencrypt/letsencrypt.log:

```
root@webproxy:~/letsencrypt# ./letsencrypt-auto auth --server https://acme-v01.api.letsencrypt.org/directory        
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt auth --server https://acme-v01.api.letsencrypt.org/directory
An unexpected error occurred.
PythonDialogBug
Please see the logfiles in /var/log/letsencrypt for more details.
root@webproxy:~/letsencrypt# cat /var/log/letsencrypt/letsencrypt.log
2015-10-27 20:02:01,485:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-10-27 20:02:01,485:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-10-27 20:02:01,485:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151024
2015-10-27 20:02:01,486:DEBUG:letsencrypt.cli:Arguments: ['auth', '--server', 'https://acme-v01.api.letsencrypt.org/directory']
2015-10-27 20:02:01,486:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-10-27 20:02:01,505:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1083, in main
    disclaimer, "Agree", "Cancel"):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/display/util.py", line 134, in yesno
    yes_label=yes_label, no_label=no_label)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 3749, in yesno
    kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
PythonDialogBug
```
So that's indeed still the PythonDialogBug.

I'm trying to upgrade ubuntu to eliminate that .x.1 version difference now, see if that helps

**Comment by kuba** [comment]
In the meantime could you paste full log of `letsencrypt-auto -vvvvv -text`? It's interesting that it fails in dialog mode only.

**Comment by kvannotten** [comment]
```
root@webproxy:~/letsencrypt# ./letsencrypt-auto -vvvvv --text auth
-vvvvv
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: letsencrypt-apache in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: zope.interface in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: acme==0.0.0.dev20151024 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python2-pythondialog>=3.2.2rc1 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: PyOpenSSL in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: requests in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: parsedatetime in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: configobj in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pytz in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: psutil>=2.1.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: six in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: cryptography>=0.7 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: zope.component in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: mock in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: ConfigArgParse in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: pyrfc3339 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Requirement already up-to-date: python-augeas in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt-apache)
Requirement already up-to-date: pyasn1 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: ndg-httpsclient in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: werkzeug in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from acme==0.0.0.dev20151024->letsencrypt)
Requirement already up-to-date: idna>=2.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: enum34 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: ipaddress in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: cffi>=1.1.0 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cryptography>=0.7->letsencrypt)
Requirement already up-to-date: zope.event in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from zope.component->letsencrypt)
Requirement already up-to-date: funcsigs in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pbr>=0.11 in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from mock->letsencrypt)
Requirement already up-to-date: pycparser in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt -vvvvv --text auth
2015-10-27 21:10:20,236:DEBUG:letsencrypt.cli:Root logging level set at -20
2015-10-27 21:10:20,236:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-10-27 21:10:20,237:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151024
2015-10-27 21:10:20,237:DEBUG:letsencrypt.cli:Arguments: ['-vvvvv', '--text', 'auth']
2015-10-27 21:10:20,238:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)

-------------------------------------------------------------------------------
This is a PREVIEW RELEASE of a client application for the Let's Encrypt
certificate authority and other services using the ACME protocol. The Let's
Encrypt certificate authority is NOT YET ISSUING CERTIFICATES TO THE PUBLIC.

Until publicly-trusted certificates can be issued by Let's Encrypt, this
software CANNOT OBTAIN A PUBLICLY-TRUSTED CERTIFICATE FOR YOUR WEB SERVER.  You
should only use this program if you are a developer interested in experimenting
with the ACME protocol or in helping to improve this software.  If you want to
configure your web site with HTTPS in the meantime, please obtain a certificate
from a different authority.

For updates on the status of Let's Encrypt, please visit the Let's Encrypt home
page at https://letsencrypt.org/.
-------------------------------------------------------------------------------
(A)gree/(C)ancel: A
2015-10-27 21:10:21,846:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-10-27 21:10:21,998:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache): 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-10-27 21:10:22,001:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 50, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-10-27 21:10:22,008:DEBUG:letsencrypt.display.ops:Multiple candidate plugins: * manual
Description: Manual Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: manual = letsencrypt.plugins.manual:Authenticator
Initialized: <letsencrypt.plugins.manual.Authenticator object at 0xb5f5aa6c>
Prep: True

* standalone
Description: Standalone Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0xb5f5abcc>
Prep: True

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Manual Authenticator (manual)
2: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
```

Then I can select either and it just seems to work. 

The ubuntu upgrade also didn't resolve anything, as expected.

**Comment by bmw** [comment]
@kvannotten, I actually got this exact behavior when my `TERM` environment variable was messed up on the machine I ssh'd into. One thing that would be interesting to try is to create a file named `test.py` with the following contents:

```
import dialog

try:
    dialog.Dialog().msgbox("Hi")
except Exception as e:
    print e.message
```

Then run `~/.local/share/letsencrypt/bin/python2 test.py`. Recreating the setup I had when I experienced the problem, I get the following output: `expected an empty output from u'msgbox', but got: u'Error opening terminal: rxvt-unicode-256color.\n'`.

**Comment by kvannotten** [comment]
@bmw Indeed, that seems to be it. Using your test script: 
```
# ~/.local/share/letsencrypt/bin/python2 test.py            
expected an empty output from u'msgbox', but got: u'Error opening terminal: xterm-termite.\n'
```
If  I prefix it with ```TERM=xterm ...``` it seems to be working. Same with the ```./letsencrypt-auto```, prefixing it with ```TERM=xterm``` seems to work.

For future reference: to fix it on my specific terminal (termite), running ```tic -x``` on this file ```https://raw.githubusercontent.com/thestinger/termite/master/termite.terminfo``` works too; don't have to set the TERM env var anymore then.

Cheers for the help :smile:

**Comment by jarmo** [comment]
I have the same problem when having *letsencrypt-auto* in cron:
```
./letsencrypt-auto certonly --webroot -w /var/www -d example.com --keep-until-expiring --expand --agree-tos --email my@email.com
```

When ran manually, it works without any problems. Prefixing command with *TERM=xterm* does not work either probably due to differences how commands are ran within cron. Also, adding *--text* caused *EOFError*.

This problem started to occur at random moment and didn't exist prior that.

**Comment by jarmo** [comment]
Adding *--text* and *--non-interactive* flags to the command seem to have fixed this problem for me.

**Comment by bcutter** [comment]
@jarmo: Perfect, saved my day!

**Comment by speedplane** [comment]
It would be nice if `--text --non-interactive` were documented in `letsencrypt certonly --help`.

**Comment by reillychase** [comment]
Same problem, fixed with  --text --non-interactive thanks @jarmo

**Comment by douglasjunior** [comment]
In my case the problem occurs in Debian within a docker container. To solve the command added `export TERM=xterm` at the end of the file `~/.bashrc`.

**Comment by ohemorange** [comment]
Dialog was removed in #3665, so this issue should disappear with 0.10.0.
