### ISSUE TITLE
Configuration file breaks for multiple domains

### ISSUE THREAD

**Issue by MaStr** [letsencrypt/letsencrypt#1180]
When I try to setup a config file like decribed here https://letsencrypt.readthedocs.org/en/latest/using.html#configuration-file , it is not possible to generate new certificates.
When I leave out the domain value (two comma separated values) and enter them manual, it works out.

````
# This is an example of the kind of things you can do in a configuration file.
# All flags used by the client can be configured here. Run Let's Encrypt with
# "--help" to learn more about the available options.

# Use a 4096 bit RSA key instead of 2048
# rsa-key-size = 4096
# Always use the staging/testing server
#server = https://acme-staging.api.letsencrypt.org/directory
# closed beta server
server = https://acme-v01.api.letsencrypt.org/directory

# Uncomment and update to register with the specified e-mail address
email = email@....

# Uncomment to use a text interface instead of ncurses
text = True

# Uncomment to use the standalone authenticator on port 443
# authenticator = standalone
# standalone-supported-challenges = dvsni

# Uncomment to use the webroot authenticator. Replace webroot-path with the
# path to the public_html / webroot folder being served by your web server.
authenticator = webroot
webroot-path = /<path to>/public_html
domains = example.com,www.example.com

agree-dev-preview = True
````

Error message:
````
2015-10-29 01:29:13,906:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-10-29 01:29:13,906:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-10-29 01:29:13,907:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151024
2015-10-29 01:29:13,907:DEBUG:letsencrypt.cli:Arguments: ['-c', '/etc/letsencrypt/xxxxx-config', 'auth']
2015-10-29 01:29:13,907:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-10-29 01:29:13,908:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2015-10-29 01:29:13,916:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /var/www/bitcave.io/public_html/.well-known/acme-challenge
2015-10-29 01:29:13,917:DEBUG:letsencrypt.display.ops:Single candidate plugin: * webroot
Description: Webroot Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0x974654c>
Prep: True
2015-10-29 01:29:13,917:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0x974654c> and installer None
2015-10-29 01:29:13,951:DEBUG:letsencrypt.cli:Picked account: <Account(a3f5a3863af591cc208d3df1aa652822)>
2015-10-29 01:29:13,951:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-10-29 01:29:13,956:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-10-29 01:29:14,575:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-10-29 01:29:14,578:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Thu, 29 Oct 2015 01:29:14 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 29 Oct 2015 01:29:14 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '8DULfo07ruK4orCOEruSMKezU135e3KFtY2d33EMReU'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-29 01:29:14,579:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Thu, 29 Oct 2015 01:29:14 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 29 Oct 2015 01:29:14 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '8DULfo07ruK4orCOEruSMKezU135e3KFtY2d33EMReU'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-29 01:29:14,794:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0010_key-letsencrypt.pem
2015-10-29 01:29:14,796:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/strubel/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1097, in main
    return args.func(args, config, plugins)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 473, in auth
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 313, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 210, in obtain_certificate
    csr = crypto_util.init_save_csr(key, domains, self.config.csr_dir)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 78, in init_save_csr
    csr_pem, csr_der = make_csr(privkey.pem, names)
 File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 118, in make_csr
    value=", ".join("DNS:%s" % d for d in domains)
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 653, in __init__
    _raise_current_error()
  File "/home/strubel/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('X509 V3 routines', 'v2i_GENERAL_NAME_ex', 'missing value'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]
````

I guess, the config file should work like a normal input in text or ncurses mode.

**Comment by MaStr** [comment]
Hi.
the solution is to use

````
domains = example.com
domains = www.example.com
````

This is a bit uncommon compared to the other configuraiton and the long name "domain**s**"

Matthias

**Comment by bmw** [comment]
This is a known limitation that should perhaps be addressed in the documentation. Setting values in the configuration file is like setting them on the command line. On the command line, you have to specify the `domain` flag for each domain. For example:

`letsencrypt-auto --domain example1.com --domain example2.org`

This is what you would have to do in the configuration file BUT this doesn't quite work. If you do something like:
```
domains = example1.com
domains = example2.org
```
The value of `domains` is overwritten by "example2.org". I agree the use of `domains` is misleading and this limitation isn't ideal. Perhaps we could consider using a comma separated list for `--domains` in the future which would fix the problem.
