### ISSUE TITLE
venv.sh fails on Ubuntu 14.04 with "OSError: [Errno 30] Read-only file system"

### ISSUE THREAD

**Issue by TheNavigat** [letsencrypt/letsencrypt#1192]
```
local@local:/media/sf_letsencrypt$ ./bootstrap/dev/venv.sh
+ export VENV_ARGS=--python python2
+ ./bootstrap/dev/_venv_common.sh -r requirements.txt -e acme[testing] -e .[dev,docs,testing] -e letsencrypt-apache -e letsencrypt-nginx -e letshelp-letsencrypt -e letsencrypt-compatibility-test
+ VENV_NAME=venv
+ rm -rf *.egg-info
+ date +%s
+ mv venv venv.1446124598.bak
+ virtualenv --no-site-packages venv --python python2
Running virtualenv with interpreter /usr/bin/python2
New python executable in venv/bin/python2
Also creating executable in venv/bin/python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2339, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1405, in install_python
    os.symlink(py_executable_base, full_pth)
OSError: [Errno 30] Read-only file system
```

**Comment by kuba** [comment]
Is `/media/sf_letsencrypt` writeable? :D

**Comment by TheNavigat** [comment]
That is extremely weird.

I'm using a virtual machine to run Let's Encrypt.

```
drwxrwx---   1 root vboxsf 1462 Oct 30 02:46 sf_letsencrypt
```

These are the permissions for the folder, however, I can actually write to the folder. I think that is "somehow" managed by VirtualBox.

I copied the folder to the desktop and after setting the permissions correctly, and it worked. Spooky.

Sorry about that.
