### ISSUE TITLE
Error: PythonDialogErrorBeforeExecInChildProcess

### ISSUE THREAD

**Issue by denaje** [letsencrypt/letsencrypt#1198]
I attempted to run (substituting my.test.domain with my actual domain):

`# ./letsencrypt-auto --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d my.test.domain --nginx run`

Not really sure if that is the correct usage. Anyways, this was the output:

```
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --agree-dev-preview --server https://acme-v01.api.letsencrypt.org/directory -d my.test.domain --nginx run
An unexpected error occurred.
PythonDialogErrorBeforeExecInChildProcess
Please see the logfile 'letsencrypt.log' for more details.
```

The contents of letsencrypt.log:

```
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1058, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 979, in setup_logging
    cli_handler = cli_handler_factory(args, level, fmt)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 966, in _cli_log_handler
    handler = log.DialogHandler()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1038, in __init__
    self.backend_version())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1817, in backend_version
    use_persistent_args=False)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1466, in _wait_for_program_termination
    more precisely what happened."""))
PythonDialogErrorBeforeExecInChildProcess
```

I'm not super familiar with python packages, but it looks to me that there was something wrong with the `python2-pythondialog` package? I attempted to run `# pip install python2-pythondialog` but got:

```
Collecting python2-pythondialog
  Using cached python2-pythondialog-3.3.0.tar.bz2
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-vdfahv7g/python2-pythondialog/setup.py", line 32, in <module>
        from dialog import __version__ as VERSION
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-vdfahv7g/python2-pythondialog/setup.py", line 32, in <module>
    
        from dialog import __version__ as VERSION
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vdfahv7g/python2-pythondialog
```

All the above is on Arch Linux running as root. Did I do something wrong, or is something in my stack not supported?

**Comment by bmw** [comment]
Hi @denaje. Sorry to hear you're having trouble. The only "problem" I see with the initial command you ran is `--nginx` as `letsencrypt-auto` doesn't install our Nginx plugin as it is still very experimental and isn't ready for use. That wouldn't cause the problem you're having though.

I would strongly recommend not trying to `pip install` anything yourself as everything `letsencrypt-auto` does is isolated in a Python virtual environment that doesn't affect the rest of your system (unlike using systemwide `pip`).

Looking at the line in `dialog` that raised the exception in your traceback, I see the following message:
> possible reasons include:
>   - the dialog-like program could not be executed (this can happen
>     for instance if the Python program is trying to call the
>     dialog-like program with arguments that cannot be represented
>     in the user's locale [LC_CTYPE]);
>   - the system is out of memory;
>   - the maximum number of open file descriptors has been reached;
>   - a cosmic ray hit the system memory and flipped nasty bits.
> There ought to be a traceback above this message that describes
> more precisely what happened.

Being your system, you may have a better idea which one of these scenarios is likely the cause, but I would suspect taking a look at your [locale](https://wiki.archlinux.org/index.php/Locale). Let me know if this helps!

**Comment by denaje** [comment]
Thanks for the help. I attempted to run `dialog` manually, and it failed due to not being able to find libncurses. Turns out ncurses recently put out a major version with a breaking ABI, so I simply updated all my packages, and dialog works again. Tried out the letsencrypt, and that works too.
