### ISSUE TITLE
renewer fails due to http01_port = None

### ISSUE THREAD

**Issue by marcan** [letsencrypt/letsencrypt#1326]
By default, letsencrypt writes `http01_port = None` to the renewal config file. However, the renewer expects an int, and fails:

    Traceback (most recent call last):
      File "/usr/bin/letsencrypt-renewer", line 9, in <module>
        load_entry_point('letsencrypt==0.1.0.dev0', 'console_scripts', 'letsencrypt-renewer')()
      File "/usr/lib64/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/renewer.py", line 196, in main
        renew(cert, old_version)
      File "/usr/lib64/python2.7/site-packages/letsencrypt-0.1.0.dev0-py2.7.egg/letsencrypt/renewer.py", line 79, in renew
        config.namespace.http01_port = int(config.namespace.http01_port)
    ValueError: invalid literal for int() with base 10: 'None'

**Comment by bmw** [comment]
While related to #2468, `renewer.py` has been removed so this issue is no longer relevant.
