### ISSUE TITLE
Error: serverInternal :: The server experienced an internal error :: Error creating new authz

### ISSUE THREAD

**Issue by backav** [letsencrypt/letsencrypt#1327]
## whole logs here:

```log
2015-11-04 13:53:16,105:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-04 13:53:16,106:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-04 13:53:16,107:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151104
2015-11-04 13:53:16,107:DEBUG:letsencrypt.cli:Arguments: ['--agree-dev-preview', '--server', 'https://acme-v01.api.letsencrypt.org/directory']
2015-11-04 13:53:16,108:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoin
t#manual,PluginEntryPoint#standalone)
2015-11-04 13:53:16,111:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-11-04 13:53:16,168:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache): 
Traceback (most recent call last):
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-11-04 13:53:16,169:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 89, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-11-04 13:53:16,169:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7fa8eec18a10>
Prep: True
2015-11-04 13:53:16,170:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7fa8eec18a10> and installer None
2015-11-04 13:53:16,186:DEBUG:letsencrypt.cli:Picked account: <Account(92eedaddb9a47c274c973e63bc23706d)>
2015-11-04 13:53:16,187:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-04 13:53:16,190:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 13:53:17,396:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-04 13:53:17,401:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Wed, 04 Nov 2015 13:53:17 GMT', 'Strict-Transport-Security'
: 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 13:
53:17 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'TneOIQRZqvgn4Hqo21IxzA6OtlrJKqCkhpBtG9oX
qSE'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://a
cme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-04 13:53:17,402:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Wed, 04 Nov 2015 13:53:17 GMT', 'Strict-Tra
nsport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed,
 04 Nov 2015 13:53:17 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'TneOIQRZqvgn4Hqo21IxzA6O
tlrJKqCkhpBtG9oXqSE'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"h
ttps://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-04 13:53:17,402:DEBUG:letsencrypt.display.ops:No installer, picking names manually
2015-11-04 13:53:20,064:INFO:letsencrypt.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0039_key-letsencrypt.pem
2015-11-04 13:53:20,068:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0039_csr-letsencrypt.pem
2015-11-04 13:53:20,070:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0039_csr-letsencrypt.pem', data='0\x82\x02\x850\x82\x01m\x02\x000\x171\x150\x13\x06\x03U\x04\x03\x0c\x0cxiangyang.li0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xd7PI\x91M\r\x0e\xba\x90\xec\x1d\xef.\x13\x87#\xfc\x13\xed)\x82v\xe1\xfd\xdc.\xb8U\xf2%\xc2\xd2k\xf1m\xb1\x97\xe1W\x0f\xd6\x90\xe2\xd8p\xa0>4\x80\x87\xab\xe5\xa6F\x99\x88\x82\xabA\xa9\xd1K\x9b\xa8q\x8c\xa6\x9b\xc1\xd5T\x15\xdfJU\xd7D\xeb~\xfd\xdckL\xb1\r\x10\xfd\xb3\xe9\xf8\xddS%Ob\xb2s\xdc\xa0\x02\xd7:\x95\x96x\xd7\xf8\xdb\xdd\xd1\x08\xf2\x8cGl\x86V\xbd\x04\x0e\xe5]\xf2\x01\xc8)\xe3\x19D\x16\xdd\xe34\x90\x8f\xb8C0(\xde\xc4$\xa0\x0c\xcb\x90\xeb\xc2DeW\xca\x91\xf6j\xfd\xda5\x01\xc6:\x07\xac3@a\x9c\xb8U0\xa8\x92\x04\x8c\xce\xe9\x020\xc8\xf1s\x8bA\xb7\xd1Si8\xaa\xd3\xca\x08\x11\xe4\xc0:l\x1b\xf4\xb5\xbb\xec8\xcc`\xe8\x88L\x18`b\x04}\x0b\x06 \xccYobnq\x83\xd7\x82\xf4W\xd3^\xb7=r7\xbcl>\xb6\xe0&\'\xf1\x80\x1d\x0eAe\xdd&\xf6_\x04?\x0e\xc2\x00%\x02\x03\x01\x00\x01\xa0*0(\x06\t*\x86H\x86\xf7\r\x01\t\x0e1\x1b0\x190\x17\x06\x03U\x1d\x11\x04\x100\x0e\x82\x0cxiangyang.li0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\xd6\xb6\x9e\x03\xdf\xe7\xdaH\xa6X\x90}\xdfQ\xc6\x9901q\xcc]\x82\xaatc\x9a\x01\xa2 \xc0\xde\xe9FOK8\xa4\xb1\x16\x89\x00\x88\x83\x11\x16}Q\x17\xf8|Th\x80\xbf\xbd\xffN\xeb\x0f\xf2\x0e\xce\xd1\xa1[\xcf\x00I\x9dkn3\x02}\x144\xc1\xf3vq\x0eb6\xba\xb03`\xdcS\xc9=\x99\x9b\x0f\x8a\xcb\xf7\xd3\x87DJ\xc8T\xe7\x9d\xbdF]\xaeD_\x07\x15+?n\x08\x98\xbc\x173E\xd7\xf5\x9d(\x91\xd7{\xdb\x1b~\xfb\xc6\x7f\x9d\x92\xc3<`\xda\xd5\x14\xb9\xbd\xfd\x07\x9fT\xd9\xd4\xd4\xa3\xb2::P\x9c\xce\xad\xe2\xbd\xcc\xaa\x91-\x88\xf9\\\xc6#\x04\x07R\x9a\xee\x0eI[[\xa3c\xcb_\xa2\xf8\xd5\xf7\xc7\xdfD\xb3k\x98]\xedMQ\xd1\xa19\xab\x96\xc6\xa2\xa4\x1f\x9f\x8d\x13\x02Z\x98Bt\xdd\x024\x8a\\\xce\x92\xe6\xc5~\xf1\xeb\xc1(0.\x1c\x9d\x06\xfc\xda\xc6]\x91\xf9o\xcb\x9b\xbbV\x11\x9c\xca:\xc3|U\xf6\xe2\x0e.', form='der'), domains: ['xiangyang.li']
2015-11-04 13:53:20,071:DEBUG:root:Requesting fresh nonce
2015-11-04 13:53:20,071:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-04 13:53:20,073:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 13:53:20,621:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-04 13:53:20,623:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Wed, 04 Nov 2015 13:53:20 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 13:53:20 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '2X-6YJ9g82ERumMqNGsQ1HdlD9dHsZ8_pUAuJMOYtC8'}. Content: ''
2015-11-04 13:53:20,624:DEBUG:acme.client:Storing nonce: '\xd9\x7f\xba`\x9f`\xf3a\x11\xbac*4k\x10\xd4we\x0f\xd7G\xb1\x9f?\xa5@.$\xc3\x98\xb4/'
2015-11-04 13:53:20,624:DEBUG:acme.jose.json_util:Omitted empty fields: challenges=None, combinations=None, status=None, expires=None
2015-11-04 13:53:20,624:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "xiangyang.li"}, "resource": "new-authz"}
2015-11-04 13:53:20,625:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), x5tS256=None, cty=None, alg=None, jku=None, x5u=None, x5t=None, crit=(), kid=None, jwk=None, typ=None
2015-11-04 13:53:20,628:DEBUG:acme.jose.json_util:Omitted empty fields: jku=None, x5tS256=None, cty=None, x5c=(), x5u=None, x5t=None, crit=(), kid=None, typ=None, nonce=None
2015-11-04 13:53:20,628:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "pOpcSu2ynUl02RqT6Ws0uOYtU3pXX9Mg9j6iN3cDIte7R1e3O__GJx7D7y0srwyQe35K__DgLrVr3xlyycod_3glnyjs2kjrFF2vSQDsLbqmhJ9gAf2_VjeuR3I59mCLzusjPJ9fUa1ng-FRVziH_mV_MEa0Jnk7zde7GrweIVaEcg4WwCSZxaqV64nFFsAUQVlIFHdJzwVGQtRt8BqqwzzxrWa82SkPhL4B2iCD6BRGo4pe5qhRz1axlK2BPwbly3yrKstxhRMPm-uWh_suPiytKyUkfhYryN0c-qLBASOkUsO0F9aB9Am89Q60GPlMHiLzzj8Ok93gyhy3AQ4Fow"}}, "protected": "eyJub25jZSI6ICIyWC02WUo5ZzgyRVJ1bU1xTkdzUTFIZGxEOWRIc1o4X3BVQXVKTU9ZdEM4In0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJ4aWFuZ3lhbmcubGkifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "FpCRN14sL5WqcgOTR-qTAWS_eWB6fAOardayBv7Qo1lePgffsePorm5nF8ppS163PFaictA0ttI5L4955VfmYKXnMMk_7Ohw9e_f72rz2zGIEYOrXTKicBqw2u2ivGSAwDTW6n6wTFqttNfO28Vnc8zcyCywe6urxPbuWeQHKx_7vs_5VnyiVl_soqFFuHNUGWBCEJKkQHRWCxj6gAOqzhuhAgqTqOY5e2u1iIDWjHErO3p-9Lpl-zZnGsMpIjMhlmzXyreAcpWLfhuYvnyjrbfpeA_JzpnovhlPfByRuQcbWsgk5QsLr-1YOW-hKar3xkZKLhHCYTmZwFRO2MpBGw"}'}
2015-11-04 13:53:20,629:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 13:53:23,456:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 500 76
2015-11-04 13:53:23,458:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '76', 'Expires': 'Wed, 04 Nov 2015 13:53:23 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 13:53:23 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'bTkj4_pnX8h1gQR2MQViZj34bhgejo4EM7HS8VPeyr4'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-04 13:53:23,459:DEBUG:acme.client:Storing nonce: 'm9#\xe3\xfag_\xc8u\x81\x04v1\x05bf=\xf8n\x18\x1e\x8e\x8e\x043\xb1\xd2\xf1S\xde\xca\xbe'
2015-11-04 13:53:23,459:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Wed, 04 Nov 2015 13:53:23 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 13:53:23 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'bTkj4_pnX8h1gQR2MQViZj34bhgejo4EM7HS8VPeyr4'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-04 13:53:23,460:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/bac/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1138, in main
    return args.func(args, config, plugins)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/home/bac/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
```

**Comment by mitnk** [comment]
see [Known issue](https://github.com/letsencrypt/letsencrypt/wiki/Known-Issues) No 2.

**Comment by li-xiangyang** [comment]
@mitnk  what can i do ?

**Comment by mitnk** [comment]
Have to wait LE to fix the issue on server side. I have a .COM worked, but one .WANG has the same issue.

**Comment by kuba** [comment]
Another instance of https://github.com/letsencrypt/boulder/issues/1048, as @mitnk noted.

**Comment by kuba** [comment]
Actually, I'm not so sure:
```
$ host xiangyang.li
xiangyang.li has address 120.25.157.108
xiangyang.li mail is handled by 5 mail.xiangyang.li.
xiangyang.li mail is handled by 10 mail2.xiangyang.li.
```

@rolandshoemaker, could you have a look?

**Comment by backav** [comment]
This error happened when i use a ```gmail.com``` email account

**Comment by mydansun** [comment]
Can I delete CNAME records to deal the problem? I use the gmail account too

**Comment by JokerQyou** [comment]
I'm using a `protonmail.com` email account, and this error happened too. But I was dealing with a subdomain, don't know if that's related. The domain is `event.mynook.info`.

**Comment by mydansun** [comment]
I am waiting for the change in https://acme-v01.api.letsencrypt.org/build

**Comment by bmw** [comment]
Additional reports of this can be found in #1380, #1440, and #1461.

**Comment by Harvester57** [comment]
I would like to add that I could create certificates last week, without issues, and this error arose when I tried to re-generate them while adding some of my subdomains (which where whitelisted after my first certificates were generated).

To be precise, I successfully generated a certificate for "harvester.fr www.harvester.fr" last week, was working fine, and when "blog.harvester.fr reader.harvester.fr mail.harvester.fr" where whitelisted, I came across this error. And, the worst part, I can't regenerate certificates for "harvester.fr www.harvester.fr" anymore ! 

I read on other posts that it was due to DNS misconfiguration (CNAME vs. A) and I would like to point that all my subdomains are advertised using A. And that my DNS configuration didn't change during the week, so a configuration problem is very unlikely the culprit.

Hope that helps.

**Comment by bmw** [comment]
Anther report of this problem at #1525.

**Comment by bmw** [comment]
More reports: #1553

**Comment by ptibubu** [comment]
I'm in the exact same situation described by Harvester57: I suceeded to generate one certificate for a subdomain (sub1.example.com), but cannot generate for another (ex. sub2.example.com) (both whitelisted).
Changing DNS to google or opendns does not help.

**Comment by backav** [comment]
This error does not happen anymore!
But,I got a new probrom: #1610

**Comment by Harvester57** [comment]
Yep, working here since the ACME server update :)

**Comment by backav** [comment]
@Harvester57 Great job! Thanks : )

**Comment by the-real-tokai** [comment]
I experienced this too:
```
An unexpected error occurred.
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
Please see the logfiles in /var/log/letsencrypt for more details.
```

First I thought I hat some of the beta rate limits. I was brave enough and run the very same command a second time and then it worked flawlessly. Temporary hiccup? :smile:

I couldn't really extract anything useful regarding the actual issue out of the log file.

**Comment by strugglingyouth** [comment]
i have same question.  how to  do?
From https://github.com/letsencrypt/letsencrypt
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --server https://acme-v01.api.letsencrypt.org/directory -d www.tianfeiyu.com --renew --agree-dev-preview certonly
Version: 1.1-20080819
Version: 1.1-20080819
An unexpected error occurred.
Error: malformed :: The request message was malformed :: Error creating new authz :: Name is not whitelisted
Please see the logfiles in /var/log/letsencrypt for more details.

**Comment by the-real-tokai** [comment]
@strugglingyouth In your case the error should go away after December 3rd, 2015. Sounds like you're trying to get a certificate for a domain name that is not whitelisted for the closed beta test. Once the public beta tests start it should pass.

**Comment by strugglingyouth** [comment]
@the-real-tokai   I understand，thank  you。

**Comment by LVNeptune** [comment]
Unexpected error
ACME Server Returned:
{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz","sta
tus":500}

**Comment by ucoker** [comment]
Same issue, 
hello, @mitnk ,where is the [Known issue](https://github.com/letsencrypt/letsencrypt/wiki/Known-Issues) No 2. I can't find it.
