### ISSUE TITLE
Error creating new registration :: No MX record for domain xiangyang.li

### ISSUE THREAD

**Issue by backav** [letsencrypt/letsencrypt#1331]
### logs here:
```log
2015-11-04 15:32:38,895:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-04 15:32:38,895:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-04 15:32:38,895:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151104
2015-11-04 15:32:38,895:DEBUG:letsencrypt.cli:Arguments: ['--agree-dev-preview', '--server', 'https://acme-v01.api.letsencrypt.org/directory']
2015-11-04 15:32:38,896:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-04 15:32:38,898:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-11-04 15:32:38,991:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache): 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
    raise errors.NoInstallationError
NoInstallationError
2015-11-04 15:32:38,992:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 89, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-11-04 15:32:38,992:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x28d5d10>
Prep: True
2015-11-04 15:32:38,992:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x28d5d10> and installer None
2015-11-04 15:32:44,529:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-04 15:32:44,533:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 15:32:44,775:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-04 15:32:44,777:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Wed, 04 Nov 2015 15:32:44 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 15:32:44 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'VGwbDx9kvne0GLlz4ZpB25HZDbCHJCxED4ttO3UtgGk'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-04 15:32:44,778:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Wed, 04 Nov 2015 15:32:44 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 15:32:44 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'VGwbDx9kvne0GLlz4ZpB25HZDbCHJCxED4ttO3UtgGk'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-04 15:32:44,778:DEBUG:root:Requesting fresh nonce
2015-11-04 15:32:44,778:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {}
2015-11-04 15:32:44,779:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 15:32:44,900:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-reg HTTP/1.1" 405 0
2015-11-04 15:32:44,901:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Wed, 04 Nov 2015 15:32:44 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 15:32:44 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'O6uqHzVejnDJ-KEBPcCd9CRWdjQlIJ26il3h_c-vOzw'}. Content: ''
2015-11-04 15:32:44,902:DEBUG:acme.client:Storing nonce: ';\xab\xaa\x1f5^\x8ep\xc9\xf8\xa1\x01=\xc0\x9d\xf4$Vv4% \x9d\xba\x8a]\xe1\xfd\xcf\xaf;<'
2015-11-04 15:32:44,902:DEBUG:acme.jose.json_util:Omitted empty fields: certificates=None, key=None, agreement=None, authorizations=None
2015-11-04 15:32:44,902:DEBUG:acme.client:Serialized JSON: {"contact": ["mailto:wo@xiangyang.li"], "resource": "new-reg"}
2015-11-04 15:32:44,903:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jwk=None, x5u=None, kid=None, alg=None, cty=None, x5tS256=None, jku=None, x5t=None
2015-11-04 15:32:44,905:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, x5u=None, kid=None, cty=None, x5tS256=None, jku=None, x5t=None, nonce=None
2015-11-04 15:32:44,906:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "2F6wnjd3yFbGkUNaxr2nG-XPp56X8Y7Omjqvz4m2N_lWgHwiVz2wVHzQLUqbBE8YtX9TtIXMonxC9VT0r9t7ABm8DP9dwMchM5xigNPxDlpN6BwVfBnptOecDg0Bc16eVbKoIJUiKP8uq-Wbd6JbLHjWc4pEYBlQEyEFFWMqePoP4KOb-ZFGUR_M2y6cxihBbsXRdOUijn6X-BeHgitfuerVgH8Hq7lcTnsedpQTEyBf5EIcOvv5ssPPNnOGRSiASUAA8U5iDNTMB1-ELdPM3u4qPZF2SADjHNfedYnvs37QMnHRFB2akm8JBhkSaGLaGeNr_RjEq2NSvp-uYJeDkQ"}}, "protected": "eyJub25jZSI6ICJPNnVxSHpWZWpuREotS0VCUGNDZDlDUldkalFsSUoyNmlsM2hfYy12T3p3In0", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86d29AeGlhbmd5YW5nLmxpIl0sICJyZXNvdXJjZSI6ICJuZXctcmVnIn0", "signature": "BilxhQORdAsnIPZJv0gqCZ_WBEenghG6qImWhH5zqAdX-P4VCP9ki99YstGaaH9ShP9Xrncb8FNEJxVCN0LdGlgw7KX8-wn7wWiXBQcns28ZWs1MkaNsk1DbC6qCtXRbTQ-K3TSi66uDxTQ0n_khqoDVx4iuVmKxKKabbetPPlQY_AwHvb0NtmDM370gPGnkCJZUd7sAaBxG2npZgEXlnm9XC2CQQUHZvQMOMdK8jtk_2ne0upBazpkMFxij26yRG30xSXM7WUgv3YWviaV92sjyKeLEijCn1MPNVmnQsNzOyQ0sur2fy4KPRQpGR3EEzxGSWRvEexgNq-_Esa7W7A"}'}
2015-11-04 15:32:44,907:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-04 15:32:47,043:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-reg HTTP/1.1" 400 118
2015-11-04 15:32:47,045:DEBUG:root:Received <Response [400]>. Headers: {'Content-Length': '118', 'Expires': 'Wed, 04 Nov 2015 15:32:47 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 15:32:47 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'dw1Zu6C7dsjY5bZe4Np0V06gPCLzjGticMfxKuG9UXE'}. Content: '{"type":"urn:acme:error:malformed","detail":"Error creating new registration :: No MX record for domain xiangyang.li"}'
2015-11-04 15:32:47,045:DEBUG:acme.client:Storing nonce: 'w\rY\xbb\xa0\xbbv\xc8\xd8\xe5\xb6^\xe0\xdatWN\xa0<"\xf3\x8ckbp\xc7\xf1*\xe1\xbdQq'
2015-11-04 15:32:47,045:DEBUG:acme.client:Received response <Response [400]> (headers: {'Content-Length': '118', 'Expires': 'Wed, 04 Nov 2015 15:32:47 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 04 Nov 2015 15:32:47 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'dw1Zu6C7dsjY5bZe4Np0V06gPCLzjGticMfxKuG9UXE'}): '{"type":"urn:acme:error:malformed","detail":"Error creating new registration :: No MX record for domain xiangyang.li"}'
2015-11-04 15:32:47,046:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1138, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 479, in obtaincert
    le_client = _init_le_client(args, config, authenticator, installer)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 174, in _init_le_client
    acc, acme = _determine_account(args, config)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 161, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 89, in register
    regr = acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 97, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: malformed :: The request message was malformed :: Error creating new registration :: No MX record for domain xiangyang.li
```

**Comment by mitnk** [comment]
is `wo@xiangyang.li` a valid email? try use a different one.

**Comment by kuba** [comment]
```
$ host -t mx xiangyang.li
xiangyang.li mail is handled by 10 mail2.xiangyang.li.
xiangyang.li mail is handled by 5 mail.xiangyang.li.
```

Did you add it just recently, @backav?

@rolandshoemaker, can you have a look?

**Comment by kuba** [comment]
@backav, do you still have problems?

**Comment by kuba** [comment]
Ok, looks like you fixed it in, looking at #1327. Please yell at me if you think this should be reopened.

**Comment by backav** [comment]
@mitnk It's a  valid email.

**Comment by backav** [comment]
I set xiangyang.li MX to mail.xiangyang.li a long time age

**Comment by backav** [comment]
@kuba Yes, this error still happen to me.

**Comment by bmw** [comment]
@jsha, any thoughts?

**Comment by jsha** [comment]
My guess is that this is actually a DNS timeout in prod. Probably a related case of https://github.com/letsencrypt/boulder/issues/1047, which I'm working on.

**Comment by backav** [comment]
This error does not happen anymore!
But,I got a new probrom: https://github.com/letsencrypt/letsencrypt/issues/1610
