### ISSUE TITLE
Error: serverInternal :: The server experienced an internal error :: Error creating new authz

### ISSUE THREAD

**Issue by ghw** [letsencrypt/letsencrypt#1380]
When prompted me to generate a key error,
Use the following command parameter:

 ./letsencrypt-auto --agree-dev-preview --authenticator standalone --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --email webmaster@gehaowu.com -d gehaowu.com -d www.gehaowu.com auth
Updating letsencrypt and virtual environment dependencies......
Running with virtualenv: sudo /home/ghw/.local/share/letsencrypt/bin/letsencrypt --agree-dev-preview --authenticator standalone --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --email webmaster@gehaowu.com -d gehaowu.com -d www.gehaowu.com auth
An unexpected error occurred.
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
Please see the logfiles in /var/log/letsencrypt for more details.

http://pastebin.com/Feefwp9v
/var/log/letsencrypt/letsencrypt.log
2015-11-06 07:43:03,911:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-06 07:43:03,913:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-06 07:43:03,915:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151104
2015-11-06 07:43:03,915:DEBUG:letsencrypt.cli:Arguments: ['--agree-dev-preview', '--authenticator', 'standalone', '--server', 'https://acme-v01.api.letsencrypt.org/directory', '--rsa-key-size', '4096', '--email', 'webmaster@gehaowu.com', '-d', 'gehaowu.com', '-d', 'www.gehaowu.com']
2015-11-06 07:43:03,916:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-06 07:43:03,928:DEBUG:letsencrypt.cli:Requested authenticator standalone and installer None
2015-11-06 07:43:04,076:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x80af523d0>
Prep: True
2015-11-06 07:43:04,078:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x80af523d0> and installer None
2015-11-06 07:43:04,112:DEBUG:letsencrypt.cli:Picked account: <Account(0b33dcf11694cd437c872778cbe4bcac)>
2015-11-06 07:43:04,114:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-06 07:43:04,122:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-06 07:43:04,558:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-06 07:43:04,562:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Fri, 06 Nov 2015 07:43:03 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 06 Nov 2015 07:43:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'fYyLp-mJ21G0JyLZ_SIvg19CFRmrNm7Qhyqs1t-xiMI'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-06 07:43:04,563:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Fri, 06 Nov 2015 07:43:03 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 06 Nov 2015 07:43:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'fYyLp-mJ21G0JyLZ_SIvg19CFRmrNm7Qhyqs1t-xiMI'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-06 07:43:04,885:INFO:letsencrypt.crypto_util:Generating key (4096 bits): /etc/letsencrypt/keys/0006_key-letsencrypt.pem
2015-11-06 07:43:04,903:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0006_csr-letsencrypt.pem
2015-11-06 07:43:04,905:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0006_csr-letsencrypt.pem', data='0\x82\x04\x950\x82\x02}\x02\x01\x000\x161\x140\x12\x06\x03U\x04\x03\x0c\x0bgehaowu.com0\x82\x02"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x02\x0f\x000\x82\x02\n\x02\x82\x02\x01\x00\xbb\xabJ\x85\xa7\x85\xb2\x07\xe3V\x92.\xb0\xf31Q\x93\xab)\xf6\xbd\xd1\x96l\xa6@\x19\x8995\x1cX\xab\xce\xf2\xc4\xc9\xe6k\xe4\x9d\x80QJ\x0e\xbaV&\xa0\xdad\xe6\x9d?ta:*]\xd2p\xfb]\xa5C\x04vG\x19VD\xdfzVsE\xf5e\xd2\x81\xebgz\xee\xce\xc6c,z\x93\xd3\xdb\xaf\x00\x8c(\x02\xc2Z\xf5\x13\x18\xb5\xad\x89w\x86\n\x9fL\xaa\xee\xd5t\xe2(\x81\xed\xad\x96h<Ftj\x15\xfd\xc1\xc2\x0c\r\xf2h\xa0?\x8f \xfe\xc0\xce/\x1b\x14\x1aG\xb7\xe9p\xd9\x81.\xce*o\x02O\x19Z>B\x8a\xaf\xc8\xe9E\x02p\xcb\xc6/)\x89E\xf8\x18&\xb9\xcc\xc2\x02s9z\xe4)\xf7\xd35\xbb}Q\x05\'`\xc7]V\xf9&Y\x95Q\xa12\x12(\x0c\xc7a\xd4c\x14\xe3[[L[\x9fh\xb4VC\xf9~\xf8]\x92\x90\n\xfcK\x94F\x01L\xb0E\x9f\xe8\xb2\xbb\xae\x19\xd5\xb8V\x86^h\xb8.\xe8\xc9\x9aQ<\x04\xa2L\\e@\xb5\x11\xa5\xac\xa7\xa5h\x19\xb6\xd5\xf9\x1f9\x9eQ\x9d\xda\x1e7\xe7\xbe\x86\x874\xb5M\xd1\xd3\xa4|\xee\xb8\x1b\xa7\xc8{\xa6\xc1\xdd\xb5\xbc\x04\xe3h\xe8Rw\xbd\xden\xe3Sp\xec\xa4\x997\x00\x916_\xe9\x89f\xab\xb7F\x01\xb2G\x9e\x18f\xfd\xd03\xe1\x14Z\x02?T\x04\x8b\x8d\xa7q\xbf\x0f\xfe5\xec\xa6\xa0\xcb\xe3+\x03\xb2\xe8\xfcp@\xc1\xa5\x93\xc0\x8d1\xbf\\\x13\x95\xd6,\x9f~\x99\x9f@\x11\xcc\xb1"\xfd\x91\xedRm\xa9e\x94\xd0j(t<\xb0\x10\xde\x01\x16.g\x8ag\x98\xc6\x86\x80O3-\xc6\xf0U\xe6\xa06ej\x90\xd3\xa8\xdb(\xfe\xe8\x8e\tK/G\xceX\x0c\xb9\xfe\xb2I\x01aE\xa9HJ\xfe\xd7\x84\x96\x8cO\x0c\xb8\xe58\xa8\x16\xc0\xe9\xe7\xa5\x84\xcd\xdfmX\xbc\x17\xf0!\x18\xe3E\x19D\x0b\xd6Y\xc5\x86\x04\xa3\r$P\x17\xc1\xc4\rj\xd6J.\x18U\'\x83\xc6\x00?\xf5\xdd\x86\xed\xbaRN\x19u\x02\x03\x01\x00\x01\xa0:08\x06\t*\x86H\x86\xf7\r\x01\t\x0e1+0)0\'\x06\x03U\x1d\x11\x04 0\x1e\x82\x0bgehaowu.com\x82\x0fwww.gehaowu.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x02\x01\x00<\xfe\xb5Bj,\xfc\xd2\\_\x02]\xcf\xe3^\xf2\xcay\xcd?P4\x9a.\xaa\xce4\xa4\xb3X\x0f\xb5Y*\xbf\xd3\xd4\xed,\xf0x\xd7g9\xa6Wx\xda\x9e\xf8\xd0?q\x8aK$d|W5?\x8e7$l\xc1\xf6\x15Uh\xe0#a\x83\xc7\xbe\xbau\xcamR\x93S\xbd\x01\xe3\x89\x8eg\x1e\xdb\xd8\x9d\xd8\xfa\x04A;/mg\xb1#;\x92\xa3\xa5\xa6C^\x7f#yb\x80\x16\x8e\xa9|\x92\xb0\x0fX\x7f\x8f\x01>\xfeh\x92\xec\xe8\xffR\xf2\xe5\x93\xb5C\xbb?\xc59\x1b`:\xdf\x0b\x080\x88$\ru<\\\xf0\xbbz\x16\xd1\x97\xe0H\xee<D\xd1\x12\xee\xe2\x19R\xb4\x8e2\x8c\x9f\xda\x01\x04\x15\x17\xa2\xe6g\xf7`\xec\x99\x8b\xa3\xf5M\x1a\xef\xb0\xee\xcd\x1fuo\x08\x8c\xdc`\xce\xc6\xd8\x1b\xdfM\x96v\xba5\xa9\x1cf\x01\xee\xc0F/a\xf8\x80\x1a]j0%\xee\xea\xb0\x02\x18\x00\xe1\xbb\xc5$\x9d\xe4\x9f\x0b9\x08O\x13\xc3=6\xd8B!\x0b\rS}\xd0\x9d+\xef\x8f\x81\xac>\xab6\xa8\x9f\x80\x9a\xb4u\xab\xeb\xed\xf6\xffvl\xf0\x9c_\xc91\xe9\xcd95#\xf0x=6\xcc*\xc2\xea&\xc0M\xa16_}#\x89!.\x07\xefa\xf3`]\x95p%!\x06\xd0\xc4\xd6T\x1a{z\x06\x91\xf4#\xd1\xd9\x85/\x00\'\xaa\x83\xe4Y\x10\x96\x06_v\xe7\x05m\xe9"\xb0\xf0=\xe8l\xecA\x10r-\x9b\x88\xc4\xdf\x9d\xe1\xf4\xdbe\xaf\xbe|!\xb3\x01\x85\xcceP/\x8d\xbf\xbai\x14Z$gt\xc0\xef,do\x92\xbb\xbc\xbd;\xa0:\xda\xaaN(\xee@\xa8\xa0\xd9\x01\xde&\xf9\xb2\x05"W/w\x9f\r\xf4`\x0c\x0c\xff\x04\x9aZ!\x8d\x0e"\x01\x8b"\x91\x16\xd0\x11&\xfdz\x11&\xd5\xd7\n\x17\x15# \x83\xee`\x01P\x9c\xe0\t\xfc\xb1\xf5\xd9k\x86Z,Qo\x10b{\xc17\x138\xdcc\xea(\xb6\xe2}\xc2\x8d\xc5\x9fI\x12,\xa1\xcb\xbb\xe1\x03\xd3\x87\xab\xb5Y\x06\xe2\xdb\x87\xfb&', form='der'), domains: ['gehaowu.com', 'www.gehaowu.com']
2015-11-06 07:43:04,906:DEBUG:root:Requesting fresh nonce
2015-11-06 07:43:04,906:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-06 07:43:04,908:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-06 07:43:05,085:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-06 07:43:05,113:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Fri, 06 Nov 2015 07:43:04 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 06 Nov 2015 07:43:04 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'GOEalUPEyx0jAsRxzFbEt-axzY27Ld0_rs5Akj0sBXA'}. Content: ''
2015-11-06 07:43:05,114:DEBUG:acme.client:Storing nonce: '\x18\xe1\x1a\x95C\xc4\xcb\x1d#\x02\xc4q\xccV\xc4\xb7\xe6\xb1\xcd\x8d\xbb-\xdd?\xae\xce@\x92=,\x05p'
2015-11-06 07:43:05,115:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2015-11-06 07:43:05,116:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "gehaowu.com"}, "resource": "new-authz"}
2015-11-06 07:43:05,119:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), x5t=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None, alg=None, jwk=None, typ=None
2015-11-06 07:43:05,134:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), x5t=None, nonce=None, jku=None, x5tS256=None, cty=None, kid=None, x5u=None, typ=None
2015-11-06 07:43:05,135:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "5shANJCnJs2QIeWmeXpBl5E0kvK6aNz-bxq3Uof_EJZz_wDXMwqaSwTorLJAsBHMQYZRzxmXEe3LQKNkydFg9-dE_rAtNJhCBYtSbypxGWivnlvR3QkQL3gcUAhKU7FT1xJrmmMH1eZAIqPI7gw8vQnI4kY3tJC-8wajaERyG3b_rlxvCg-sJA8t3V0nAldPaOX01R0GyxRR1iZROOe617XwaRUvHBpw1X-W7YxbzcixIAtqFjezMRmimr8yc9SUsauqzk8FUurNDu-MHk9pPvQ0ZyCZGNIK4UetzllWZbNqEfYebDt-J9gTzJUNheKAK98w9QwozfAcUi0RzpFGiq88_QyBPAzLevPvvJFni2Aox5rDJIA5oC3E_GXbLo7kezRlAQieY_Hd10mnFiJFN2q1wAnUHiSo-bwprA1AOgO2dyJpB__peRmJGnuj1YK8sECWFdwDuTOfaWAiswPi8j7Bw3doxbBQpe-bndVW7Lp8WTFFdtmJyc2T7UJdG4y-F0PbmPUzalzY1AxvYD9V7ldO1mOjTOsSXGRa3KU1PqDpGl90_YrxmvFwV-8JwD-TgrYPIyXP8YBSU0me5kQh-tDMyiz0Sjpd_6pcn8YoPamLuOIa9fyifNw_-TamiVXLTtaC_iGJdBccYnsAzDPWyXfHWVAQYlJnMDBaMJ1_-IE"}}, "protected": "eyJub25jZSI6ICJHT0VhbFVQRXl4MGpBc1J4ekZiRXQtYXh6WTI3TGQwX3JzNUFrajBzQlhBIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJnZWhhb3d1LmNvbSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "bWocOD-neKCmUGRxGMMDJ2i_iouXDuFzvTkx4pEgzfSZqmYTV5YxdoQyjHvdSMC4mdYTczguXKEj_OgwN-425VsIX8waUEX6ZysJpjGotbuhyRVKThN7ihcJPLE70Z5qw240o9anBAuAeAJ37MhE5FnqNO1-yBI7x7IFTWS4-08o74XMeZDz7VASLpE-Xn4UPeX10SaZAYCWAH6yEIUOK-BOm3YPK9tcNRPn9VG2WG6DbIpV5DRqtru-dr0oeqrjaKnuh1J1u8KySsGwa4IzPrkiTgAFuSAWYSmN0cXGeC_mTmeQy8jho8oL7MsWetDLjdO_kSr5_4mEx6wrgZ9PQLpLbcIvUARv_juR9z6tAb7sqljLVlGEmtDhd6ayUQxi_oc1RQGDZMbJJ99HQtFmWYgLFSsRVN7VyMrMdBYmgq0osyVcPd58PXGqExItu0HsmpXxR73M4PfPRHl8jt5ObdgouwNkL2LPx8Q64ES_oZBSRJGqZhY8mCTRlvLKIe9uTIkd-Fz8xwEJsuGeY2s2Z-9vOd63EY5ogEql_CBFtpmx8vFvUAbELxK6DvSGS5dGgCZNjNIVihZDfEp6IK01n-D2_nAPmvnNx7Jk12cLsU8q03fD8BJWK3gQvT8SmqX_l3ntD55zn7mMWQVaa-2MKNEtjtJAoBdpZyCzUXdrKbA"}'}
2015-11-06 07:43:05,138:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-06 07:43:07,323:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 500 76
2015-11-06 07:43:07,328:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '76', 'Expires': 'Fri, 06 Nov 2015 07:43:06 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 06 Nov 2015 07:43:06 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'hBTYZKE_EGzFdGi_3M5ltizD1_VOpBxhOGLMHHfeUWY'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-06 07:43:07,328:DEBUG:acme.client:Storing nonce: '\x84\x14\xd8d\xa1?\x10l\xc5th\xbf\xdc\xcee\xb6,\xc3\xd7\xf5N\xa4\x1ca8b\xcc\x1cw\xdeQf'
2015-11-06 07:43:07,329:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Fri, 06 Nov 2015 07:43:06 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 06 Nov 2015 07:43:06 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'hBTYZKE_EGzFdGi_3M5ltizD1_VOpBxhOGLMHHfeUWY'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-06 07:43:07,332:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/ghw/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1138, in main
    return args.func(args, config, plugins)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/home/ghw/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz

**Comment by bmw** [comment]
Thanks for reporting the problem @ghw. Since #1327 is about the same problem, I'm closing this issue. I referenced this issue there so we can use your logs for debugging.
