### ISSUE TITLE
Error message with wrong domains is very cryptic

### ISSUE THREAD

**Issue by bisho** [letsencrypt/letsencrypt#1383]
Documentation doesn't make clear how to use -d flag, so I tried `-d <domain>.com,www.<domain>.com`. Apparently you should use two -d flags each with one domain.

That is fine, but the error message was really cryptic for novices, and any some typos while entering the domain name can cause the same issue.

I think lets encrypt should first validate that the domain is valid and report a understandable error message. For example, try resolving it (the server will need to do this anyway) and if fails to resolve, explain that the domain might be wrong or not properly configured in DNS.

```
2015-11-06 08:45:53,489:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/user/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1138, in main
    return args.func(args, config, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 210, in obtain_certificate
    csr = crypto_util.init_save_csr(key, domains, self.config.csr_dir)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 78, in init_save_csr
    csr_pem, csr_der = make_csr(privkey.pem, names)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/crypto_util.py", line 118, in make_csr
    value=", ".join("DNS:%s" % d for d in domains)
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/crypto.py", line 653, in __init__
    _raise_current_error()
  File "/home/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('X509 V3 routines', 'v2i_GENERAL_NAME_ex', 'missing value'), ('X509 V3 routines', 'X509V3_EXT_nconf', 'error in extension')]
```

**Comment by devnsec-com** [comment]
I totally agree with you. I've seen this error message too, it is really confusing.

**Comment by pde** [comment]
If someone would like to send a pull request to fix this, I'd recommend starting by adding an `ensure_configuration_sanity` function and calling it from [here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L1087) or [here](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/configuration.py#L40)

(currently aside from that single port check, all configuration sanity tests are performed on a per-verb basis, but clearly things like domain value checkin should occur for every verb)

**Comment by pde** [comment]
It should be possible to squash #1212 and #830 at the same time.

**Comment by joohoi** [comment]
I have started to work on this
