### ISSUE TITLE
OSX installation failure with virtualenv-13.1.2-py2.py3-none-any.whl

### ISSUE THREAD

**Issue by dantman** [letsencrypt/letsencrypt#1437]
Here's the installer failure I got on OSX:
```
Daniels-MacBook-Air:letsencrypt daniel$ ./letsencrypt-auto --debug
Bootstrapping dependencies for Mac OS X...
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Installing dependencies for augeas: pkg-config, libxml2, readline
==> Installing augeas dependency: pkg-config
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/pkg-config-
######################################################################## 100.0%
==> Pouring pkg-config-0.28.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.28: 10 files, 604K
==> Installing augeas dependency: libxml2
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/libxml2-2.9
######################################################################## 100.0%
==> Pouring libxml2-2.9.1.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, so it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libxml2/lib
    CPPFLAGS: -I/usr/local/opt/libxml2/include


If you need Python to find the installed site-packages:
  mkdir -p ~/Library/Python/2.7/lib/python/site-packages
  echo '/usr/local/opt/libxml2/lib/python2.7/site-packages' >> ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.1: 278 files, 11M
==> Installing augeas dependency: readline
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/readline-6.
######################################################################## 100.0%
==> Pouring readline-6.2.4.mavericks.bottle.2.tar.gz
==> Caveats
This formula is keg-only, so it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.2.4: 31 files, 1.6M
==> Installing augeas
==> Downloading http://download.augeas.net/augeas-1.0.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/augeas/1.0.0
==> make install
==> Caveats
Lenses have been installed to:
  /usr/local/share/augeas/lenses/dist
==> Summary
🍺  /usr/local/Cellar/augeas/1.0.0: 339 files, 3.4M, built in 83 seconds
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Downloading ftp://invisible-island.net/dialog/dialog-1.2-20130928.tgz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/dialog/1.2-20130928 --mandir=/usr/loc
==> make install
🍺  /usr/local/Cellar/dialog/1.2-20130928: 7 files, 660K, built in 20 seconds
virtualenv Not Installed
Installing with pip
Downloading/unpacking virtualenv
  Downloading virtualenv-13.1.2-py2.py3-none-any.whl (1.7MB): 1.7MB downloaded
Installing collected packages: virtualenv
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/wheel.py", line 207, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-1.5.4-py2.7.egg/pip/wheel.py", line 194, in clobber
    os.makedirs(destsubdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/virtualenv-13.1.2.dist-info'

Storing debug log for failure in /var/folders/t4/lr96d_b55fd7f5cb1c_60rl80000gn/T/tmpHWW4af
```

**Comment by the-real-tokai** [comment]
Looks like you need `sudo` for the Python stuff at the end, but that conflicts with the official Homebrew philosophy (recommend to install w/o admin privileges, see http://brew.sh/ )… additionally Homebrew stuff probably will run into conflicts with your Fink or MacPorts installation.

The `letsencrypt` client sucks a lot of dependencies into the system and alters your installation in ways you perhaps didn't anticipated (or even wanted). This is not well documented (unless you read the letsencrypt source code first.)

I recommend to install a virtual machine with a tiny Linux installation and run/ try the `letsencrypt` client that way first (I used VirtualBox + Ubuntu Server), that way you don't break your OS X installation.

**Comment by dantman** [comment]
> I recommend to install a virtual machine with a tiny Linux installation and run/ try the letsencrypt client that way first (I used VirtualBox + Ubuntu Server), that way you don't break your OS X installation.

Actually I'd like to try and help improve the OSX support instead.

Besides, my Air has enough of a burden running everything else without me adding a vm into the mix.

**Comment by dantman** [comment]
...ok, I didn't expect something that's supposed to be installable everywhere to get certificates to require a full maria database and rabbitmq daemon. I guess I'll go with the docker install.

**Comment by hwine** [comment]
> Looks like you need sudo for the Python stuff at the end, but that
> conflicts with the official Homebrew philosophy (recommended to install
> w/o admin privileges, see http://brew.sh/ )

virtualenv is installed via pip, not homebrew. See hwine/letsencrypt@b5ed378bc6138183857a43a68ada3bde798f6c38 for a possible workaround.

**Comment by hwine** [comment]
>...ok, I didn't expect something that's supposed to be installable everywhere to get certificates to require a full maria database and rabbitmq daemon. I guess I'll go with the docker install.
@dantman fwiw, my experience was just cert request as of yesterday. Any auto installation is disabled (even with --debug)

**Comment by crispgm** [comment]
Using homebrew to install python even if u have an OSX python
That would be okay.

**Comment by pde** [comment]
@dantman @crispgm @hwine can any of you review #1895?
