### ISSUE TITLE
Error: serverInternal :: The server experienced an internal error :: Error creating new authz

### ISSUE THREAD

**Issue by aleng20** [letsencrypt/letsencrypt#1461]
log file:

```javascript
2015-11-11 07:11:17,704:DEBUG:letsencrypt.cli:Root logging level set at -10
2015-11-11 07:11:17,706:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-11 07:11:17,707:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151108
2015-11-11 07:11:17,707:DEBUG:letsencrypt.cli:Arguments: ['--server', 'https://acme-v01.api.letsencrypt.org/directory', '-vvvv', '--text', '--agree-dev-preview', '--agree-tos', '-a', 'standalone', '-d', '**.me']
2015-11-11 07:11:17,708:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-11 07:11:17,710:DEBUG:letsencrypt.cli:Requested authenticator standalone and installer None
2015-11-11 07:11:18,060:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7f8fa5855890>
Prep: True
2015-11-11 07:11:18,062:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7f8fa5855890> and installer None
2015-11-11 07:11:18,083:DEBUG:letsencrypt.cli:Picked account: <Account(188a4c7fc54e7e650771122eed632c48)>
2015-11-11 07:11:18,084:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-11 07:11:18,089:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-11 07:11:18,695:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
.
.
.'
2015-11-11 07:11:21,571:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Wed, 11 Nov 2015 07:11:21 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 11 Nov 2015 07:11:21 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'JPJZlRGLqfWU9sKePE6YGfyeP9PRX1H0gKQ3px39y3g'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
2015-11-11 07:11:21,576:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1140, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 628, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 544, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz"

```

Debian8,nginx,

**Comment by aleng20** [comment]
i've even try Docker

```javascript
docker run -it --rm -p 443:443 -p 80:80 --name letsencrypt -v "/etc/letsencrypt:/etc/letsencrypt" -v /var/lib/letsencrypt:/var/lib/letsencrypt" quay.io/letsencrypt/letsencrypt:latest auth
```

however, give me the same error

**Comment by bmw** [comment]
I'm glad you resolved the problem @aleng20. Thanks for reporting the issue and including your logs. Since #1327 is about the same problem, I'm closing this issue. I referenced this issue there so we can use your logs for debugging.
