### ISSUE TITLE
Simple-verify in all plugins

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#1586]
We should attempt to verify our challenges for correctness in all plugins. Doing this would simplify debugging for us and our users.

**Comment by TheNavigat** [comment]
I find this relatively confusing. I can't find any other plugins that use simple-verify.

**Comment by bmw** [comment]
`manual` is the only plugin that uses `simple_verify`. This issue proposed that all of our plugins should use it.

**Comment by TheNavigat** [comment]
I'm having a problem with adding ```simple_verify``` to ```standalone.py``` plugin.

```python
    def perform2(self, achalls):
        """Perform achallenges without IDisplay interaction."""
        responses = []

        for achall in achalls:
            if isinstance(achall.chall, challenges.HTTP01):
                server = self.servers.run(
                    self.config.http01_port, challenges.HTTP01)
                response, validation = achall.response_and_validation()
                self.http_01_resources.add(
                    acme_standalone.HTTP01RequestHandler.HTTP01Resource(
                        chall=achall.chall, response=response,
                        validation=validation))
            else:  # tls-sni-01
                server = self.servers.run(
                    self.config.tls_sni_01_port, challenges.TLSSNI01)
                response, (cert, _) = achall.response_and_validation(
                    cert_key=self.key)
                self.certs[response.z_domain] = (self.key, cert)
            self.served[server].add(achall)
            responses.append(response)

            if not response.simple_verify(
                    achall.chall, achall.domain,
                    achall.account_key.public_key(), self.config.http01_port):
                logger.warning("Self-verify of challenge failed.")

        return responses
```

That code fails with these errors.

```
======================================================================
ERROR: test_perform2 (letsencrypt.plugins.standalone_test.AuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nav/Documents/letsencrypt/letsencrypt/plugins/standalone_test.py", line 177, in test_perform2
    responses = self.auth.perform2([http_01, tls_sni_01])
  File "/Users/nav/Documents/letsencrypt/letsencrypt/plugins/standalone.py", line 252, in perform2
    achall.account_key.public_key(), self.config.http01_port):
  File "/Users/nav/Documents/letsencrypt/acme/acme/challenges.py", line 432, in simple_verify
    return self.verify_cert(cert)
  File "/Users/nav/Documents/letsencrypt/acme/acme/challenges.py", line 396, in verify_cert
    sans = crypto_util._pyopenssl_cert_or_req_san(cert)
  File "/Users/nav/Documents/letsencrypt/acme/acme/crypto_util.py", line 174, in _pyopenssl_cert_or_req_san
    for i in range(cert_or_req.get_extension_count())]
AttributeError: 'int' object has no attribute 'get_extension_count'
-------------------- >> begin captured logging << --------------------
acme.challenges: WARNING: Using non-standard port for http-01 verification: 4321
acme.challenges: DEBUG: Verifying http-01 at http://localhost:4321/.well-known/acme-challenge/ZXZhR3hmQURzNnBTUmIyTEF2OUlaZjE3RHQzanV4R0orUEN0OTJ3citvQQ...
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
acme.challenges: ERROR: Unable to reach http://localhost:4321/.well-known/acme-challenge/ZXZhR3hmQURzNnBTUmIyTEF2OUlaZjE3RHQzanV4R0orUEN0OTJ3citvQQ: HTTPConnectionPool(host='localhost', port=4321): Max retries exceeded with url: /.well-known/acme-challenge/ZXZhR3hmQURzNnBTUmIyTEF2OUlaZjE3RHQzanV4R0orUEN0OTJ3citvQQ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1118d3350>: Failed to establish a new connection: [Errno 61] Connection refused',))
letsencrypt.plugins.standalone: WARNING: Self-verify of challenge failed.
--------------------- >> end captured logging << ---------------------
```

I think I do understand why it occurs, but I'm not sure how to fix it.

**Comment by bmw** [comment]
So the client team discussed this issue in a meeting today and we don't think we want to implement this. I feel really bad writing this because I know @TheNavigat has invested a lot of time in #1876, but after revisiting this issue, we think it's a bad idea.

The problem is we can't do this reliably. Some of the reasons for this are identified in this [comment](https://github.com/letsencrypt/letsencrypt/pull/1876#issuecomment-183561066). Additionally, things like firewalls are a problem. We've wanted to do things like this before and in the end determined that we cannot do so.

Since we can't do this reliably, we'll spread misinformation. We print warnings saying "Self-verification failed" when there's no problem at all. Furthermore, since the information can be invalid, it doesn't have much use for debugging as suggested by this issue.

With all this in mind, we think that the additional complexity of doing this isn't worth the little/no gain it provides and I'm closing this issue.
