### ISSUE TITLE
Possible TLS-SNI-01 DV failure from cli.ini?

### ISSUE THREAD

**Issue by KeiroD** [letsencrypt/letsencrypt#1615]
I'm on Ubuntu 14.04.

`./letsencrypt-auto --apache -c cli.ini -d heimkoma.com` gives the following error:

I'm having to create this on a separate server that doesn't have the SSL virtualhost for heimkoma.com

```
Failed authorization procedure. heimkoma.com (tls-sni-01): unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge

IMPORTANT NOTES:
 - The following 'unauthorized' errors were reported by the server:

   Domains: heimkoma.com
   Error: The client lacks sufficient authorization

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
```

`cli.ini` contains the following:

```
# This is an example of the kind of things you can do in a configuration file.
# All flags used by the client can be configured here. Run Let's Encrypt with
# "--help" to learn more about the available options.

# Use a 4096 bit RSA key instead of 2048
rsa-key-size = 4096

# Always use the staging/testing server
server = https://acme-v01.api.letsencrypt.org/directory

# Uncomment and update to register with the specified e-mail address
email = foo@example.com

# Uncomment to use a text interface instead of ncurses
# text = True

# Uncomment to use the standalone authenticator on port 443
# authenticator = standalone
# standalone-supported-challenges = tls-sni-01

# Uncomment to use the webroot authenticator. Replace webroot-path with the
# path to the public_html / webroot folder being served by your web server.
# authenticator = webroot
# webroot-path = /usr/share/nginx/html
```

**Comment by pde** [comment]
You can't run the Apache authenticator on a system other than the one that `heimkoma.com` is pointed at, because the Let's Encrypt CA needs to connect to `heimkoma.com` in order to verify your response.

Depending on what kind of access you have on the system that the heimkoma SNI vhost actually runs on, you might have more luck with the webroot or manual authenticators.

**Comment by pde** [comment]
There's also some code [here](https://github.com/letsencrypt/letsencrypt/pull/1419) that might work for you for performing webroot authentication over rsync.

**Comment by KeiroD** [comment]
Er... is it a possibility that the fact that `Ghost` runs on heimkoma.com that might be interfering with this?

**Comment by pde** [comment]
I don't know enough details about your setup to know exactly what the issue is, but when you say, "I'm having to create this on a separate server that doesn't have the SSL virtualhost for heimkoma.com", it sounds like you're doing something that would produce this error!

Please ask for help on https://community.letsencrypt.org!

**Comment by pde** [comment]
Or are you saying that you're making the `client.ini` file on one machine, and deploying it via Ghost, and it isn't working when it gets there?

**Comment by pde** [comment]
If this method works when you run the client manually on heimokma.com, but not when you deploy `cli.ini` via Ghost, then it's possible there's a bug in `cli.ini` processing.  Can you get the client to work manually?

**Comment by KeiroD** [comment]
Reproducing this on the server that hosts `heimkoma.com` still produces that error.

I'm not entirely sure why LE's CA is unable to authenticate. Currently, `heimkoma.com` is running `Ghost` ... or well, was before I stopped `nginx` and `Ghost` so that the `apache` authenticator would work. DNS is properly pointed, the service is set up properly.

Right now I'm just using the `apache` authenticator to try getting the SSL certificate set up properly on this server. I have another test setup that works perfectly with just `apache` but I've yet to get that one whitelisted for actual SSL roll-outs. That one's still running against the staging/test ACME server.

I'll update comment in a few more minutes with more detail.

**Comment by KeiroD** [comment]
OK, so `./letsencrypt-auto` correctly detects `heimkoma.com`

However, it seems that LE is not authorizing my server to actually do the SSL cert generation with it... despite being whitelisted?

Now, `/var/log/letsencrypt/letsencrypt.log` says:

```
2015-11-25 02:58:55,237:DEBUG:letsencrypt.cli:Root logging level set at 30
2015-11-25 02:58:55,237:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-11-25 02:58:55,237:DEBUG:letsencrypt.cli:letsencrypt version: 0.0.0.dev20151123
2015-11-25 02:58:55,237:DEBUG:letsencrypt.cli:Arguments: ['-c', 'cli.ini']
2015-11-25 02:58:55,238:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-11-25 02:59:07,420:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2015-11-25 02:59:07,750:DEBUG:letsencrypt.display.ops:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fd44334fa90>
Prep: True
2015-11-25 02:59:07,751:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fd44334fa90> and installer <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7fd44334fa90>
2015-11-25 02:59:09,922:DEBUG:letsencrypt.cli:Picked account: <Account(23911a14774054650896f028934047f0)>
2015-11-25 02:59:09,922:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-11-25 02:59:09,926:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-25 02:59:10,223:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-11-25 02:59:10,227:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '3PflWs6yCnQQq2palOP0nNL-XRYl3nXSGDlSDCKAAdI'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-25 02:59:10,227:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '3PflWs6yCnQQq2palOP0nNL-XRYl3nXSGDlSDCKAAdI'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-11-25 02:59:10,501:INFO:letsencrypt.crypto_util:Generating key (4096 bits): /etc/letsencrypt/keys/0011_key-letsencrypt.pem
2015-11-25 02:59:10,516:INFO:letsencrypt.crypto_util:Creating CSR: /etc/letsencrypt/csr/0011_csr-letsencrypt.pem
2015-11-25 02:59:10,516:DEBUG:letsencrypt.client:CSR: CSR(file='/etc/letsencrypt/csr/0011_csr-letsencrypt.pem', data='0\x82\x04\xe10\x82\x02\xc9\x02\x01\x000\x1a1\x180\x16\x06\x03U\x04\x03\x0c\x0feidolonhost.com0\x82\x02"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x02\x0f\x000\x82\x02\n\x02\x82\x02\x01\x00\xde\xd2\x00b\x12\xc4d8s\xb8\xacG\xf5]%\xec\xa5\xc5\xcd\x90T=\xfb\x8c8b\xd9\x9d\t]eO\xc7\xf3\xf2#\x0f\x081g\x9d9e\xf4\xa3\xeaB\x05\x9e\x13G\x98\xd2\xad\x83\xd9\x96<\x13\x90\xf3\x9e\xa118\x07\x17$\xaf\xd1A\x8eu\xfb\x9ca\xed\xf1,\xa0^\xc3P\xbc\xdc"\xd2\xee\x13\xadv\x1c\x9c\x80\xde`\xac\xf0\xd5\rT\xff\x9d \xb08\xc7\xab6n\xcd\xcf\xa6%z\xd1\xf7\xa0^\xd4L\x17\xa5\x02\x064\xdas\xf3\xeb\x80u\xea\xc1\x05\xd02<\xf8\x81\xe8\xe0\x95\xab\xad=+\\h\xce\xa8\xc6\xae\x82\x81\xbe3dm\x98\x9b\xae\x0cv\x19]W\x9a\xdd\xc66\xfb\xd5\x1c\x8f\xf98\xca\xa6\\\xcc\x9d\xf4\x1e/\xd0\x98\xb2\xa1\xff\x17:\xbb\x19\xb2f/8\x97UN\xd5}l\xab\xeb\x9f\x99c\xbe\xe3\xa3\x88\x85\x96a\x11-;\x0b\x0c<Bl\xf1\xd7\xebv_\x1d\xbf\xecu4\x13\x84?\xefw5S\xfac\xb8\xd3\xc2\xf6\xe4s-\\\xd0UI\xbc\x0f\xaaY\x1c\xc3\xce\xe1\x81\xe0\x1c\xf8\x96\x03s\xae\x1co\xafLCp\xe2\x83\xa5:\x16\xef\xa7\xd2\xadI,o\t"+z\'k"4%\xa3f\xe7\xb2\xb607\xd3\x90\to\x13w.\xf8t\xc1\xe7E\x1d\xd6\x12,G\xd8;d\x1b\xb4\x84z\xc1 0\xaf\x9c\x0b\x8b\x91\x9c@\xcdRf\xc2\x82g\x9b1Z\x02\xc4O\x94L,\xaeM\xd1\x10\x89b\x9e7hN\xdb U\x8cT\x95h\xbb\x97)\xe7\x8f\xb7\x1b4H\xd7\xdc\rO\x1c\xb2x35\xa1\xc2\xccG\xd2uL\x06\xc4\xd0\x8ft\xfa\x17F]\xef\xf3\xfc\x92\xda\xf5\xd4\x0e\xa1\xfe\xdd.\x13\xc9hf\xd5\xf9j\x8f\xbc\xbc,s\x04Ylx\xc7\xe2\x89\xe5n\xcc\x12A\xbe\xe4x\x08\xf0\xb4g\xf8]:];\x08i\x06\xa0u\xc1\xa23\x0c_\xe8\xe0\xc3\xd2\x9a\xdf\xca\xe3q~\x81\xc4\xe1\x04\x93\xf9fG\x97\xc1<\xbaq1\xf7Tj\x82\xb3Q\x06\x88\xe3\x97+\x13\x90\xa0zH\xb8\r\xae\xdd\x10\xca\x9b4n\x91\x02\x03\x01\x00\x01\xa0\x81\x810\x7f\x06\t*\x86H\x86\xf7\r\x01\t\x0e1r0p0n\x06\x03U\x1d\x11\x04g0e\x82\x0feidolonhost.com\x82\x1awww.status.eidolonhost.com\x82\x0cheimkoma.com\x82\x16status.eidolonhost.com\x82\x10www.heimkoma.com0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x02\x01\x00_4\xba\xdc]\xfaZ\xb5\x15\xa3\xdd\x1f\x96vr\xc9?\xda\xc5Rxj\x9d7\x84\x86l\xd8\xc6_w2Q\xb0t\nsQ\xa2m=U\xc6\x1f\x9b\x00\x12\xac\xeeY\xdd=\xefe\x19\xe3W\xab^k\xd6\xdbw\xb8=o\xeaii\xe6F\x9bS\x1b\xfay5\xa3\xb4:-\x8eEp\x82\xe4/d\xc2\x01\xa2\x99\xa9O&\xb3\xe4G\x8d\xe8\xdc9;a\x9c-\xbfiN\x0e\xf7\x0f\xaa\xc4\x85\xe0\x83\x1eY\xa7\nIm\xb6\xbb\x98(B\xe3;\x16r?-\xd9\xac\x8e\xa9\xd9\xda\x0fz\x88a3\xddE\xdfi\x99\xd7\xf7(\x8b\xa1\x90c\xccK\x91\x8b\x89\xdb\xd63\xd3\xe0\xe1\x01\xab\x8d\xa9$Q|9\xc7\x03\x8cZ(\xe5\x98P\x9d.\xf3\xcb\xe6\xc7\xfd\x06:\x89\x92\x0bBxP\xcb\xbbv\xc0\xf2\xc9\x118\xb4\x01\x0b}\x99\xac\xf0\xecQ-)\x07\xbd\x15\xaf\xaf\xf0\x9b^\x19>\r9\xf4T\xed\xc2t\xdd\xfab\n\xe4\xcd\xec"-aq\t\x15\x90L\x8c\x17\x8eD9\x93\x18\x17f\x932iT\xf3\xfbl{\xa8W-\x06$\xbbX\xabt\xfa>\x91&&\xc6\xf7\')-4\xef\x97\xba{\x1b\xee\xc9a\xa7\x11\xcf\x18\xdb\xbf\x1d\xa8\xb7\xf1\xa0k\x0f<|\x917\xcd\x08\x0cn\x19\'\x1e\x81\x90\xc3|\xf3*\xddr\xc2>\xc8Aa\x06]\xbd8I\xcb\x894\x9eQq\xf37\xc2]H4\xda\x9f\xdc/d\xa8\xc7G\x84\xfe%\x1drD\xe2\xc60-\x08\x16\xb2\x83\xc2\xb4\x0bt\x1f\x1f;%\x827\xf5M\xcf\x7fS\xf1,,\xce\x1f%\xd4>\x08\xa1.X\x19\x15\xfc \x1f\xbc\x90\x13\x86\xb4\xf9\x98\xb7\x19\xda\xd17~T\xe0\xf6\x9d>b\x8ah2i\xd4\xaa\x82\x99\xea\x86f,f\x01\x80R\xf9M\xf2\x99\xfe3\xc6\x7f\x1d\xd6k\xc190\x93V\x94i:#j\x80\xe6)*r\x19\xc6\x98\x12\x1ac[\xbel\xe1\xfc\xb8\x90)\x08l\x14\xab$#\x17\xddz\x07[)O{\nO\x0c\xcb\x0f\xdb|e\xcf5\xf1\x94l\x13\xff\xb3\xc1\xf5\xf8\xc9', form='der'), domains: ['eidolonhost.com', 'www.status.eidolonhost.com', 'heimkoma.com', 'status.eidolonhost.com', 'www.heimkoma.com']
2015-11-25 02:59:10,516:DEBUG:root:Requesting fresh nonce
2015-11-25 02:59:10,516:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2015-11-25 02:59:10,517:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-25 02:59:10,591:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2015-11-25 02:59:10,594:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'Bt8Su1fb90s_42T6idJ0pWe1fSVtYhlsVT_6ZqU88T8'}. Content: ''
2015-11-25 02:59:10,595:DEBUG:acme.client:Storing nonce: '\x06\xdf\x12\xbbW\xdb\xf7K?\xe3d\xfa\x89\xd2t\xa5g\xb5}%mb\x19lU?\xfaf\xa5<\xf1?'
2015-11-25 02:59:10,595:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2015-11-25 02:59:10,595:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "eidolonhost.com"}, "resource": "new-authz"}
2015-11-25 02:59:10,596:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, jwk=None, x5t=None, x5tS256=None, cty=None, x5u=None, typ=None, alg=None, jku=None
2015-11-25 02:59:10,598:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, nonce=None, x5tS256=None, cty=None, x5t=None, x5u=None, typ=None, jku=None
2015-11-25 02:59:10,598:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "xXz_syLd6vzVV0mQaJUwQxQhsB36djbDHoCJW4xBQ4sMnFrc9-EWuV3oIWt0Ry6wGUxuIkJifHBd9atoFwolM8o32wgu2EaVcvcN0cj1WsIESp5-Hfvauhc9pBQoX4TYOcQDDVaIDG7x0btGrb04JhiCvq6HKwFgyK-kKu78OvtZzspqXPA1TTE94uLkm1RVFcPGY1qB7FRtL0FYLtTsJr4_c5vNGjKJPfgjkXVLxx9oCwMUVzKDbTrIE0sjDKTKzb-Hz6pI_JpwDHuECz-0coemMuGgfsp13O2WOb6To9oCKQCyYNt5QHN2GHyHoyRMDNzJxcKiCYmVEXan2_GSaQ"}}, "protected": "eyJub25jZSI6ICJCdDhTdTFmYjkwc180MlQ2aWRKMHBXZTFmU1Z0WWhsc1ZUXzZacVU4OFQ4In0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJlaWRvbG9uaG9zdC5jb20ifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "AkXp83J2LME-xnHK4fG09CUNeUytn0DkGbruspY0UgjPVA01vZnwqsXPEMSGz0lwXXLU2AbAyNRxq3LZOX_EgucfoOBblg8nG5gLk2iLbW8WRE1fca1gvjl2bZGE1MIiltE7DE8iG3YWb3lhrRYCFreciuCOFeNh298x037e17lvhXtKikSKaMHr3qbGYGAs0yUk_bDsuUAJv6LNvfpXt4YULkeHiJLajIVObscwZRKqvJZriyQjEV0FgwwH8IUlqBmTz1qx-shHDIjUt1TkZoErCq68hiDaDTRCiauksApsyvLJ5_3t8rGnfvRLkm9kdocllSuquxIh50KTtsExQA"}'}
2015-11-25 02:59:10,600:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-25 02:59:10,723:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 566
2015-11-25 02:59:10,726:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '566', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'Nx-lb5_KaZ7TFqddGJVrUC6KfRSwPEzNddJ3SnGTVKA'}. Content: '{"identifier":{"type":"dns","value":"eidolonhost.com"},"status":"pending","expires":"2015-12-02T02:59:10.669484063Z","challenges":[{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc/473021","token":"xTs_qqZ4OXF5dMkUpVfOd7KAo9pKxeg9vYa_CHiWOFo"},{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc/473022","token":"EJpKG9pg4eY11H_acr0Sd1LujEqX3eNMe9fL-oDDUBM"}],"combinations":[[1],[0]]}'
2015-11-25 02:59:10,727:DEBUG:acme.client:Storing nonce: '7\x1f\xa5o\x9f\xcai\x9e\xd3\x16\xa7]\x18\x95kP.\x8a}\x14\xb0<L\xcdu\xd2wJq\x93T\xa0'
2015-11-25 02:59:10,727:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '566', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'Nx-lb5_KaZ7TFqddGJVrUC6KfRSwPEzNddJ3SnGTVKA'}): '{"identifier":{"type":"dns","value":"eidolonhost.com"},"status":"pending","expires":"2015-12-02T02:59:10.669484063Z","challenges":[{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc/473021","token":"xTs_qqZ4OXF5dMkUpVfOd7KAo9pKxeg9vYa_CHiWOFo"},{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/lgsZHYJMhQItgcqYVjERe3Ss9h6SB7T52KoTo1RKLcc/473022","token":"EJpKG9pg4eY11H_acr0Sd1LujEqX3eNMe9fL-oDDUBM"}],"combinations":[[1],[0]]}'
2015-11-25 02:59:10,728:DEBUG:acme.jose.json_util:Omitted empty fields: expires=None, challenges=None, status=None, combinations=None
2015-11-25 02:59:10,729:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "www.status.eidolonhost.com"}, "resource": "new-authz"}
2015-11-25 02:59:10,730:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, jwk=None, x5t=None, x5tS256=None, cty=None, x5u=None, typ=None, alg=None, jku=None
2015-11-25 02:59:10,731:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), kid=None, nonce=None, x5tS256=None, cty=None, x5t=None, x5u=None, typ=None, jku=None
2015-11-25 02:59:10,731:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "xXz_syLd6vzVV0mQaJUwQxQhsB36djbDHoCJW4xBQ4sMnFrc9-EWuV3oIWt0Ry6wGUxuIkJifHBd9atoFwolM8o32wgu2EaVcvcN0cj1WsIESp5-Hfvauhc9pBQoX4TYOcQDDVaIDG7x0btGrb04JhiCvq6HKwFgyK-kKu78OvtZzspqXPA1TTE94uLkm1RVFcPGY1qB7FRtL0FYLtTsJr4_c5vNGjKJPfgjkXVLxx9oCwMUVzKDbTrIE0sjDKTKzb-Hz6pI_JpwDHuECz-0coemMuGgfsp13O2WOb6To9oCKQCyYNt5QHN2GHyHoyRMDNzJxcKiCYmVEXan2_GSaQ"}}, "protected": "eyJub25jZSI6ICJOeC1sYjVfS2FaN1RGcWRkR0pWclVDNktmUlN3UEV6TmRkSjNTbkdUVktBIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJ3d3cuc3RhdHVzLmVpZG9sb25ob3N0LmNvbSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "DoWhseJJ5ILm9cAT10S8HWMb0JjoPwZCZx8IsG8_EP9VLy3BJzALZpXnP9s933LzWto3_lLCXf0q-0kjfI4dJe_gB9QWke8GGXnL1nTpL6sS1-6oeO9yuVAVsKK2ZadjSmzcv9NF_ZN46t1bRsdydfeq8EZ3YPBgeGGVpkgIzko2kuUpD0gXI2Zsch-tce3OgMpdh4usGJOI6lo48PUPYY10mI1jMlGOt8uyFzGt4VuFrDm67AR4H3InuIZiXSLl2mSzmz_puYmCLTThZhz2bZ-4bwRw7Ym_XJ4f83Su05aDygLnSJ2hvL3As72seekLzj6i9U6lsypfZnTXHxx51A"}'}
2015-11-25 02:59:10,732:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-11-25 02:59:10,824:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 403 101
2015-11-25 02:59:10,827:DEBUG:root:Received <Response [403]>. Headers: {'Content-Length': '101', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '1cAHEfy36ww1bUq81PjT9AHPjsvcv-e1uYMOvd8XVxw'}. Content: '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-25 02:59:10,828:DEBUG:acme.client:Storing nonce: '\xd5\xc0\x07\x11\xfc\xb7\xeb\x0c5mJ\xbc\xd4\xf8\xd3\xf4\x01\xcf\x8e\xcb\xdc\xbf\xe7\xb5\xb9\x83\x0e\xbd\xdf\x17W\x1c'
2015-11-25 02:59:10,828:DEBUG:acme.client:Received response <Response [403]> (headers: {'Content-Length': '101', 'Expires': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 25 Nov 2015 02:59:10 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '1cAHEfy36ww1bUq81PjT9AHPjsvcv-e1uYMOvd8XVxw'}): '{"type":"urn:acme:error:unauthorized","detail":"Error creating new authz :: Name is not whitelisted"}'
2015-11-25 02:59:10,829:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1206, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 460, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 325, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 628, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 544, in _check_response
    raise messages.Error.from_json(jobj)
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Name is not whitelisted
```

**Comment by pde** [comment]
"Name is not whitelisted" -- you're trying to issue a cert for a domain name that isn't in the private beta program.

**Comment by pde** [comment]
Arbitrary domains will be supported without whitelisting from the 3rd of December.

**Comment by KeiroD** [comment]
Except it is... at least, as per LE e-mail.

```
Helpful Information

Let's Encrypt maintainence events are posted on https://letsencrypt.status.io/ and Twitter (@letsencrypt_ops). If you need help, both the Let's Encrypt community at https://community.letsencrypt.org/ and #letsencrypt on irc.freenode.org are excellent sources of assistance.

If there are updates for Beta program participants, they will be posted at the community site at https://community.letsencrypt.org/t/beta-program-announcements/1631.

Your whitelisted domains are:

wolf.furryavalon.net
daedalus.eidolonhost.com
heimkoma.com
eidolonhost.com
www.furryavalon.net
www.eidolonhost.com
www.heimkoma.com
furryavalon.net
irc.furryavalon.net
These are the domains approved out of those you submitted. If you're missing domains, likely they weren't in your original submission, or they may have had a typo. If you like, you can re-submit to the beta program and you'll receive another notification when they, too, are whitelisted.
```
Is there a reason for LE to be incorrectly detecting the domain as not whitelisted?

**Comment by bmw** [comment]
Responding to the superfluous comment to hopefully help you solve your problem. I see this in the log above:
```
domains: ['eidolonhost.com', 'www.status.eidolonhost.com', 'heimkoma.com', 'status.eidolonhost.com', 'www.heimkoma.com']
```
The only names that are whitelisted are the fully qualified domain names that are included in your beta invite. If for example, you'd like a cert for `status.eidolonhost.com`, you'd need to fill out another beta participation request or wait until public beta on December 3rd.
