### ISSUE TITLE
Apache ports.conf parsing too strict for Listen 443

### ISSUE THREAD

**Issue by Maescool** [letsencrypt/letsencrypt#1699]
In my configuration, I only have certain IP's bound to the 443
so it could be `Listen 10.1.1.1:443` (given private IP as an example, IRL it's a public one)
it seems to only look for `Listen 443`
cause other the other IP's bound to this machine are used by different services.
Snippits of log:
````
2015-12-03 22:40:32,796:DEBUG:letsencrypt_apache.configurator:No Listen 443 directive found. Setting the Apache Server to Listen on port 443
2015-12-03 22:40:33,178:DEBUG:letsencrypt.reverter:Creating backup of /etc/apache2/ports.conf
2015-12-03 22:40:33,178:DEBUG:letsencrypt.reverter:Creating backup of /etc/apache2/apache2.conf
2015-12-03 22:40:33,289:ERROR:letsencrypt.le_util:Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 2 of /etc/apache2/le_tls_sni_01_cert_challenge.conf:
The address or port is invalid

2015-12-03 22:40:33,295:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1289, in perform
    self.restart()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1199, in restart
    self.config_test()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1222, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 2 of /etc/apache2/le_tls_sni_01_cert_challenge.conf:
The address or port is invalid
2015-12-03 22:40:33,296:DEBUG:letsencrypt.error_handler:Calling registered functions
2015-12-03 22:40:33,296:INFO:letsencrypt.auth_handler:Cleaning up challenges
2015-12-03 22:40:33,567:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 470, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 336, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1289, in perform
    self.restart()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1199, in restart
    self.config_test()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1222, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 2 of /etc/apache2/le_tls_sni_01_cert_challenge.conf:
The address or port is invalid

````

**Comment by pde** [comment]
Thanks for the report @Maescool.  Would you be comfortable posting your conf files here?

**Comment by Maescool** [comment]
Here you go, did however redact the ip's
ip's themselves are fine
````
# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen ipv4ip:80
Listen [ipv6ip]:80

<IfModule ssl_module>
	Listen ipv4ip:443
	Listen [ipv6ip]:443
</IfModule>

<IfModule mod_gnutls.c>
	Listen ipv4ip:443
	Listen [ipv6ip]:443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
````

**Comment by Maescool** [comment]
The `The address or port is invalid` errors are probably related to #1143

**Comment by watercrossing** [comment]
I think this is closed by #1831 and #2093.

**Comment by pde** [comment]
My attempts to reproduce this have thus far failed; when I try to concretize @Maescool 's example, I see apache restart without complaint, but not actually bind to any ports.  So that's prevented me from confirming this is closed, or adding a test to `letsencrypt-apache/letsencrypt_apache/tests/apache-conf-files/`

The conf file I've tried is here:

```
Listen 10.21.171.130:80
Listen [fe80::7e7a:91ff:fe5e:dedb]:80

<IfModule ssl_module>
    Listen 10.21.171.130:443
    Listen [fe80::7e7a:91ff:fe5e:dedb]:443
</IfModule>

<IfModule mod_gnutls.c>
    Listen 10.21.171.130:443
    Listen [fe80::7e7a:91ff:fe5e:dedb]:443
</IfModule>

<VirtualHost 10.21.171.130 fe80::7e7a:91ff:fe5e:dedb>
	ServerAdmin webmaster@localhost
        ServerName dee.isnot.org

	DocumentRoot /var/www/tweedle
	<Directory />
		Options FollowSymLinks
		AllowOverride None
	</Directory>
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>

	ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
	<Directory "/usr/lib/cgi-bin">
		AllowOverride None
		Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
		Order allow,deny
		Allow from all
	</Directory>
	

	ErrorLog ${APACHE_LOG_DIR}/error.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by pde** [comment]
Closing in any case.
