### ISSUE TITLE
Mixed case indentifiers cause UnexpectedUpdate error due to lack of normalization

### ISSUE THREAD

**Issue by ajwhite** [letsencrypt/letsencrypt#1712]
I've received the following stack trace after selecting the domain I want to add a cert for with `./letsencrypt-auto`. I've redacted parts of the log below. I'm doing this on a Digital Ocean Ubuntu 14.04x64 box with Apache2. DNS is hosted on CloudFlare.

```
2015-12-04 04:29:57,939:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-04 04:29:58,085:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 572
2015-12-04 04:29:58,088:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '572', 'Expires': 'Fri, 04 Dec 2015 04:29:58 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/XXXXXXXXXXXXXXXXXX', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Dec 2015 04:29:58 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'XXXXXXXXXXXXXXXXXX'}. Content: '{"identifier":{"type":"dns","value":"name.XXXXXXXXXXXXXXXXXX.com"},"status":"pending","expires":"XXXXXXXXXXXXXXXXXX","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX","token":"XXXXXXXXXXXXXXXXXX"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX","token":"XXXXXXXXXXXXXXXXXX"}],"combinations":[[1],[0]]}'
2015-12-04 04:29:58,089:DEBUG:acme.client:Storing nonce: 'XXXXXXXXXXXXXXXXXX'
2015-12-04 04:29:58,089:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '572', 'Expires': 'Fri, 04 Dec 2015 04:29:58 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/XXXXXXXXXXXXXXXXXX', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 04 Dec 2015 04:29:58 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'XXXXXXXXXXXXXXXXXX'}): '{"identifier":{"type":"dns","value":"name.XXXXXXXXXXXXXXXXXX.com"},"status":"pending","expires":"XXXXXXXXXXXXXXXXXX","challenges":[{"type":"tls-sni-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX","token":"XXXXXXXXXXXXXXXXXX"},{"type":"http-01","status":"pending","uri":"https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX","token":"XXXXXXXXXXXXXXXXXX"}],"combinations":[[1],[0]]}'
2015-12-04 04:29:58,091:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/aw/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 470, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 336, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 198, in request_challenges
    return self._authzr_from_response(response, identifier)
  File "/home/aw/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 179, in _authzr_from_response
    raise errors.UnexpectedUpdate(authzr)
UnexpectedUpdate: AuthorizationResource(body=Authorization(status=Status(pending), challenges=(ChallengeBody(chall=TLSSNI01(token='XXXXXXXXXXXXXXXXXX'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX', error=None), ChallengeBody(chall=HTTP01(token='XXXXXXXXXXXXXXXXXX'), status=Status(pending), validated=None, uri=u'https://acme-v01.api.letsencrypt.org/acme/challenge/XXXXXXXXXXXXXXXXXX', error=None)), identifier=Identifier(typ=IdentifierType(dns), value=u'name.XXXXXXXXXXXXXXXXXX.com'), expires=datetime.datetime(2015, 12, 11, 4, 29, 58, 22474, tzinfo=<UTC>), combinations=((1,), (0,))), new_cert_uri='https://acme-v01.api.letsencrypt.org/acme/new-cert', uri='https://acme-v01.api.letsencrypt.org/acme/authz/XXXXXXXXXXXXXXXXXX')
```

**Comment by jespertheend** [comment]
Same problem here

**Comment by jespertheend** [comment]
I fixed this problem by modifying the client.py file in `/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py` ([link](https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/client.py))
I commented out these two lines:

    if authzr.body.identifier != identifier:
        raise errors.UnexpectedUpdate(authzr)

in the `_authzr_from_response` method.

Probably not the best solution but at least it works.

**Comment by kuba** [comment]
By blinding (`xxxx`) all the data you make it nearly impossible to debug the problem, I'm afraid.  There should not be any secret material (in terms of cryptography) in the logs, but if you still don't want to disclose this data publicly, maybe you can send it to me in a private message (maybe IRC?)?

**Comment by jespertheend** [comment]
Here's my log:
[letsencrypt.log.5](https://github.com/letsencrypt/letsencrypt/files/67634/letsencrypt.log.5.txt)

**Comment by kuba** [comment]
Thanks for the output!

It seems that you used `ZeGame.jespertheend.com` and Boulder returns an authorization with normalized domain name `zegame.jespertheend.com`. `acme.client.Client._authzr_from_response` does unicode comparison without such normalization and so it fails.

Quickfix: use lowercase letters everywhere.

Long term fix: I don't know yet. @jsha, could you advise if we should also normalize identifiers on the client side or should Boulder have it fixed?

**Comment by jsha** [comment]
I would recommend having the client downcase identifiers.

**Comment by schoen** [comment]
I forgot what the PR was, but I'm pretty sure that the client now does downcase identifiers in `enforce_domain_sanity()`. I just tried issuing for a domain ending in `.ORG` and it worked just fine. I'm going to close this for now but I think we should double-check the renewal behavior in #2191 (just to make sure that the client successfully renews the existing lineage in that case rather than spuriously making a new lineage).

**Comment by ajwhite** [comment]
Thanks for the update @schoen - i'll aim to give this another try next time I'm working on any certs
