### ISSUE TITLE
webroot without root broken

### ISSUE THREAD

**Issue by jeremiejig** [letsencrypt/letsencrypt#1747]
Hello,

I'm using letsencrypt with a letsencrypt user.
For validation I created a directory /var/www/letsencrypt
It was working fine with the version of lets encrypt of the 1 december.

But now I get this error: 

```shell
2015-12-04 16:46:26,091:DEBUG:letsencrypt.plugins.webroot:Attempting to save validation to /var/www/letsencrypt/.well-known/acme-challenge/I-MSp***_ODo0
2015-12-04 16:46:26,092:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 83, in perform
    return [self._perform_single(achall) for achall in achalls]
  File "/home/paul/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 109, in _perform_single
    os.chown(path, stat_parent_path.st_uid, stat_parent_path.st_gid)
OSError: [Errno 1] Operation not permitted: '/var/www/letsencrypt/.well-known/acme-challenge/IMSp***_ODo0'
```

I hope to see something like an option to activate or deactivate the chown behaviour, or some smart detection of wether to use chown.
Maybe add a warning when running without sudo about some webserver enforcing strict user ownership.

Best Regards

**Comment by jeremiejig** [comment]
After reading how chown is called, I simply change ownership of the folder /var/www/letsencrypt to letsencrypt (previoulsy owned by root).
