### ISSUE TITLE
Unable to import libaugeas

### ISSUE THREAD

**Issue by milandamen** [letsencrypt/letsencrypt#1770]
When I run `./letsencrypt-auto` I get this output:

    Updating letsencrypt and virtual environment dependencies.......
    Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt
    An unexpected error occurred:
    ImportError: Unable to import libaugeas!
    Please see the logfile 'letsencrypt.log' for more details.

I got letsencrypt by `git clone https://github.com/letsencrypt/letsencrypt.git` into directory `/opt`.  
When I run `bootstrap/debian.sh` everything is the newest version.  
`apt-get install libaugeas0` and `apt-get install libffi-dev` also tells me everything is the newest version. 

I'm running ReadyNAS OS 6.4.1 which is some kind of Debian. I run every command as root.  
`apt-get install letsencrypt` returns `Unable to locate package letsencrypt`

letsencrypt.log:

    Traceback (most recent call last):
      File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
        sys.exit(main())
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1236, in main
        plugins = plugins_disco.PluginsRegistry.find_all()
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 168, in find_all
        plugin_ep = PluginEntryPoint(entry_point)
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 31, in __init__
        self.plugin_cls = entry_point.load()
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
        return self.resolve()
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 22, in <module>
        from letsencrypt_apache import augeas_configurator
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt_apache/augeas_configurator.py", line 4, in <module>
        import augeas
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/augeas.py", line 78, in <module>
        class Augeas(object):
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/augeas.py", line 82, in Augeas
        _libaugeas = _dlopen("augeas")
      File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/augeas.py", line 75, in _dlopen
        raise ImportError("Unable to import lib%s!" % args[0])
    ImportError: Unable to import libaugeas!

**Comment by pde** [comment]
If you do `apt-get install python-augeas` and then run `python` and type `import augeas`, does it work?

**Comment by milandamen** [comment]
@pde `apt-get install python-augeas` installed version 0.4.0-2.1 from `http://mirrors.kernel.org/debian/ wheezy/main`.

Running `import augeas` in `python` and also in a seperate .py file gives this:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/augeas.py", line 55, in <module>
        class Augeas(object):
      File "/usr/lib/python2.7/dist-packages/augeas.py", line 65, in Augeas
        _libaugeas = _dlopen("augeas")
      File "/usr/lib/python2.7/dist-packages/augeas.py", line 52, in _dlopen
        raise ImportError("Unable to import lib%s!" % args[0])
    ImportError: Unable to import libaugeas!

**Comment by johman10** [comment]
I'm also having this problem on a ReadyNas with OS 6.4.1.

**Comment by Rudloff** [comment]
It seems to work if you install libaugeas-dev.

**Comment by milandamen** [comment]
@Rudloff Thank you, it fully works now.

**Comment by marietta-tech** [comment]
/letsencrypt/lib/python2.7/site-packages/augeas.py", line 75, in _dlopen
    raise ImportError("Unable to import lib%s!" % args[0])
ImportError: Unable to import libaugeas!

Same issue OSX 10.11.1

**Comment by sunny-g** [comment]
I needed to run `brew install augeas` to get this to work when installing `letsencrypt` as a part of `boulder`'s integration tests - is this dependency documented anywhere?

**Comment by piribes** [comment]
on centos 7 you need to run "yum install python-augers"

**Comment by petamem** [comment]
under gentoo, you need to install

emerge app-admin/augeas dev-python/python-augeas

I wouldn't be so sure if one should close issues like this so easily. Good programming practice - IMHO - would be to check the prerequisites beforehand and give hints to the user what to do in case something was missing.
