### ISSUE TITLE
Making cron to generate the cert is failing

### ISSUE THREAD

**Issue by anthonykozak** [letsencrypt/letsencrypt#1790]
Hello !
Running this line on cron : 
    letsencrypt-auto certonly --webroot -d domain.fr -w /home/domain

is getting this error : 
```
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --webroot -d domain.fr -w /home/domain
An unexpected error occurred:
PythonDialogBug
 Please see the logfiles in /var/log/letsencrypt for more details.
```

And here is the log :
```
2015-12-06 14:14:37,885:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 512, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 318, in _auth_from_domains
    lineage = _treat_as_renewal(config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 256, in _treat_as_renewal
    interfaces.IDisplay).yesno(question, "Replace", "Cancel"):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/display/util.py", line 140, in yesno
    yes_label=yes_label, no_label=no_label)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 3749, in yesno
    kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
PythonDialogBug
```
any idea why ?
thank you so much !
regards,
Anthony

**Comment by anthonykozak** [comment]
ok I found a working example here
https://community.centminmod.com/threads/letsencrypt-free-ssl-certificates-with-web-root-authentication-method.4635/#post-20800
