### ISSUE TITLE
webroot_map does not extract domains from CSR files

### ISSUE THREAD

**Issue by DeHackEd** [letsencrypt/letsencrypt#1802]
Environment: CentOS 7 in a virtualenv with all components installed via pip.
<pre>
$ git describe
v0.1.0-32-gce0ea2b
$ letsencrypt -v -v -v --text --webroot --config-dir /home/sslcerts/letsencrypt-data/etc --work-dir /home/sslcerts/letsencrypt-data/varlib --logs-dir /home/sslcerts/letsencrypt-data/varlog --webroot-path /home/sslcerts/public_html/ --csr domain.net.req_der --register-unsafely-without-email --webroot-path /home/sslcerts/public_html/ certonly 
2015-12-06 20:31:42,545:DEBUG:letsencrypt.cli:Root logging level set at 0
2015-12-06 20:31:42,546:INFO:letsencrypt.cli:Saving debug log to /home/sslcerts/letsencrypt-data/varlog/letsencrypt.log
2015-12-06 20:31:42,546:DEBUG:letsencrypt.cli:letsencrypt version: 0.2.0.dev0
2015-12-06 20:31:42,546:DEBUG:letsencrypt.cli:Arguments: ['-v', '-v', '-v', '--text', '--webroot', '--config-dir', '/home/sslcerts/letsencrypt-data/etc', '--work-dir', '/home/sslcerts/letsencrypt-data/varlib', '--logs-dir', '/home/sslcerts/letsencrypt-data/varlog', '--webroot-path', '/home/sslcerts/public_html/', '--csr', 'domain.net.req_der', '--register-unsafely-without-email', '--webroot-path', '/home/sslcerts/public_html/']
2015-12-06 20:31:42,547:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-12-06 20:31:42,548:WARNING:letsencrypt.cli:Root (sudo) is required to run most of letsencrypt functionality.
2015-12-06 20:31:42,548:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2015-12-06 20:31:42,551:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/home/sslcerts/virutalenv/lib/python2.7/site-packages/letsencrypt-0.2.0.dev0-py2.7.egg/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/home/sslcerts/virutalenv/lib/python2.7/site-packages/letsencrypt-0.2.0.dev0-py2.7.egg/letsencrypt/plugins/webroot.py", line 54, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2015-12-06 20:31:42,552:DEBUG:letsencrypt.display.ops:No candidate plugin
2015-12-06 20:31:42,552:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
The webroot plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('--webroot-path must be set',)
$
</pre>

When using a client-generated key and csr (replace `--csr  filename` with `-d domain.net`) it does work successfully.

Yes I specified webroot-path twice. I was trying a few basic troubleshooting ideas

**Comment by kuba** [comment]
I can see that `--webroot-path` was specified on the CLI, so this is clearly a bug.

**Comment by osirisinferi** [comment]
Could it have something to do with this code, which does some checks between the -w and the -d options?

https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L1090

And as -d and --csr are mutually exclusive: https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L489

Perhaps the --webroot-path variable isn't passed on to the webroot plugin?

**Comment by Hawk777** [comment]
The problem AFAICT is that the webroot map is what actually matters to the rest of the code; webroot path is just a shortcut way to configure a value for webroot map if no other value is provided for the domain. Until the bug is fixed, specifying a webroot map in cli.ini (or, presumably, on the command line) explicitly instead of using webroot path option makes CSRs work properly, though of course it’s rather annoying to have to list out your domains twice (once in your CSR generator and once in cli.ini).

**Comment by osirisinferi** [comment]
> though of course it’s rather annoying to have to list out your domains twice (once in your CSR generator and once in cli.ini).

Well, when using the webroot authenticator, the LE script should have a clue where it can find the specific webroots. So it's only logical that some form of webroot-map has to be given, as this information is obviously missing from the CSR :stuck_out_tongue_closed_eyes: 

So I think the best option is to remove the incompatibility between --csr and -d, but check if the CN and SANs from the CSR were properly entered by all -d's and make sure no extra -d's were entered which weren't in the CSR.

Another option is adding an extra check for --csr and check for --webroot-path and give the user the hint to use --webroot-map?

**Comment by DeHackEd** [comment]
In this case I was generating a pair of certs for domains which point to the same target. One webroot was applicable to both domains I was interested in.

**Comment by Hawk777** [comment]
I could see this being the case for e.g. domain.tld and www.domain.tld, which would very commonly share a webroot.

In my case, I just don’t want Let’s Encrypt mucking around in my real webroots, so I created a separate webroot just for LE and used an alias rule to map it into the appropriate location in all my domains.

Really, the question is pretty simple: if I’m allowed to use -w -d -d -d to specify a single webroot for three domains, why aren’t I allowed to use -w --csr to specify a single webroot for three domains? There are legitimate reasons for doing this, and AFAICT no reason to forbid it.

**Comment by pde** [comment]
Because `--csr` only works in certonly mode at the moment, one solution strategy would be `if args.webroot_path: <add webroot map entries iff they're missing>` in [this location](https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/cli.py#L590).  Send us a pull request!

**Comment by module0x90** [comment]
This works with

/opt/letsencrypt/letsencrypt-auto --renew certonly --server https://acme-v01.api.letsencrypt.org/directory --csr domain.csr -a webroot --webroot-map '{"domain.tld" : "/tmp"}'

Commit 0c704fa7f27277c838e13deed85e5c1ecbe46e90

**Comment by karolyi** [comment]
+1

**Comment by pde** [comment]
Done in 0.4.0.
