### ISSUE TITLE
ImportError: cannot import name NewConnectionError

### ISSUE THREAD

**Issue by thehowl** [letsencrypt/letsencrypt#1806]
I have installed the letsencrypt client through the package on Arch Linux's official repositories. When I try to run the client, I get the following:

```
howl@zxq.co:~$ letsencrypt
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0', 'console_scripts', 'letsencrypt')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 521, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2632, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2312, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2318, in resolve
  File "/usr/lib/python2.7/site-packages/letsencrypt/cli.py", line 26, in <module>
    from letsencrypt import account
  File "/usr/lib/python2.7/site-packages/letsencrypt/account.py", line 15, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .api import request, get, head, post, patch, put, delete, options
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 14, in <module>
    from . import sessions
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 27, in <module>
    from .adapters import HTTPAdapter
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 27, in <module>
    from .packages.urllib3.exceptions import NewConnectionError
ImportError: cannot import name NewConnectionError
```

Info:

```
howl@zxq.co:~$ pip2.7 --version
pip 7.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
howl@zxq.co:~$ python2.7 --version
Python 2.7.10
```

**Comment by gws** [comment]
@thehowl Does this help? https://bugs.archlinux.org/task/47255

**Comment by thehowl** [comment]
Yep. Removing requests from both pip and pacman, then adding it with pip fixed it.
