### ISSUE TITLE
Domain with german umlauts ('ascii' codec can't encode character)

### ISSUE THREAD

**Issue by lulabad** [letsencrypt/letsencrypt#1836]
CentOS 7.1.1503

I tried to create an certificat with domain contains german umlauts. Domain is: entä.de
I getting in the console this error:
````
An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 3: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.
````

Logfile:
````python
2015-12-08 17:58:44,353:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 511, in obtain_cert
    domains = _find_domains(args, installer)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 106, in _find_domains
    domains = display_ops.choose_names(installer)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/display/ops.py", line 187, in choose_names
    return _choose_names_manually()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/display/ops.py", line 235, in _choose_names_manually
    return display_util.separate_list_input(input_)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/display/util.py", line 419, in separate_list_input
    return [str(string) for string in no_commas.split()]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 3: ordinal not in range(128)
````

Is there a way to fix this?

**Comment by kuba** [comment]
Displaying this error message is a bug. Nevertheless I don't think you can use IDN

**Comment by joohoi** [comment]
Yeah, IDNs are not currently supported. I just did work on the domain validation, and can use the same checks here. Fixing this in a minute.
