### ISSUE TITLE
Versioned dependency on PyOpenSSL interferes with packaging

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#1861]
Currently acme depends on PyOpenSSL >= 0.15.  The comment in setup.py says this is for `X509req.get_extensions()`, but the only place where that's called appears to be [wrapped in a fallback](https://github.com/letsencrypt/letsencrypt/blob/master/acme/acme/crypto_util.py#L171).

If we can relax this version dependency, that will greatly assist packaging for RHEL 6/7 and Debian 7.

**Comment by pde** [comment]
I tried testing this on a Debian squeeze system (I couldn't get PyOpenSSL==0.13 to pip install on newer systems):

`sudo venv/bin/letsencrypt --webroot -w /var/www/tweedle/ -d tweedle.isnot.org -w /var/www/dee -d dee.isnot.org certonly -t -vv --debug`

I see this error:
```
Traceback (most recent call last):
  File "venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt', 'console_scripts', 'letsencrypt')()
  File "/home/admin/letsencrypt/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/home/admin/letsencrypt/letsencrypt/cli.py", line 512, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/home/admin/letsencrypt/letsencrypt/cli.py", line 336, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/home/admin/letsencrypt/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/admin/letsencrypt/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/admin/letsencrypt/letsencrypt/client.py", line 228, in _obtain_certificate
    authzr)
  File "/home/admin/letsencrypt/acme/acme/client.py", line 310, in request_issuance
    headers={'Accept': content_type})
  File "/home/admin/letsencrypt/acme/acme/client.py", line 631, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/home/admin/letsencrypt/acme/acme/client.py", line 508, in _wrap_in_jws
    jobj = obj.json_dumps().encode()
  File "/home/admin/letsencrypt/acme/acme/jose/interfaces.py", line 189, in json_dumps
    return json.dumps(self, default=self.json_dump_default, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 263, in iterencode
    return _iterencode(o, 0)
  File "/home/admin/letsencrypt/acme/acme/jose/interfaces.py", line 214, in json_dump_default
    return python_object.to_partial_json()
  File "/home/admin/letsencrypt/acme/acme/jose/json_util.py", line 263, in to_partial_json
    return self.fields_to_partial_json()
  File "/home/admin/letsencrypt/acme/acme/jose/json_util.py", line 251, in fields_to_partial_json
    jobj[field.json_name] = field.encode(value)
  File "/home/admin/letsencrypt/acme/acme/jose/json_util.py", line 96, in encode
    return self.fenc(value)
  File "/home/admin/letsencrypt/acme/acme/jose/json_util.py", line 401, in encode_csr
    OpenSSL.crypto.FILETYPE_ASN1, csr))
TypeError: must be X509Req, not ComparableX509
```

**Comment by pde** [comment]
PyOpenSSL 0.14 works though.

**Comment by pde** [comment]
Fixing this completely (>= 0.13) will be work, so moving it to the 0.2.0 milestone.  For now, we will live with (>= 0.14).

**Comment by rbu** [comment]
For RHEL6 and 7, we'll need compatibility with 0.13.1 unfortunately. Here's a test run on RHEL 7: https://paste.fedoraproject.org/299758/

Just for reference, for EPEL7, we're discussing this in https://bugzilla.redhat.com/show_bug.cgi?id=1288743 . pyOpenSSL is the only real blocker, all other package dependencies were easily resolved.

**Comment by NoodlesNZ** [comment]
+1

**Comment by kuba** [comment]
It's not a fallback. These are two separate branches for 2 different code paths, one for certs, one for CSRs.
