### ISSUE TITLE
webroot plugin unexpected error

### ISSUE THREAD

**Issue by pragmar** [letsencrypt/letsencrypt#1995]
The initial run of webroot/certonly went off without a hitch, but subsequent runs are encountering an error. The first run created 3 symlinks, *privkey.pem, chain.pem, and cert.pem*. Running the script again fails after looking for a missing *fullchain.pem* symlink. I''ve only been working with LE for a few hours, so I may be overlooking something obvious--but given it's a hard exception it doesn't seem right. I'm using master branch as of 2015-12-22.

##### command and output

    /user/letsencrypt/letsencrypt-auto certonly --webroot --renew-by-default -w /var/www/vhosts/example.com/etc/letsencrypt -d example.com -d www.example.com
    
    Updating letsencrypt and virtual environment dependencies.......
    Running with virtualenv: /user/.local/share/letsencrypt/bin/letsencrypt certonly --webroot --renew-by-default -w /var/www/vhosts/example.com/etc/letsencrypt -d example.com -d www.example.com
    An unexpected error occurred:
    AttributeError: 'NoneType' object has no attribute 'rfind'
    Please see the logfiles in /var/log/letsencrypt for more details.

##### log

    2015-12-23 05:15:25,287:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0x7f5ac66aac90> and installer None
    2015-12-23 05:15:25,308:DEBUG:letsencrypt.cli:Picked account: <Account(5aec10617f8de2455e3341784a12f567)>
    2015-12-23 05:15:25,310:DEBUG:user:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
    2015-12-23 05:15:25,316:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
    2015-12-23 05:15:26,283:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
    2015-12-23 05:15:26,287:DEBUG:user:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Wed, 23 Dec 2015 05:15:26 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 23 Dec 2015 05:15:26 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'ZqDHQaA4dgJ2L7bkcfhLewwvYlIptZjhibnBkkDBTHw'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
    2015-12-23 05:15:26,288:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Wed, 23 Dec 2015 05:15:26 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 23 Dec 2015 05:15:26 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'ZqDHQaA4dgJ2L7bkcfhLewwvYlIptZjhibnBkkDBTHw'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
    2015-12-23 05:15:26,292:DEBUG:letsencrypt.storage:Expected symlink /etc/letsencrypt/live/example.com/fullchain.pem for fullchain does not exist.
    2015-12-23 05:15:26,293:DEBUG:letsencrypt.cli:Exiting abnormally:
    Traceback (most recent call last):
      File "/user/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
        sys.exit(main())
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
        return args.func(args, config, plugins)
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in obtain_cert
        _auth_from_domains(le_client, config, domains)
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 379, in _auth_from_domains
        action, lineage = _treat_as_renewal(config, domains)
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 242, in _treat_as_renewal
        return _handle_identical_cert_request(config, ident_names_cert)
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 258, in _handle_identical_cert_request
        if cert.should_autorenew(interactive=True):
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 560, in should_autorenew
        if self.ocsp_revoked(self.latest_common_version()):
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 371, in latest_common_version
        versions = [self.available_versions(x) for x in ALL_FOUR]
      File "/user/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 341, in available_versions
        where = os.path.dirname(self.current_target(kind))
      File "/user/.local/share/letsencrypt/lib/python2.7/posixpath.py", line 129, in dirname
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'

##### symlinks context from first run

    user@localhost:/etc/letsencrypt/live/example.com# ls -ltr
    total 0
    lrwxrwxrwx 1 user user 38 Dec 23 04:12 privkey.pem -> ../../archive/example.com/privkey1.pem
    lrwxrwxrwx 1 user user 36 Dec 23 04:12 chain.pem -> ../../archive/example.com/chain1.pem
    lrwxrwxrwx 1 user user 35 Dec 23 04:12 cert.pem -> ../../archive/example.com/cert1.pem

**Comment by bmw** [comment]
`fullchain.pem` should have also been created on the first run. Can you try one of the following:

* Move `/etc/letsencrypt` to another location, at least temporarily and rerun the client.
* Run the client specifying `--config-dir` on the command line with a path to a directory other than `/etc/letsencrypt`.

Please let me know if you can reproduce this problem.

**Comment by pragmar** [comment]
I've moved /etc/letsencrypt to /etc/letsencrypt.old and ran it. This time I received a fullchain.pem symlink. Everything is running smoothly, including a second run:

    ls -l /etc/letsencrypt/live/example.com/
    total 0
    lrwxrwxrwx 1 user user 35 Dec 23 17:30 cert.pem -> ../../archive/example.com/cert2.pem
    lrwxrwxrwx 1 user user 36 Dec 23 17:30 chain.pem -> ../../archive/example.com/chain2.pem
    lrwxrwxrwx 1 user user 40 Dec 23 17:30 fullchain.pem -> ../../archive/example.com/fullchain2.pem
    lrwxrwxrwx 1 user user 38 Dec 23 17:30 privkey.pem -> ../../archive/example.com/privkey2.pem

Thanks for the help, I wish I knew what I may have done differently before, but I'm not certain. There were a few false starts while I was getting the command arguments right the first time around. If there's any additional information I can provide, just let me know, but I think this may be a case of user error.

**Comment by bmw** [comment]
Thanks for taking the time to follow up on this @pragmar. My guess is `letsencrypt` somehow got interrupted between writing `chain.pem` and `fullchain.pem` on your first run. Glad it's fixed for you!
