### ISSUE TITLE
Cannot write to letsencrypt.log

### ISSUE THREAD

**Issue by cowlicks** [letsencrypt/letsencrypt#2016]
When I go through the notes for [running local copy of client](https://letsencrypt.readthedocs.org/en/latest/contributing.html#running-a-local-copy-of-the-client). When I get to the step where I run `letsencrypt`, I get

```
(venv)➜  letsencrypt git:(master) ✗ letsencrypt
An unexpected error occurred:
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
Please see the logfile 'letsencrypt.log' for more details.
```
The log file says
```
Traceback (most recent call last):
  File "/home/blake/github/letsencrypt/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt', 'console_scripts', 'letsencrypt')()
  File "/home/blake/github/letsencrypt/letsencrypt/cli.py", line 1366, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/home/blake/github/letsencrypt/letsencrypt/cli.py", line 1279, in setup_logging
    args, logfile=logfile, fmt=fmt)
  File "/home/blake/github/letsencrypt/letsencrypt/cli.py", line 1250, in setup_log_file_handler
    log_file_path, maxBytes=2 ** 20, backupCount=10)
  File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 905, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 935, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/letsencrypt/letsencrypt.log'
```

I is this log file supposed to be created during the setup and installation? I could not find where this is supposed to happen.

Or am I supposed to set this up myself, and this is just not mentioned in the documentation? If so I can add that.

**Comment by pde** [comment]
If you're root, it will be set up automatically.  If you want to run as non-root, create /var/log/letsencrypt so that your nonroot user can write to it, or pass in --logs-dir for some other directory.  You may encounter similar issues with /etc/letsencrypt and /var/lib/letsencrypt.

**Comment by cowlicks** [comment]
Thanks @pde, sorry for the noise. I just wanted to record the issue for posterity.
