### ISSUE TITLE
Windows: AttributeError: 'module' object has no attribute 'geteuid'

### ISSUE THREAD

**Issue by stopspazzing** [letsencrypt/letsencrypt#2046]
Windows 10 64bit
Python 2.7.11
Used pypi to install letsencrypt:
Running the created exe produces the follow error:
```
Traceback (most recent call last):
  File "d:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\letsencrypt.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "d:\python27\lib\site-packages\letsencrypt\cli.py", line 1358, in main
    directory, constants.CONFIG_DIRS_MODE, os.geteuid(),
AttributeError: 'module' object has no attribute 'geteuid'
```

Seems no geteuid in windows.

**Comment by stopspazzing** [comment]
Fixed it, by checking for windows, and if it is, use the current user: https://gist.github.com/stopspazzing/d57732ab97ada2abece2

but have new issue:
```python
Traceback (most recent call last):
  File "d:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "d:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Python27\Scripts\letsencrypt.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "d:\python27\lib\site-packages\letsencrypt\cli.py", line 1369, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "d:\python27\lib\site-packages\letsencrypt\cli.py", line 1279, in setup_logging
    cli_handler = cli_handler_factory(args, level, fmt)
  File "d:\python27\lib\site-packages\letsencrypt\cli.py", line 1266, in _cli_log_handler
    handler = log.DialogHandler()
  File "d:\python27\lib\site-packages\letsencrypt\log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "d:\python27\lib\site-packages\dialog.py", line 1013, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "d:\python27\lib\site-packages\dialog.py", line 477, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound
```

**Comment by xgin** [comment]
Use `--text` option - it does not require dialog.

I have an experimental polyfill for Windows: https://github.com/plesk/letsencrypt-plesk/blob/windows/letsencrypt_plesk/win32.py

**Comment by bmw** [comment]
Unfortunately, `letsencrypt` doesn't work on Windows yet. See our system requirements [here](https://github.com/letsencrypt/letsencrypt#system-requirements). You can also see discussions about a Windows client on our [mailing list](https://groups.google.com/a/letsencrypt.org/forum/#!forum/client-dev).
