### ISSUE TITLE
Renewal fails due to "Correct zName not found for TLS SNI challenge", but lists the correct URL.

### ISSUE THREAD

**Issue by NukaPunk** [letsencrypt/letsencrypt#2102]
I'm running `letsencrypt-auto certonly --standalone  -d app.website.com` (where `website` is my URL) and I'm getting the following error: `Failed authorization procedure. app.website.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found app.website.com`

As you can see it is in-fact finding the zName, but claims that it can't.  I also disabled all firewalls just to be sure nothing was blocking it, but I get the same error.

Here is the full log:

```
Updating letsencrypt and virtual environment dependencies.......
Running with virtualenv: sudo /home/app/.local/share/letsencrypt/bin/letsencrypt install -d app.website.com --logs-dir ./log

2016-01-06 17:58:09,188:DEBUG:letsencrypt.plugins.standalone:Stopping server at 0.0.0.0:443...
2016-01-06 17:58:09,311:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/app/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 389, in _auth_from_domains
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 84, in get_authorizations
    self._respond(cont_resp, dv_resp, best_effort)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 142, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 204, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. app.website.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found app.website.com

                                                                                                                                                                                          83,0-1        Bot
2016-01-06 17:58:09,188:DEBUG:letsencrypt.plugins.standalone:Stopping server at 0.0.0.0:443...
2016-01-06 17:58:09,311:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/home/app/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1396, in main
    return args.func(args, config, plugins)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 598, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 389, in _auth_from_domains
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 84, in get_authorizations
    self._respond(cont_resp, dv_resp, best_effort)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 142, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/home/app/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 204, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. app.website.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Correct zName not found for TLS SNI challenge. Found app.website.com
```

**Comment by kuba** [comment]
`zName` refers to `*.acme.invalid`. Your TLS SNI setup on the app.website.com web server must be broken, i.e. it doesn't serve the appropriate certificate.

I see that you're using `standalone` plugin, which means that you must take down your existing webserver. Do you actually run this command on the target server? If there is already running webserver, `standalone` plugin should raise an error because it would not be able to bind to port `443`...

**Comment by NukaPunk** [comment]
OK I'm not able to take down the existing NodeJS server which is bound to the port 443, so that must be the issue. I will look into using the webroot method instead. Thanks!
