### ISSUE TITLE
ImportError: No module named urllib3

### ISSUE THREAD

**Issue by edvinas91** [letsencrypt/letsencrypt#2108]
Hi,

I'm trying to run the auto script after cloning letsencrypt to a new folder and here's what happens (All commands are executed by root):

```
./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --help
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 26, in <module>
    from letsencrypt import account
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/account.py", line 15, in <module>
    from acme import messages
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

Verifying that python has urllib3 in both python2.* and 3.*:
```
python
Python 2.7.11 (default, Dec 15 2015, 16:46:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>>
```

```
python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib3
>>> 

```

Any suggestions/ideas are appreciated.

**Comment by pde** [comment]
The copy of python in your the virtual environment (`~/.local/share/letsencrypt/bin/python`) has its own copies of various libraries, including a copy of `requests`.  `requests` bundles its own internal copy of `urllib3`.  But yours is missing for some reason.

@kuba do you have any thoughts on this?

**Comment by pde** [comment]
@edvinas91 if you move `/root/.local/share/letsencrypt/` to another location (keep a copy around for debugging for now) and try again, does the problem re-occur?

**Comment by edvinas91** [comment]
@pde Awesome, moved ``/root/.local/share/letsencrypt/`` to ``/root/.local/share/letsencrypt_bk/`` and re-cloned letsencrypt, ran it again and.. it worked!

I believe the problem was because i updated local version of Python from 2.7.4 to 2.7.11 the first time I tried to run the auto script, because it was giving me ``InsecurePlatformWarning`` and some local files must have messed up because of that. 

Thanks!

**Comment by pixeline** [comment]
@edvinas91 @pde thank you, exact same path to error here. It all works fine now. LE is awesome.
