### ISSUE TITLE
Debian "Jessie" - ./letsencrypt-auto --apache = result: ExecutableNotFound

### ISSUE THREAD

**Issue by gree303** [letsencrypt/letsencrypt#2166]
Hi all;

I'm having some troubles executing letsencrypt. Used this tutorial: https://eblog.damia.net/2015/12/03/lets-encrypt-automation-on-debian/
System: Bunsenlabs / Debian "Jessie"
Maybe someone had the same "issue".

Terminal:
$ ./letsencrypt-auto --apache
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: sudo /home/xx/.local/share/letsencrypt/bin/letsencrypt --apache
An unexpected error occurred:
ExecutableNotFound
Please see the logfile 'letsencrypt.log' for more details.

letsencrypt.log:

Traceback (most recent call last):
  File "/home/xx/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1364, in main
    setup_logging(args, _cli_log_handler, logfile='letsencrypt.log')
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1278, in setup_logging
    cli_handler = cli_handler_factory(args, level, fmt)
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1265, in _cli_log_handler
    handler = log.DialogHandler()
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/log.py", line 29, in __init__
    self.d = dialog.Dialog() if d is None else d
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1013, in __init__
    self._dialog_prg = _path_to_executable(dialog)
  File "/home/xx/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 477, in _path_to_executable
    "can't find the executable for the dialog-like "
ExecutableNotFound

Any help is very much welcome.
Thanks.

**Comment by gree303** [comment]
... update: Downloaded Ubuntu Oracle VM. After downloading and running letsencrypt I'm getting a TLS verification error. Also tried to port forward 443 without success.

Any advice or ideas?
thx

**Comment by alex3137** [comment]
Same problem for me, running Debian Jessie too in an OpenVZ container.

**Comment by pde** [comment]
For @gree303's report: is the `dialog` package installed?  What is your PATH set to?

**Comment by alex3137** [comment]
That solved the problem for me, thanks !
