### ISSUE TITLE
Conditional python-ndg-httpsclient dependency doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2175]
During release testing:
```
export PIP_EXTRA_INDEX_URL=https://isnot.org/pip
./letsencrypt-auto --version -v
Bootstrapping dependencies for Debian-based OSes...
Ign http://us-east-1.ec2.archive.ubuntu.com trusty InRelease
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates InRelease           
Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release.gpg                 
Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release                     
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Sources        
Hit http://security.ubuntu.com trusty-security InRelease                       
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Sources    
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages 
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en 
Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Sources                
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Sources            
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main amd64 Packages         
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages     
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Translation-en         
Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Translation-en     
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://security.ubuntu.com trusty-security/universe Sources                
Hit http://security.ubuntu.com trusty-security/main amd64 Packages             
Ign http://us-east-1.ec2.archive.ubuntu.com trusty/main Translation-en_US      
Ign http://us-east-1.ec2.archive.ubuntu.com trusty/universe Translation-en_US  
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en  
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Ign http://ppa.launchpad.net trusty InRelease 
Hit http://ppa.launchpad.net trusty InRelease       
Hit http://ppa.launchpad.net trusty Release.gpg                              
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Hit http://ppa.launchpad.net trusty Release
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main Translation-en
Reading package lists... Done 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
augeas-lenses is already the newest version.
ca-certificates is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
python-virtualenv is already the newest version.
libssl-dev is already the newest version.
The following package was automatically installed and is no longer required:
  libjs-jquery
Use 'apt-get autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 141 not upgraded.
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/ubuntu/.local/share/letsencrypt/bin/python2.7
Also creating executable in /home/ubuntu/.local/share/letsencrypt/bin/python
Installing setuptools, pip...done.
Updating letsencrypt and virtual environment dependencies...
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.5/s/setuptools/setuptools-19.2-py2.py3-none-any.whl#md5=7bdac510b6bc1675a2a149eb3f81af77
  Downloading setuptools-19.2-py2.py3-none-any.whl (463kB): 463kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed setuptools
Cleaning up...
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
Collecting letsencrypt
/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached https://isnot.org/pip/letsencrypt/letsencrypt-0.2.0-py2-none-any.whl
Collecting letsencrypt-apache
  Using cached https://isnot.org/pip/letsencrypt-apache/letsencrypt_apache-0.2.0-py2-none-any.whl
Collecting zope.interface (from letsencrypt)
  Using cached zope.interface-4.1.3.tar.gz
Requirement already up-to-date: setuptools in /home/ubuntu/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt)
  Using cached python2-pythondialog-3.3.0.tar.bz2
Collecting PyOpenSSL (from letsencrypt)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting pytz (from letsencrypt)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting parsedatetime (from letsencrypt)
  Using cached parsedatetime-1.5-py2-none-any.whl
Collecting configobj (from letsencrypt)
  Using cached configobj-5.0.6.tar.gz
Collecting acme==0.2.0 (from letsencrypt)
  Using cached https://isnot.org/pip/acme/acme-0.2.0-py2-none-any.whl
Collecting psutil>=2.1.0 (from letsencrypt)
  Using cached psutil-3.3.0.tar.gz
Collecting six (from letsencrypt)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from letsencrypt)
  Using cached cryptography-1.2.1.tar.gz
Collecting zope.component (from letsencrypt)
  Using cached zope.component-4.2.2.tar.gz
Collecting mock (from letsencrypt)
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting ConfigArgParse (from letsencrypt)
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting pyrfc3339 (from letsencrypt)
  Using cached pyRFC3339-1.0-py2.py3-none-any.whl
Collecting python-augeas (from letsencrypt-apache)
  Using cached python-augeas-0.5.0.tar.gz
Collecting requests (from acme==0.2.0->letsencrypt)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting werkzeug (from acme==0.2.0->letsencrypt)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=0.7->letsencrypt)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=0.7->letsencrypt)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=0.7->letsencrypt)
  Using cached enum34-1.1.2.tar.gz
Collecting ipaddress (from cryptography>=0.7->letsencrypt)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=0.7->letsencrypt)
  Using cached cffi-1.4.2.tar.gz
Collecting zope.event (from zope.component->letsencrypt)
  Using cached zope.event-4.1.0.tar.gz
Collecting funcsigs (from mock->letsencrypt)
  Using cached funcsigs-0.4-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->letsencrypt)
  Using cached pbr-1.8.1-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=0.7->letsencrypt)
  Using cached pycparser-2.14.tar.gz
Installing collected packages: zope.interface, python2-pythondialog, six, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, PyOpenSSL, pytz, parsedatetime, configobj, requests, werkzeug, funcsigs, pbr, mock, pyrfc3339, acme, psutil, zope.event, zope.component, ConfigArgParse, letsencrypt, python-augeas, letsencrypt-apache
  Running setup.py install for zope.interface
  Running setup.py install for python2-pythondialog
  Running setup.py install for enum34
  Running setup.py install for pycparser
  Running setup.py install for cffi
  Running setup.py install for cryptography
  Running setup.py install for configobj
  Running setup.py install for psutil
  Running setup.py install for zope.event
  Running setup.py install for zope.component
  Running setup.py install for ConfigArgParse
  Running setup.py install for python-augeas
Successfully installed ConfigArgParse-0.10.0 PyOpenSSL-0.15.1 acme-0.2.0 cffi-1.4.2 configobj-5.0.6 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 letsencrypt-0.2.0 letsencrypt-apache-0.2.0 mock-1.3.0 parsedatetime-1.5 pbr-1.8.1 psutil-3.3.0 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 python-augeas-0.5.0 python2-pythondialog-3.3.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3 zope.component-4.2.2 zope.event-4.1.0 zope.interface-4.1.3
Requesting root privileges to run with virtualenv: sudo /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt --version -v
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 32, in <module>
    from letsencrypt import client
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 10, in <module>
    from acme import client as acme_client
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 28, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'pyopenssl'
```

**Comment by pde** [comment]
@Natim this looks like a side effect of #1914.  Strangely, it *is* working on some systems; debian squeeze was fine, for instance...

**Comment by pde** [comment]
Also CCing @erikrose for insights

**Comment by pde** [comment]
More info:
```
ubuntu@ip-172-31-50-10:~/.local/share/letsencrypt$ bin/pip freeze
acme==0.2.0
cffi==1.4.2
ConfigArgParse==0.10.0
configobj==5.0.6
cryptography==1.2.1
enum34==1.1.2
funcsigs==0.4
idna==2.0
ipaddress==1.0.16
letsencrypt==0.2.0
letsencrypt-apache==0.2.0
mock==1.3.0
parsedatetime==1.5
pbr==1.8.1
psutil==3.3.0
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
pyRFC3339==1.0
python-augeas==0.5.0
python2-pythondialog==3.3.0
pytz==2015.7
requests==2.9.1
six==1.10.0
Werkzeug==0.11.3
zope.component==4.2.2
zope.event==4.1.0
zope.interface==4.1.3
ubuntu@ip-172-31-50-10:~/.local/share/letsencrypt$ python --version
Python 2.7.6
```

**Comment by pde** [comment]
```
ubuntu@ip-172-31-50-10:~/.local/share/letsencrypt$ bin/pip --version
pip 7.1.2 from /home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages (python 2.7)
```

**Comment by bmw** [comment]
While likely way more info than anyone has wanted ever, here's a [log](https://gist.github.com/13634405fb8ce2ca54fb) of the problem where I modified `letsencrypt-auto` to run `pip` with `-vvv`.

**Comment by bmw** [comment]
Interestingly, I can recreate the problem on an Ubuntu 14.04 box using `bootstrap/venv.sh` but not `bootstrap/dev/venv.sh`...

**Comment by bmw** [comment]
Moar updates: The problem only occurs when using the `acme==0.2.0` wheel.

**Comment by kuba** [comment]
Where can I find the build artifacts? I would like to test stuff.

**Comment by Natim** [comment]
Yes you are probably right that conditionnal install_requires and wheel are not a good fit.

**Comment by Natim** [comment]
I will investigate.

**Comment by Natim** [comment]
A quick fix would be to install dependencies to all Python 2 version instead of just the one lower than 2.7.9

**Comment by Natim** [comment]
I will try to use [extra_requires](https://wheel.readthedocs.org/en/latest/#defining-conditional-dependencies) first.

**Comment by Natim** [comment]
```# env markers in extras_require cause problems with older pip:``` #517

**Comment by Natim** [comment]
Actually now that we dropped py2.6 support it might worth to actually use extra_requires.

**Comment by kuba** [comment]
`acme` never dropped support for Python2.6

**Comment by Natim** [comment]
@pde can you try ``pip install http://hubscher.remy.free.fr/wheel/acme-0.2.0.dev0-py2-none-any.whl``

**Comment by Natim** [comment]
@kuba oh, does it means we still cannot use ``extra_requires`` for that?

**Comment by Natim** [comment]
Note that we should probably really consider dropping py26 support since cryptography will soon.

```~/.virtualenvs/py269/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6```

**Comment by Natim** [comment]
Also note that today installing on py26 with the wheel is also broken.

**Comment by kuba** [comment]
That's not in the scope of this bug. We expect users to use old pip, so no, you cannot use those tags.

**Comment by kuba** [comment]
If current py26 wheel is broken, then please file a bug report, thanks!

**Comment by Natim** [comment]
I filed #2178 about this, also it seems to be tests dependencies so not a big issue.

**Comment by Natim** [comment]
> We expect users to use old pip, so no, you cannot use those tags.

Do you recall which version of pip I should test this with?

**Comment by pde** [comment]
@Natim unfortunately python2.6-by-default platforms are 10-15% of our userbase.  The most common is CentOS 6, but also Amazon Linux and some other rpm-based systems, and Debian Squeeze. So we won't be able to deprecate it for a few years without a lot of people yelling at us.

**Comment by pde** [comment]
I don't think I fully understand pip and venv interactions yet, and pip version numbers seem strange to me, but...

My sense is that inside venv we should always have a recent pip (7.1.2, currently), but outside we might have old ones.  For instance, the latest version of Amazon Linux ships python26-pip.noarch 0:6.1.1-1.21.amzn1.  On rpm systems we have [these versions](https://apps.fedoraproject.org/packages/python-pip) plus whatever is vailable on fedora 20, maybe?  On debian we have these: https://packages.debian.org/search?keywords=python-pip

**Comment by erikrose** [comment]
As @Natim said, dependencies that are conditional on the Python version just won't work with "none-any" wheels. At minimum, we'd need to build separate wheels for separate versions. Otherwise, the condition will go in the direction of the machine that happened to build the wheel. @bmw and I previously discussed pulling out the conditional dependencies and going with a works-anywhere set. We decided against it at the time, but now it's looking like a better idea. I can confirm that using the PyPI-based argparse works fine in 2.7; I do it all the time. I'm less certain about the ndg-httpsclient and pyasn1.

**Comment by Natim** [comment]
As far as I understand, letsencrypt will work without mock, argparse, pyasn1 and ndg-httpsclient.
So we should go with the extra_requires for ``pyasn1`` and ``ndg-httpsclient`` and keep using the if for 2.6 ``argparse`` and ``mock`` dependencies.

- argparse being already installed by other dependencies
- mock being useful for tests only
- pyasn1 and ndg-httpsclient just removing a warning (but it is still working fine without them)

I have implemented this proposal here: https://github.com/letsencrypt/letsencrypt/pull/2177/files

I am going to test that it works with py26 and pip 6.1.1.

**Comment by Natim** [comment]
I built the universal wheel with python 2.7.6.

**python2.6 with pip 6.1.1**

```
$ pip install dist/acme-0.2.0.dev0-py2.py3-none-any.whl 
You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing ./dist/acme-0.2.0.dev0-py2.py3-none-any.whl
[...]
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 ordereddict-1.1 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**Comment by Natim** [comment]
**python 2.7 with pip 7.1.1**
```
$ pip --version
pip 7.1.1 from ~/.virtualenvs/py276/local/lib/python2.7/site-packages (python 2.7)
$ pip install dist/acme-0.2.0.dev0-py2.py3-none-any.whl
Installing collected packages: pytz, requests, pyasn1, six, enum34, ipaddress, idna, pycparser, cffi, cryptography, PyOpenSSL, ndg-httpsclient, werkzeug, funcsigs, pbr, mock, pyrfc3339, acme
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**Comment by Natim** [comment]
**python 2.7 with pip 7.0.3**

```
$ pip --version
pip 7.0.3 from /home/rhubscher/.virtualenvs/py276-7.0/local/lib/python2.7/site-packages (python 2.7)
$ pip install dist/acme-0.2.0.dev0-py2.py3-none-any.whl
Installing collected packages: pytz, requests, pyasn1, six, enum34, ipaddress, idna, pycparser, cffi, cryptography, PyOpenSSL, ndg-httpsclient, werkzeug, funcsigs, pbr, mock, pyrfc3339, acme
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**Comment by Natim** [comment]
I think we can say that the patch works as expected will all version of python since ``pip 6.1``.

**Comment by Natim** [comment]
Oh wait I've build the wheel with python 2.7.6 so that it adds the dependencies to the ``install_requires``...

**Comment by Natim** [comment]
Let me start again building the wheel with python 3

**Comment by Natim** [comment]
**python 2.6.9 with pip 6.0.8**
```
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 ordereddict-1.1 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**Comment by Natim** [comment]
**python 2.6 with pip 6.1.1**

```
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 ordereddict-1.1 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**Comment by Natim** [comment]
**python 2.7.6 with pip 7.0.3**

```
Installing collected packages: pytz, requests, werkzeug, six, enum34, ipaddress, pyasn1, idna, pycparser, cffi, cryptography, PyOpenSSL, ndg-httpsclient, funcsigs, pbr, mock, pyrfc3339, acme
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**python 2.7.9 with pip 7.1**
```
Installing collected packages: pytz, requests, werkzeug, six, enum34, ipaddress, pyasn1, idna, pycparser, cffi, cryptography, PyOpenSSL, ndg-httpsclient, funcsigs, pbr, mock, pyrfc3339, acme
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 mock-1.3.0 ndg-httpsclient-0.4.0 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

**python 3.4.3 with pip 7.1**

```
Successfully installed PyOpenSSL-0.15.1 acme-0.2.0.dev0 cffi-1.4.2 cryptography-1.2.1 idna-2.0 mock-1.3.0 pbr-1.8.1 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3
```

It works because ``ndg-httpsclient`` is not installed. ``pyasn1`` is installed as a dependency for cryptography.

**Comment by Natim** [comment]
So I just had confirmation that python_version doesn't supports < and > comparison signs.

https://bitbucket.org/pypa/wheel/issues/139/wheel-should-support-pep-426-environment#comment-24717494
