### ISSUE TITLE
Can't build ACME on SLES 11

### ISSUE THREAD

**Issue by weberhofer** [letsencrypt/letsencrypt#2192]
Dear developers,
python-acme 0.2.0 fails building on SLES 11 with the error below. 
Is openSSL in the delivered version too old and unsupported, or is there something that can be done to make it building?

[  172s] ======================================================================
[  172s] ERROR: test_ps (acme.jose.jwa_test.JWARSTest)
[  172s] ----------------------------------------------------------------------
[  172s] Traceback (most recent call last):
[  172s]   File "/usr/src/packages/BUILD/acme-0.2.0/acme/jose/jwa_test.py", line 97, in test_ps
[  172s]     sig = PS256.sign(RSA1024_KEY, b'foo')
[  172s]   File "/usr/src/packages/BUILD/acme-0.2.0/acme/jose/jwa.py", line 110, in sign
[  172s]     signer = key.signer(self.padding, self.hash)
[  172s]   File "/usr/lib/python2.6/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 527, in signer
[  172s]     return _RSASignatureContext(self._backend, self, padding, algorithm)
[  172s]   File "/usr/lib/python2.6/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 187, in __init__
[  172s]     _Reasons.UNSUPPORTED_HASH
[  172s] UnsupportedAlgorithm: When OpenSSL is older than 1.0.1 then only SHA1 is supported with MGF1.
[  172s] 
[  172s] ----------------------------------------------------------------------

**Comment by bmw** [comment]
What OpenSSL version do you have?

**Comment by weberhofer** [comment]
It's a patched version of 0.9.8j

**Comment by weberhofer** [comment]
The same happens with acme 0.4.0;
