### ISSUE TITLE
Error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Name does not end in a public suffix

### ISSUE THREAD

**Issue by xEtarusx** [letsencrypt/letsencrypt#2258]
Hello, I'm getting the following error while trying to install letsencrypt certificates.

Executing this command
`./letsencrypt-auto --apache`

results in an error
`Error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Name does not end in a public suffix`

Here's the end of the log file
`2016-01-22 09:56:56,705:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
...skipping...
 "new-authz"}
2016-01-22 09:57:00,725:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jwk=None, x5u=None, kid=None, alg=None, cty=None, x5tS256=None, jku=None, x5t=None
2016-01-22 09:57:00,731:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, x5u=None, kid=None, cty=None, x5tS256=None, jku=None, x5t=None, nonce=None
2016-01-22 09:57:00,732:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "qR-ZqHYbCoNJFQEf6i-ZNida_1XUPNIsCDaUU3IzypGBuJmafV5kWDTNnquGjOZyitygJxfWVWqC0sVWjfsRJUpjIKLtwwTzBsCoBKQ24l0YFijlTXktMLqaYjQHmw7s__C8CJtS31ZZTZOJuB-eAmJB3bIUeUMoZiiK0sUphupFGfpZYtROhl5jKUbFRmaf3CxgUy1i1f_8GhUDCUqHm5FIeKvBbKS1OuKb-0xF0a88rMR81xDZnRLAYNjnN9xNsY2zrw0CXdRZItJCXksU5hZFpoAzmQ3PR6rMeFjQmHP8nqR-lgYinO7JJ606s9ILFakMNFnfP6eg6bsPu7Dvw"}}, "protected": "eyJub25jZSI6ICI5OVFObDFtWU5wSkZsVXF3RHvNzd3OWNnT1p2YlNodUdrNzZwRmhETFRjIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJyb3VuZGN1YmUud2VibWFpbCJ9LCAicmVzb3VyY2UiOiAibmVLWF1dGh6In0", "signature": "h6Cfed1oDJWp4BNYkvsU10qKNxWyVe-Dza7OwhImAqhB3SUDiwKcWxWA-owN8OxN-I2zBiLruID4h0x98xUJQXmht--0AQNgo836XvDaVrSpumP5k7XqNSqd4AHoGkDIVA_auBxRwJCKUJEnKfTfiFFp1JDnsZcdeb82NFwOmaaTdMZJcGdo3XGVNqQ_DZ-f96Wg4oYlJ4W_rWQQTCtU58rq7fuwluaDDXFh7DhQ3WV0j8Q-8Wfs-bQUMn2kxyLsE4XFnXzBS80D94MS76ajpiHwBWwoAciFREZd-F3Jw7Dye2VPTAueh9uQSOzjqLfYLULG9rTfm4q71DTQ63Lpg"}'}
2016-01-22 09:57:00,734:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-01-22 09:57:00,967:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 400 124
2016-01-22 09:57:00,969:DEBUG:root:Received <Response [400]>. Headers: {'Content-Length': '124', 'Server': 'nginx', 'Connection': 'close', 'Date': 'Fri, 22 Jan 2016 09:57:00 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'zEEwoWNHNAJ8dc-yEL5mspibvc0Y-Squ_UH1DWf5cVA'}. Content: '{"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Name does not end in a public suffix","status":400}'
2016-01-22 09:57:00,970:DEBUG:acme.client:Storing nonce: '\xccA0\xa1cG4\x02|u\xcf\xb2\x10\xbef\xb2\x98\x9b\xbd\xcd\x18\xf9*\xae\xfdA\xf5\rg\xf9qP'
2016-01-22 09:57:00,970:DEBUG:acme.client:Received response <Response [400]> (headers: {'Content-Length': '124', 'Server': 'nginx', 'Connection': 'close', 'Date': 'Fri, 22 Jan 2016 09:57:00 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'zEEwoWNHNAJ8dc-yEL5mspibvc0Y-Squ_UH1DWf5cVA'}): '{"type":"urn:acme:error:malformed","detail":"Error creating new authz :: Name does not end in a public suffix","status":400}'
2016-01-22 09:57:00,972:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1398, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 559, in run
    lineage = _auth_from_domains(le_client, config, domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 404, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 634, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 550, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Name does not end in a public suffix`

Any ideas on how to fix this?
Thanks

**Comment by xEtarusx** [comment]
Problem was a faulty domain which was checked because of the roundcube webmail installation .... I don't know why. ("roundcube.webmail")
