### ISSUE TITLE
Letsencrypt cannot create certificate

### ISSUE THREAD

**Issue by freaknils** [letsencrypt/letsencrypt#2301]
If I do a letsencrypt certonly --standalone -d example.com I get following error:
`root@localhost:  > letsencrypt certonly --standalone -d example.com
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.3.0', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 550, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2710, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/letsencrypt/cli.py", line 32, in <module>
    from letsencrypt import client
  File "/usr/lib/python2.7/site-packages/letsencrypt/client.py", line 27, in <module>
    from letsencrypt import storage
  File "/usr/lib/python2.7/site-packages/letsencrypt/storage.py", line 29, in <module>
    def add_time_interval(base_time, interval, textparser=parsedatetime.Calendar()):
  File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 271, in __init__
    self.ptc = Constants()
  File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 2357, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/lib/python2.7/site-packages/parsedatetime/pdt_locales/icu.py", line 48, in get_icu
    result['icu'] = icu = pyicu.Locale(locale)
AttributeError: 'module' object has no attribute 'Locale'`

`root@localhost: /etc  > python2 --version
Python 2.7.11`

`root@localhost: /etc  > openssl version 
OpenSSL 1.0.2e 3 Dec 2015
`

OS ist current Archlinux

A few weeks ago everything worked fine.

**Comment by bmw** [comment]
Is your [locale](https://wiki.archlinux.org/index.php/Locale) set? What's the output of `locale -a`?

**Comment by freaknils** [comment]
Yes it is set:

> root@localhost:
 ~  > locale -a
C
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
de_DE.utf8
deutsch
en_US
en_US.iso88591
en_US.utf8
german
POSIX

**Comment by bmw** [comment]
Sorry for all the followup questions, but can I asked how you installed the client?

**Comment by freaknils** [comment]
No problem! I use the package from the official [Archlinux mirror](https://www.archlinux.org/packages/community/any/letsencrypt/)

**Comment by freaknils** [comment]
At the moment it is still not running and my certificates expire in a few days. Is there an update?

**Comment by DeltaBravo** [comment]
I am also running into this issue!
```
$ locale -a
C
en_US.utf8
POSIX
```

**Comment by freaknils** [comment]
The error is still there. Are there any possible solutions??
```
root@localhost (17.05.2016) 10:21:22 
: /etc  > letsencrypt renew --standalone --dry-run
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.5.0', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/letsencrypt/main.py", line 18, in <module>
    from letsencrypt import client
  File "/usr/lib/python2.7/site-packages/letsencrypt/client.py", line 26, in <module>
    from letsencrypt import storage
  File "/usr/lib/python2.7/site-packages/letsencrypt/storage.py", line 29, in <module>
    def add_time_interval(base_time, interval, textparser=parsedatetime.Calendar()):
  File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 271, in __init__
    self.ptc = Constants()
  File "/usr/lib/python2.7/site-packages/parsedatetime/__init__.py", line 2375, in __init__
    self.locale = get_icu(self.localeID)
  File "/usr/lib/python2.7/site-packages/parsedatetime/pdt_locales/icu.py", line 48, in get_icu
    result['icu'] = icu = pyicu.Locale(locale)
AttributeError: 'module' object has no attribute 'Locale'
```

**Comment by schlauberg** [comment]
Hi,

I fixed it in my archlinux cryptography package.
The problem came from what seems like a regression, in version 1.2.1 things were still okay.
Edit:
/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py"
replace:
20            ep.resolve()
with
 20             ep.resolve() if hasattr(ep, "resolve") else ep.load(require=False)
.
I included the patchfile as attachment. Being in the same directory as the patchfile you simply go:

sudo patch /usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py ./crypto.patch

[crypto.patch.gz](https://github.com/certbot/certbot/files/364775/crypto.patch.gz)

**Comment by gjedeer** [comment]
In case this helps someone, I've been able to work around this issue un Ubuntu 18.04 by removing my existing installation:

```
pip uninstall certbot
```

and re-installing with pip3:

```
pip3 install certbot
```

**Comment by marklit** [comment]
If anyone is getting this issue and is still running Python 2.7 the following should downgrade both setuptools and parsedatetime in the right order so that certbot is usable. The following is in a virtualenv:

```bash
$ virtualenv ~/.certbot
$ source ~/.certbot/bin/activate
$ pip install 'setuptools<41'
$ pip install certbot
$ pip install 'parsedatetime<2.6'

$ sudo /home/ubuntu/.certbot/bin/certbot
```
