### ISSUE TITLE
AssertionError: Authorizations list is empty - With SAN extension

### ISSUE THREAD

**Issue by zettabithf** [letsencrypt/letsencrypt#2390]
So all the other issues I've seen have apparently been 'solved' and closed, but even now with a SAN record specified, I still get the Authorization list is empty error.

Creating CSR:

> openssl req -new -sha256 -key ca.key -subj '/C=US/ST=NY/L=New York/O=Company, LLC/OU=Web Services/CN=domain.com/subjectAltName=domain.com' > ca.csr

Verified that it contains the record:
> openssl req -noout -text -in ca.csr -inform pem

> Subject: C=US, ST=NY, L=New York, O=Company, LLC, OU=Web Services, CN=domain.com/subjectAltName=domain.com

Convert to DER form:
> openssl req -in ca.csr -inform pem -outform der -out ca.der

Calling LE client:
> letsencrypt-auto auth --csr ca.der

Result:
> Updating letsencrypt and virtual environment dependencies......
> Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt auth --csr ca.der
> Version: 1.1-20080819
> Version: 1.1-20080819
> An unexpected error occurred:
> AssertionError: Authorizations list is empty
> Please see the logfiles in /var/log/letsencrypt for more details.

Log file:

> 2016-02-06 08:59:30,073:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-02-06 08:59:30,075:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-02-06 08:59:30,077:DEBUG:letsencrypt.cli:letsencrypt version: 0.3.0
2016-02-06 08:59:30,077:DEBUG:letsencrypt.cli:Arguments: ['--csr', 'ca.der']
2016-02-06 08:59:30,078:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-02-06 08:59:30,085:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2016-02-06 08:59:30,839:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#apache): ('Apache Version %s not supported.', '(2, 2, 15)')
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 160, in prepare
    "Apache Version %s not supported.", str(self.version))
NotSupportedError: ('Apache Version %s not supported.', '(2, 2, 15)')
2016-02-06 08:59:30,840:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): --webroot-path must be set
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 53, in prepare
    self.option_name("path")))
PluginError: --webroot-path must be set
2016-02-06 08:59:30,841:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0xb5c6086c>
Prep: True
2016-02-06 08:59:30,842:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0xb5c6086c> and installer None
2016-02-06 08:59:30,862:DEBUG:letsencrypt.cli:Picked account: <Account(7438702ca2e671cdc89a86bd0897a02c)>
2016-02-06 08:59:30,864:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-02-06 08:59:30,868:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-02-06 08:59:33,267:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-02-06 08:59:33,270:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Sat, 06 Feb 2016 08:59:47 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 06 Feb 2016 08:59:47 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '5qh47WV8ngc6Qqr5F7qD04fbmpHPMNLLCOpViYB6ZZ4'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-02-06 08:59:33,270:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Sat, 06 Feb 2016 08:59:47 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sat, 06 Feb 2016 08:59:47 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '5qh47WV8ngc6Qqr5F7qD04fbmpHPMNLLCOpViYB6ZZ4'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-02-06 08:59:33,271:DEBUG:letsencrypt.client:CSR: CSR(file='/root/ssl/ca.der', data='{redacted}', form='der'), domains: []
2016-02-06 08:59:33,271:INFO:letsencrypt.auth_handler:Performing the following challenges:
2016-02-06 08:59:33,273:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1454, in main
    return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 633, in obtain_cert
    file=args.csr[0], data=args.csr[1], form="der"))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 245, in obtain_certificate_from_csr
    csr.data, OpenSSL.crypto.FILETYPE_ASN1), csr)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 228, in _obtain_certificate
    authzr)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 300, in request_issuance
    assert authzrs, "Authorizations list is empty"
AssertionError: Authorizations list is empty

**Comment by kuba** [comment]
You're creating CSR without SAN fields. `acme` (and the protocol, Boulder most likely as well) don't care about `CN`.  `letsencrypt` doesn't check user-supplied CSRs properly before passing it on.

**Comment by zettabithf** [comment]
If what I'm doing isn't creating the CSR with a SAN field, then how does one insert a SAN field?

**Comment by kuba** [comment]
https://github.com/letsencrypt/letsencrypt/blob/master/examples/generate-csr.sh

**Comment by zettabithf** [comment]
That solved it. Thanks.
