### ISSUE TITLE
"Failed to connect to host for DVSNI challenge" inside a docker container

### ISSUE THREAD

**Issue by anthony-o** [letsencrypt/letsencrypt#2462]
I'm running `letsencrypt-auto` inside a docker container (from Ubuntu 14.04.3, I installed apache2 & letsencrypt using git clone) inside an AWS EC2 instance.
In this docker container, only the port 443 is available from foreign requests (the security group for that EC2 instance allows 443 port from any source, and my docker container runs with `-p "443:443"`).

When I run `letsencrypt-auto --apache -d my.domain.tld --email ssl@my.domain.tld --agree-tos`, I'm getting this error:

> Failed authorization procedure. my.domain.tld (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge

I've tried to run `/root/.local/share/letsencrypt/bin/letsencrypt --no-self-upgrade -d my.domain.tld --email ssl@my.domain.tld --manual --agree-tos certonly` in order to check what's going on and saw that it tries to open the 80 port in order to do the acme challenge (which will fail because port 80 is not accessible remotely).

I found nothing in the documentation to specify the DVSNI challenge port and encountered in some github issues that a `--simple-http-port` or a `--dvsni-port` could be used, but both option gives me `letsencrypt: error: unrecognized arguments: --simple-http-port 443` and `letsencrypt: error: unrecognized arguments: --dvsni-port 443` when I try them with `--manual certonly` or even with `--apache run`.

Then I tried to run `letsencrypt-auto --verbose --apache -d my.domain.tld --email ssl@my.domain.tld --agree-tos` in order to see what happens.
Here are the last lines:

> 2016-02-12 17:21:08,580:DEBUG:acme.challenges:dns-01 was not recognized, full message: {u'status': u'pending', u'token': u'dCCjqOCCaGQza4d32HKZLhMvrEkybcPpNbFCHHuaEmg', u'type': u'dns-01', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/lQ6oaEe0qTaIXsVyRi3Ttyb1h4xF63fuH95jftSKGVs/16236635'}
> 2016-02-12 17:21:08,581:INFO:letsencrypt.reporter:Reporting to user: The following errors were reported by the server:
> Domain: my.domain.tld
> Type:   connection
> Detail: Failed to connect to host for DVSNI challenge
> 
> To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
> 2016-02-12 17:21:08,586:INFO:letsencrypt.auth_handler:Cleaning up challenges
> 2016-02-12 17:21:08,685:INFO:letsencrypt.reverter:The Let's Encrypt client has not saved any backups of your configuration
> 2016-02-12 17:21:08,690:DEBUG:letsencrypt_apache.configurator:None
> 2016-02-12 17:21:08,792:DEBUG:letsencrypt.cli:Exiting abnormally:
> Traceback (most recent call last):
>   File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
>     sys.exit(main())
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1987, in main
>     return config.func(config, plugins)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 663, in run
>     lineage, action = _auth_from_domains(le_client, config, domains)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 475, in _auth_from_domains
>     lineage = le_client.obtain_and_enroll_certificate(domains)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 269, in obtain_and_enroll_certificate
>     certr, chain, key, _ = self.obtain_certificate(domains)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 252, in obtain_certificate
>     return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 225, in obtain_certificate_from_csr
>     authzr = self.auth_handler.get_authorizations(domains)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 84, in get_authorizations
>     self._respond(cont_resp, dv_resp, best_effort)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 142, in _respond
>     self._poll_challenges(chall_update, best_effort)
>   File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 204, in _poll_challenges
>     raise errors.FailedChallenges(all_failed_achalls)
> FailedChallenges: Failed authorization procedure. my.domain.tld (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to host for DVSNI challenge

**Comment by anthony-o** [comment]
Finally the problem was coming from a typo: `-p "443:433"` instead of `-p "443:443"` when running the docker container... sorry!
