### ISSUE TITLE
Upgrading letsencrypt-auto 0.4.0 to 0.4.1 failed

### ISSUE THREAD

**Issue by soruly** [letsencrypt/letsencrypt#2575]
I just cloned the latest source and run the upgrade.
It stuckes at Installing Python packages... like forever. (I've waited over 15 minutes)
```
[soruly@socky ~]$ python --version
Python 2.7.5
[soruly@socky ~]$ pip --version
pip 8.0.2 from /usr/lib/python2.7/site-packages (python 2.7)
[soruly@socky ~]$ rm -rf letsencrypt/
[soruly@socky ~]$ git clone https://github.com/letsencrypt/letsencrypt.git
Cloning into 'letsencrypt'...
remote: Counting objects: 32243, done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 32243 (delta 92), reused 0 (delta 0), pack-reused 32077
Receiving objects: 100% (32243/32243), 8.39 MiB | 276.00 KiB/s, done.
Resolving deltas: 100% (22812/22812), done.
[soruly@socky ~]$ cd letsencrypt/
[soruly@socky letsencrypt]$ ./letsencrypt-auto
Bootstrapping dependencies for RedHat-based OSes...
dnf is /usr/bin/dnf
Using metadata from Mon Feb 29 07:08:30 2016
Package python-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-devel-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-devel-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-virtualenv-1.10.1-2.el7.noarch is already installed, skipping.
Package python-virtualenv-1.10.1-2.el7.noarch is already installed, skipping.
Package python-tools-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-tools-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-pip-7.1.0-1.el7.noarch is already installed, skipping.
Package python-pip-7.1.0-1.el7.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Using metadata from Mon Feb 29 07:08:30 2016
Package gcc-4.8.5-4.el7.x86_64 is already installed, skipping.
Package gcc-4.8.5-4.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package redhat-rpm-config-9.1.0-68.el7.centos.noarch is already installed, skipping.
Package redhat-rpm-config-9.1.0-68.el7.centos.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Using metadata from Mon Feb 29 07:08:30 2016
Package mod_ssl-1:2.4.6-40.el7.centos.x86_64 is already installed, skipping.
Package mod_ssl-1:2.4.6-40.el7.centos.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Checking for new version...
Upgrading letsencrypt-auto 0.4.0 to 0.4.1...
Replacing letsencrypt-auto...
   sudo cp /tmp/tmp.fywmMaDkpA/letsencrypt-auto ./letsencrypt-auto
Bootstrapping dependencies for RedHat-based OSes...
dnf is /usr/bin/dnf
Using metadata from Mon Feb 29 07:08:30 2016
Package python-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-devel-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-devel-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-virtualenv-1.10.1-2.el7.noarch is already installed, skipping.
Package python-virtualenv-1.10.1-2.el7.noarch is already installed, skipping.
Package python-tools-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-tools-2.7.5-34.el7.x86_64 is already installed, skipping.
Package python-pip-7.1.0-1.el7.noarch is already installed, skipping.
Package python-pip-7.1.0-1.el7.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Using metadata from Mon Feb 29 07:08:30 2016
Package gcc-4.8.5-4.el7.x86_64 is already installed, skipping.
Package gcc-4.8.5-4.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package dialog-1.2-4.20130523.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package augeas-libs-1.4.0-2.el7.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package openssl-devel-1:1.0.1e-51.el7_2.2.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package libffi-devel-3.0.13-16.el7.x86_64 is already installed, skipping.
Package redhat-rpm-config-9.1.0-68.el7.centos.noarch is already installed, skipping.
Package redhat-rpm-config-9.1.0-68.el7.centos.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Package ca-certificates-2015.2.6-70.1.el7_2.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Using metadata from Mon Feb 29 07:08:30 2016
Package mod_ssl-1:2.4.6-40.el7.centos.x86_64 is already installed, skipping.
Package mod_ssl-1:2.4.6-40.el7.centos.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Creating virtual environment...
Installing Python packages...
^C
Traceback (most recent call last):
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 864, in peep_install
[soruly@socky letsencrypt]$     for path in req_paths))
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 864, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 841, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 422, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 701, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 657, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 615, in _downloaded_filename
    file_path = self._download(link)
  File "/tmp/tmp.iTPRz1uDte/peep.py", line 577, in _download
    response = opener(urlparse(url).scheme != 'http').open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1217, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib64/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib64/python2.7/ssl.py", line 736, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.7/ssl.py", line 630, in read
    v = self._sslobj.read(len or 1024)
KeyboardInterrupt
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by erikrose** [comment]
Have you retried? My guess is it's some bit of network weather between you and PyPI's caching CDN.

**Comment by soruly** [comment]
The issue has resolved. I can upgrade to 0.4.1 without any problems now, thanks!

**Comment by erikrose** [comment]
Drat those network gremlins! Thanks for reporting back.
