### ISSUE TITLE
ImportError:  undefined symbol: EC_GROUP_new_curve_GF2m

### ISSUE THREAD

**Issue by gcstang** [letsencrypt/letsencrypt#2614]
When I try to run ./letsencrypt-auto --help I constantly get this issue, I had several others before but now this one.  (The prior ones were related to CentOS 7.2 and the location of ffi header files, I had to create a symbolic link from ln -s /usr/include/ into /usr/include/python2.7/ for these errors)

This used to all work fine but it seems somewhere while doing a renew this was updated and now no longer works.  Help would be greatly appreciated.

CentOS Linux release 7.2.1511 (Core)

`Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --help
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.2', 'console_scripts', 'letsencrypt')()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 21, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m`

**Comment by 70599** [comment]
I have same error now.
How to fix this?

**Comment by jcberthon** [comment]
Hi @gcstang 

Why did you close the issue? There are no solution to that issue that are tracked here, and at least @70599 and I do still have the problem.

Could you reopen the issue? (as sometimes people do not react on old closed issues, I reserve the right to open a new issue which will be a duplicate of that one obviously if there are not activity here anymore :-) )

**Comment by jcberthon** [comment]
I've found a workaround:

```
mv ~/.local/share/letsencrypt{,.old}
certbot-auto --help
```

It will reinstall certbot and it now seems to work.
