### ISSUE TITLE
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert

### ISSUE THREAD

**Issue by BrainStone** [letsencrypt/letsencrypt#2616]
I tried creating a cert for quite a few domains. I have all the domains and they all point to the same webspace.

I used this command: `letsencrypt-auto certonly --webroot --rsa-key-size 4096 -w /var/www/webmail/ -d mail.crazyblock-network.net -d webmail.crazyblock-network.net -d imap.crazyblock-network.net -d smtp.crazyblock-network.net -d webmail.cb-net.work -d mail.cb-net.work -d imap.cb-net.work -d smtp.cb-net.work -d webmail.tekkriver.de -d mail.tekkriver.de -d imap.tekkriver.de -d smtp.tekkriver.de -d webmail.icon-craft.net -d mail.icon-craft.net -d imap.icon-craft.net -d smtp.icon-craft.net`

This resulted in the following error:
```
An unexpected error occurred:
The server experienced an internal error :: Error creating new cert
```

The last few lines in the log `/var/log/letsencrypt/letsencrypt.log` look like this:

```
2016-03-06 14:40:58,328:INFO:letsencrypt.auth_handler:Cleaning up challenges
2016-03-06 14:40:58,328:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/nnsHBXtkOprJZfZ0UQ-YmvH-fBZNSGE3d_fQXHXAfOw
2016-03-06 14:40:58,328:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/BfEcyi3o-EIucqUfRRokHSyAAsmrUmv7bZAchrw5s0U
2016-03-06 14:40:58,328:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/xQB8AXrcdEDJA92Eoss7vKYEp97Ed_bV8g8US4j-ewM
2016-03-06 14:40:58,329:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/uPQUiKMT2UQ-JItTA31fy2CKdXIA44VjUfjIkoEX7d0
2016-03-06 14:40:58,329:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/uWUAjJ3WCTyJBIaYnTrX3k-lVX83TEhZ83GMY8vzrpE
2016-03-06 14:40:58,329:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/3ittcDOx-lPUQXngAtYxFpobjThTQEPOzReV3KQRO6A
2016-03-06 14:40:58,329:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/-xE-bCH_arIL-C1ximEufmVoLgHHLibRLu-rVxyN0kM
2016-03-06 14:40:58,330:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/yp5qDWhk2kSZ5aJaPQZUwQ-Sa7WqORbMAJVfcqRYgNs
2016-03-06 14:40:58,330:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/ycc9zh__erfguJ2hu4SgLzAg9nOkSfh1tKcgBadmZfs
2016-03-06 14:40:58,330:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/rk2b1mLFZxgeXWanu2Cxj2VxEWHDSf2XnHzP30Pq-iA
2016-03-06 14:40:58,330:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/dOZDI7waIKoLQoDzQ8wVZt_HfjeFBSVhvXeuccuUXTQ
2016-03-06 14:40:58,330:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/tCaG9quQwjJzOUgE4U_01OMHXHp08ysnCrxN8KkHV1k
2016-03-06 14:40:58,331:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/itNO1zJOawbDbxMHTWQevZtFuPvcIKFYsemrQ1S1dnQ
2016-03-06 14:40:58,331:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/GCnI4hCBvvgwkjsSdoNZ6J5AKsPTtxNcx4_be4ungsI
2016-03-06 14:40:58,331:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/82f3uTp5RRDEH18oVi1wGQfdPaRk39NgJLvd_4M_FYc
2016-03-06 14:40:58,331:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/webmail/.well-known/acme-challenge/ixFJWB-iyvTm0wAiOq_M9K3rJ-2wY1Osi5lJ0i6OysI
2016-03-06 14:40:58,332:DEBUG:letsencrypt.plugins.webroot:Challenges cleaned up but /var/www/webmail/.well-known/acme-challenge not empty
2016-03-06 14:40:58,332:DEBUG:acme.client:Requesting issuance...
2016-03-06 14:40:58,332:DEBUG:acme.client:Serialized JSON: {"resource": "new-cert", "csr": "MIIF_TCCA-UCAQIwJjEkMCIGA1UEAwwbbWFpbC5jcmF6eWJsb2NrLW5ldHdvcmsubmV0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1seyMfcxMv9FPE11k8p20CMjtN3d6YDrZrsApQhP_sXhP4B8RXwtbKIz5Gx-yjsGXqzCtlCCj-292TglgNPzuS651Z8_i97OoUbJGIeo_-NGx_9x0NN1VXGqD11oFeCdMddYrHigKGwXoz7PpAdyS6Cfd4iQwEbb3OJh0zNJSzH-FPXAhW1HEfCO74Jpy72J_PBSFmJi15Y0ifXhNQ7_0QJQXkcPPEoXufaX7KbyympdTD74LzPOiXUDTFWQYQ_1aQNfVZ_d0wLQQyihCr1fhtnx0z4bxdFIyGg1S7lKz-jtP5C9BSVaMGG1mHW7t2teVSkZoCdUImEeHses9i7BwbxY4O1uWsLuugxeo9aHnFJYrJIM6EWrVYAAXCjkJ-loQt9F1PpvbPQ5EOzdrzAQV2_B6onZSpF09QSwRi3HZJ6QUSvUQu4UGqLU6J7PEe9L9jy7JSFcI1mjzAj3Bc_nSo2EXvxKT9jvB_2Qc1YAkk9jCLzrK-RmAD4k6iPDJY9_kQ56ZWu3llBQk6ewVcBPbMDciT7-ZuaJReiLeFTp6pTB12Rhj7Mg1fBGJuLiVgV-hGWpV45faoo6a0MVWzzfSJzjWEY4NDlvVWnxZx5UbLmwcdYPTPTEJfgOyGCkkPEyqGWDxqBoPO3jzNlWQpBXNcgo1b-UVbTJiDQZik9-xhECAwEAAaCCAZAwggGMBgkqhkiG9w0BCQ4xggF9MIIBeTCCAXUGA1UdEQSCAWwwggFoghttYWlsLmNyYXp5YmxvY2stbmV0d29yay5uZXSCHndlYm1haWwuY3JhenlibG9jay1uZXR3b3JrLm5ldIIbaW1hcC5jcmF6eWJsb2NrLW5ldHdvcmsubmV0ghtzbXRwLmNyYXp5YmxvY2stbmV0d29yay5uZXSCE3dlYm1haWwuY2ItbmV0LndvcmuCEG1haWwuY2ItbmV0LndvcmuCEGltYXAuY2ItbmV0LndvcmuCEHNtdHAuY2ItbmV0LndvcmuCFHdlYm1haWwudGVra3JpdmVyLmRlghFtYWlsLnRla2tyaXZlci5kZYIRaW1hcC50ZWtrcml2ZXIuZGWCEXNtdHAudGVra3JpdmVyLmRlghZ3ZWJtYWlsLmljb24tY3JhZnQubmV0ghNtYWlsLmljb24tY3JhZnQubmV0ghNpbWFwLmljb24tY3JhZnQubmV0ghNzbXRwLmljb24tY3JhZnQubmV0MA0GCSqGSIb3DQEBCwUAA4ICAQCp8u4UZ1GyoMkOSgrDOjVirn-3-elRwou1zNZAzBLDLz2bNrrBhiyCCZczNmAVYQHuLgbSHyND-DBkUJhmx7gRQ6BqFMstztcW8CBegkAHRohQrqz_hEO92K36QFRUlimQmNv8lwaHPS9qjdUlo-dY4grZPsLSqE0e5iVF6zLMNExe5RqpK9-Bcx7J4JcjodRIHoPmLgafibS0hkR5qTV2dETJNEOiZ9DR40wu_EMZVzDXTg2-LF3WpS_ZLTRP2pS2XNzuDAAJbBJeKyrxpk3zTByKBGzZ8tBlaibrfpq-GxwxgO-I7hfEUA2l-OH5GoZqV2k_Ue4gjgUfUG1oc3eQ1-oYG0P-i93E5ycWgvbmcBUdFeBzySWYpXibtGR80jjvGqdkU15uNaHCUHWd93f4_nysCNEUrJmckUO7XLsiYM3MnkojszfLMCV-zGO6kcjGJwVkWC6QZ3g3XOiMSkqSoqkHwWfOPfIqxAQ5tFSojwLnd7nB3_DDuQswqbawx17j-F00c5oTevrTtsZSQlxc4VwXIDlRI2kMYlxzu0qi7lLrPAyFGwp_6xx7Bnj7oLa_-Mrl8VCe0y44i7qL9KVOjFuFNP2zXG90UjDgetKb1LjvyPW2tCTyFweReZBnGDSvxPTSQphY3RW16Ha4_A_TlG2l04jubNQ6n2IUiYE4Ew"}
2016-03-06 14:40:58,333:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, alg=None, jku=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None, jwk=None
2016-03-06 14:40:58,337:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, nonce=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None
2016-03-06 14:40:58,338:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-cert. args: (), kwargs: {'headers': {'Accept': 'application/pkix-cert'}, 'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "4yUnSRBHYc_dXB8pSFz2CV_-ceha1segXQ7refbAEDebiOPgOx-6f6Kn5ze8KNZSz9ggPuzowTEFQMvtFky-zJPRjy6h-NTny4gaDP8CYmlcsqjv1BBBVPAWq7qoAJEQ7cEjrhwsgPRLPdqMRgs3TEWvC13QHEHRMwyqlBmTymOQ-ZPUHrRqrL5u9Dtjsr-cEE7y5LAglq7FUdnYcm0OuqwLkuqee85LOFNUTBEdQEx_52oVnYj6YnZTOjNXTTsizlBA0wEqG8ErBC6_MvuPuFhP6GtINBKxB0LeAnn0YoIubAn2ASqNi8N4_rKlWGcBkcelW1KT-bu5sXGsZ68YZw"}}, "protected": "eyJub25jZSI6ICJTa21RUHJaSks5SzdiZ0p2MjRtTTdMS1pQQlNLWlFjUHZjcmtnZXFfUl9JIn0", "payload": "eyJyZXNvdXJjZSI6ICJuZXctY2VydCIsICJjc3IiOiAiTUlJRl9UQ0NBLVVDQVFJd0pqRWtNQ0lHQTFVRUF3d2JiV0ZwYkM1amNtRjZlV0pzYjJOckxXNWxkSGR2Y21zdWJtVjBNSUlDSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQTFzZXlNZmN4TXY5RlBFMTFrOHAyMENNanROM2Q2WURyWnJzQXBRaFBfc1hoUDRCOFJYd3RiS0l6NUd4LXlqc0dYcXpDdGxDQ2otMjkyVGdsZ05QenVTNjUxWjhfaTk3T29VYkpHSWVvXy1OR3hfOXgwTk4xVlhHcUQxMW9GZUNkTWRkWXJIaWdLR3dYb3o3UHBBZHlTNkNmZDRpUXdFYmIzT0poMHpOSlN6SC1GUFhBaFcxSEVmQ083NEpweTcySl9QQlNGbUppMTVZMGlmWGhOUTdfMFFKUVhrY1BQRW9YdWZhWDdLYnl5bXBkVEQ3NEx6UE9pWFVEVEZXUVlRXzFhUU5mVlpfZDB3TFFReWloQ3IxZmh0bngwejRieGRGSXlHZzFTN2xLei1qdFA1QzlCU1ZhTUdHMW1IVzd0MnRlVlNrWm9DZFVJbUVlSHNlczlpN0J3YnhZNE8xdVdzTHV1Z3hlbzlhSG5GSllySklNNkVXclZZQUFYQ2prSi1sb1F0OUYxUHB2YlBRNUVPemRyekFRVjJfQjZvblpTcEYwOVFTd1JpM0haSjZRVVN2VVF1NFVHcUxVNko3UEVlOUw5ank3SlNGY0kxbWp6QWozQmNfblNvMkVYdnhLVDlqdkJfMlFjMVlBa2s5akNMenJLLVJtQUQ0azZpUERKWTlfa1E1NlpXdTNsbEJRazZld1ZjQlBiTURjaVQ3LVp1YUpSZWlMZUZUcDZwVEIxMlJoajdNZzFmQkdKdUxpVmdWLWhHV3BWNDVmYW9vNmEwTVZXenpmU0p6aldFWTRORGx2VldueFp4NVViTG13Y2RZUFRQVEVKZmdPeUdDa2tQRXlxR1dEeHFCb1BPM2p6TmxXUXBCWE5jZ28xYi1VVmJUSmlEUVppazkteGhFQ0F3RUFBYUNDQVpBd2dnR01CZ2txaGtpRzl3MEJDUTR4Z2dGOU1JSUJlVENDQVhVR0ExVWRFUVNDQVd3d2dnRm9naHR0WVdsc0xtTnlZWHA1WW14dlkyc3RibVYwZDI5eWF5NXVaWFNDSG5kbFltMWhhV3d1WTNKaGVubGliRzlqYXkxdVpYUjNiM0pyTG01bGRJSWJhVzFoY0M1amNtRjZlV0pzYjJOckxXNWxkSGR2Y21zdWJtVjBnaHR6YlhSd0xtTnlZWHA1WW14dlkyc3RibVYwZDI5eWF5NXVaWFNDRTNkbFltMWhhV3d1WTJJdGJtVjBMbmR2Y211Q0VHMWhhV3d1WTJJdGJtVjBMbmR2Y211Q0VHbHRZWEF1WTJJdGJtVjBMbmR2Y211Q0VITnRkSEF1WTJJdGJtVjBMbmR2Y211Q0ZIZGxZbTFoYVd3dWRHVnJhM0pwZG1WeUxtUmxnaEZ0WVdsc0xuUmxhMnR5YVhabGNpNWtaWUlSYVcxaGNDNTBaV3RyY21sMlpYSXVaR1dDRVhOdGRIQXVkR1ZyYTNKcGRtVnlMbVJsZ2haM1pXSnRZV2xzTG1samIyNHRZM0poWm5RdWJtVjBnaE50WVdsc0xtbGpiMjR0WTNKaFpuUXVibVYwZ2hOcGJXRndMbWxqYjI0dFkzSmhablF1Ym1WMGdoTnpiWFJ3TG1samIyNHRZM0poWm5RdWJtVjBNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUNBUUNwOHU0VVoxR3lvTWtPU2dyRE9qVmlybi0zLWVsUndvdTF6TlpBekJMREx6MmJOcnJCaGl5Q0NaY3pObUFWWVFIdUxnYlNIeU5ELURCa1VKaG14N2dSUTZCcUZNc3R6dGNXOENCZWdrQUhSb2hRcnF6X2hFTzkySzM2UUZSVWxpbVFtTnY4bHdhSFBTOXFqZFVsby1kWTRnclpQc0xTcUUwZTVpVkY2ekxNTkV4ZTVScXBLOS1CY3g3SjRKY2pvZFJJSG9QbUxnYWZpYlMwaGtSNXFUVjJkRVRKTkVPaVo5RFI0MHd1X0VNWlZ6RFhUZzItTEYzV3BTX1pMVFJQMnBTMlhOenVEQUFKYkJKZUt5cnhwazN6VEJ5S0JHelo4dEJsYWlicmZwcS1HeHd4Z08tSTdoZkVVQTJsLU9INUdvWnFWMmtfVWU0Z2pnVWZVRzFvYzNlUTEtb1lHMFAtaTkzRTV5Y1dndmJtY0JVZEZlQnp5U1dZcFhpYnRHUjgwamp2R3Fka1UxNXVOYUhDVUhXZDkzZjRfbnlzQ05FVXJKbWNrVU83WExzaVlNM01ua29qc3pmTE1DVi16R082a2NqR0p3VmtXQzZRWjNnM1hPaU1Ta3FTb3FrSHdXZk9QZklxeEFRNXRGU29qd0xuZDduQjNfRER1UXN3cWJhd3gxN2otRjAwYzVvVGV2clR0c1pTUWx4YzRWd1hJRGxSSTJrTVlseHp1MHFpN2xMclBBeUZHd3BfNnh4N0JuajdvTGFfLU1ybDhWQ2UweTQ0aTdxTDlLVk9qRnVGTlAyelhHOTBVakRnZXRLYjFManZ5UFcydENUeUZ3ZVJlWkJuR0RTdnhQVFNRcGhZM1JXMTZIYTRfQV9UbEcybDA0anViTlE2bjJJVWlZRTRFdyJ9", "signature": "WtjQafTZoM8Vei47kImm7JEnDCIPhI6Dv5_u8Hy8IgmuhlscD_vqfaOaKxWpdcS4ChoEg8r2LulLbla01MyFGiRMNSMOnL-7ZvBI17we9z6KCW7a4npGqxXCHNNGXF8kVVCmb9w7uwM0Bj9bxrtU9IjNp065kdU8GxpnLGmD5MEaw6Ved0VASQanvlAMTR0r-NxfwweVYbxo0sa0h0-8Eu9y7MpjE4Ws4WO_SUNsV7cCBLvcWdQ7VJGPRcM7B6JB8_yREjl_K1YzO2vOhcsvaT_67d9mEaDCargL7JYvNLe69CiZ7MFLgdZWBpfBXJ03kEIQGedCWF5u2yVDqjZ5Yw"}'}
2016-03-06 14:40:58,339:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-03-06 14:41:02,253:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-cert HTTP/1.1" 500 88
2016-03-06 14:41:02,255:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '88', 'Expires': 'Sun, 06 Mar 2016 14:41:02 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 06 Mar 2016 14:41:02 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'rbc9HuC4xalYXdbrv_wyckbsHF_4LkDtDSXibrJ5VLE'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new cert","status":500}'
2016-03-06 14:41:02,255:DEBUG:acme.client:Storing nonce: '\xad\xb7=\x1e\xe0\xb8\xc5\xa9X]\xd6\xeb\xbf\xfc2rF\xec\x1c_\xf8.@\xed\r%\xe2n\xb2yT\xb1'
2016-03-06 14:41:02,255:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '88', 'Expires': 'Sun, 06 Mar 2016 14:41:02 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 06 Mar 2016 14:41:02 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'rbc9HuC4xalYXdbrv_wyckbsHF_4LkDtDSXibrJ5VLE'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new cert","status":500}'
2016-03-06 14:41:02,256:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1993, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 707, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 475, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 269, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 252, in obtain_certificate
    return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_certificate_from_csr
    authzr)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 319, in request_issuance
    headers={'Accept': content_type})
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 652, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 568, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert
```

If you need more of the log (which is quite long) tell me.

**Comment by BrainStone** [comment]
Duplicate of #2597

**Comment by Norcy** [comment]
I updated /etc/hosts so that the servername (that didn't have anything to do with these domains) didn't point to 127.0.0.1, I got my cert on the next attempt.

**Comment by iyan31** [comment]
Thanks @Norcy, works for me!
