### ISSUE TITLE
webroot plugin: fatal error when directory cannot be removed

### ISSUE THREAD

**Issue by aburch** [letsencrypt/letsencrypt#2678]
I run the letsencryt as non-root and have created a `${webroot}/.well-known/acme-challenge` directory manually. The letsencrypt user can write in the directory, but cannot remove the directory itself. However it gives a fatal error when it notices this:
```
2016-03-17 10:37:55,303:DEBUG:letsencrypt.plugins.webroot:Removing .../htdocs/.well-known/acme-challenge/...
2016-03-17 10:37:55,304:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 696, in obtain_cert
    certr, chain = le_client.obtain_certificate_from_csr(config.domains, csr, typ)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 225, in obtain_certificate_from_csr
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 84, in get_authorizations
    self._respond(cont_resp, dv_resp, best_effort)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 145, in _respond
    self._cleanup_challenges(active_achalls)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 280, in _cleanup_challenges
    self.dv_auth.cleanup(dv_c)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/webroot.py", line 148, in cleanup
    os.rmdir(root_path)
OSError: [Errno 13] Permission denied: '.../htdocs/.well-known/acme-challenge'
```

The client should probably only try removing the directory if it created it.

I'm using the Debian packages for letsencrypt, version 0.4.1-1~bpo8+1.

**Comment by bmw** [comment]
This was fixed in #2670 and will be included in the 0.5.0 release.
