### ISSUE TITLE
Version Conflict in latest docker image

### ISSUE THREAD

**Issue by ptxmac** [letsencrypt/letsencrypt#2712]
I just pulled the latest docker image today, and I get the following error when I try to run it:

```
# docker run -it --rm --name letsencrypt -p 10080:80 -p 10443:443 -v `pwd`/etc:/etc/letsencrypt -v `pwd`/var:/var/lib/letsencrypt quay.io/letsencrypt/letsencrypt:latest     
Traceback (most recent call last):
  File "/opt/letsencrypt/venv/bin/letsencrypt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/letsencrypt/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/opt/letsencrypt/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 2.2 (/opt/letsencrypt/venv/lib/python2.7/site-packages), Requirement.parse('setuptools>=11.3'))
```

**Comment by bmw** [comment]
Just repoed this issue.

**Comment by pescobar** [comment]
I also had hit problem when following the docs at http://letsencrypt.readthedocs.org/en/latest/using.html#running-with-docker

**Comment by bmw** [comment]
It takes a few minutes for quay.io to update everything, but after that, this should be fixed.

**Comment by ptxmac** [comment]
Works - Thanks!
