### ISSUE TITLE
Oh no! Peep had a problem

### ISSUE THREAD

**Issue by dardan** [letsencrypt/letsencrypt#2742]
Had a problem while downloading and verifying Python packages:
Downloading setuptools==20.2.2 (508K)...

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (3, 1, 1)
python: '2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2]'
pip: '8.1.1'
Command line:  ['/tmp/tmp.iErxA7GbXV/peep.py', 'install', '-r', '/tmp/tmp.iErxA7GbXV/setuptools-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.iErxA7GbXV/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.iErxA7GbXV/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.iErxA7GbXV/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.iErxA7GbXV/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.iErxA7GbXV/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/root/.local/share/letsencrypt/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting

---
root@raspberrypi:/opt/letsencrypt#

**Comment by erikrose** [comment]
#2596 should close this in 0.5.0.
