### ISSUE TITLE
Error with renewal conf files that no longer have a "server" entry

### ISSUE THREAD

**Issue by pde** [letsencrypt/letsencrypt#2750]
I have some renewal conf files that have started erroring since we've cleaned up renewal config entries. Here's one such file:
```
cert = /etc/letsencrypt/live/isnot.org/cert.pem
privkey = /etc/letsencrypt/live/isnot.org/privkey.pem
chain = /etc/letsencrypt/live/isnot.org/chain.pem
fullchain = /etc/letsencrypt/live/isnot.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
apache_enmod = a2enmod
standalone_supported_challenges = "tls-sni-01,http-01"
account = a015e247a80f161ed2a1918624eecadc
apache_handle_modules = True
apache_server_root = /etc/apache2
apache_dismod = a2dismod
apache_handle_sites = True
authenticator = apache
apache_le_vhost_ext = -le-ssl.conf
apache_challenge_location = /etc/apache2
nginx_server_root = /etc/nginx
installer = apache
nginx_ctl = nginx
apache_vhost_root = /etc/apache2/sites-available
```
The error is:
```
2016-04-02 19:31:38,725:WARNING:letsencrypt.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/isnot.org.conf produced an unexpected error: 'server'. Skipping.
2016-04-02 19:31:38,726:DEBUG:letsencrypt.renewal:Traceback was:
Traceback (most recent call last):
  File "/home/ubuntu/letsencrypt/letsencrypt/renewal.py", line 344, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/home/ubuntu/letsencrypt/letsencrypt/main.py", line 513, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/ubuntu/letsencrypt/letsencrypt/main.py", line 90, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/home/ubuntu/letsencrypt/letsencrypt/renewal.py", line 236, in renew_cert
    original_server = lineage.configuration["renewalparams"]["server"]
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'

```

**Comment by pde** [comment]
This should have been caught by integration tests, but probably was not because those set a non-default `server` value.

**Comment by hryamzik** [comment]
I get the same error when running:
```
/root/.local/share/letsencrypt/bin/letsencrypt certonly --webroot --webroot-path /var/www/letsencrypt -d example.org --renew-by-default 
```

And my version is from the 12th of April, 9d7519ca25684b81455696ceea2a22bc94ca8862

**Comment by dandv** [comment]
I still get this error (`KeyError: 'server'`) with 0.4.1, when running `letsencrypt renew`. My config file is:

```
cert = /etc/letsencrypt/live/dandascalescu.com/cert.pem
privkey = /etc/letsencrypt/live/dandascalescu.com/privkey.pem
chain = /etc/letsencrypt/live/dandascalescu.com/chain.pem
fullchain = /etc/letsencrypt/live/dandascalescu.com/fullchain.pem

# Options and defaults used in the renewal process
[renewalparams]
installer = None
authenticator = standalone
account = a9146dfa22d2f6306332af5b3f578e42
standalone_supported_challenges = "http-01,tls-sni-01"
```

`letsencrypt certonly -d dandascalescu.com` produces this error in the log:

```
2016-08-09 05:47:39,068:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-08-09 05:47:39,070:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-08-09 05:47:39,071:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.1
2016-08-09 05:47:39,071:DEBUG:letsencrypt.cli:Arguments: ['-d', 'dandascalescu.com']
2016-08-09 05:47:39,072:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-08-09 05:47:39,078:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2016-08-09 05:47:39,148:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/webroot.py", line 56, in prepare
    "Missing parts of webroot configuration; please set either "
PluginError: Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.
2016-08-09 05:47:39,149:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7f8723186790>
Prep: True
2016-08-09 05:47:39,150:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7f8723186790> and installer None
2016-08-09 05:47:39,170:DEBUG:letsencrypt.cli:Picked account: <Account(a9146dfa22d2f6306332af5b3f578e42)>
2016-08-09 05:47:39,175:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-08-09 05:47:39,179:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-08-09 05:47:39,343:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-08-09 05:47:39,347:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Tue, 09 Aug 2016 05:47:39 GMT', 'Boulder-Request-Id': 'EPWRr4RVfq3kZp0VgnfGmujO979caEWi8c9C6djuDJY', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 09 Aug 2016 05:47:39 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'q4ICK2_t5qoDceAeY-TlEIhZkk86pnOpnqROysBrV1U'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-08-09 05:47:39,347:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Tue, 09 Aug 2016 05:47:39 GMT', 'Boulder-Request-Id': 'EPWRr4RVfq3kZp0VgnfGmujO979caEWi8c9C6djuDJY', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 09 Aug 2016 05:47:39 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'q4ICK2_t5qoDceAeY-TlEIhZkk86pnOpnqROysBrV1U'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-08-09 05:47:39,356:DEBUG:parsedatetime:parse (top of loop): [30 days][]
2016-08-09 05:47:39,366:DEBUG:parsedatetime:CRE_UNITS matched
2016-08-09 05:47:39,367:DEBUG:parsedatetime:parse (bottom) [][30 days][][]
2016-08-09 05:47:39,367:DEBUG:parsedatetime:weekday False, dateStd False, dateStr False, time False, timeStr False, meridian False
2016-08-09 05:47:39,367:DEBUG:parsedatetime:dayStr False, modifier False, modifier2 False, units True, qunits False
2016-08-09 05:47:39,367:DEBUG:parsedatetime:_evalString(30 days, time.struct_time(tm_year=2016, tm_mon=8, tm_mday=9, tm_hour=5, tm_min=47, tm_sec=39, tm_wday=1, tm_yday=222, tm_isdst=0))
2016-08-09 05:47:39,367:DEBUG:parsedatetime:_buildTime: [30 ][][days]
2016-08-09 05:47:39,367:DEBUG:parsedatetime:units days --> realunit days
2016-08-09 05:47:39,368:DEBUG:parsedatetime:return
2016-08-09 05:47:39,368:DEBUG:letsencrypt.storage:Should renew, less than 30 days before certificate expiry 2016-08-07 04:02:00 UTC.
2016-08-09 05:47:39,368:INFO:letsencrypt.cli:Cert is due for renewal, auto-renewing...
2016-08-09 05:47:39,369:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 453, in _auth_from_domains
    original_server = lineage.configuration["renewalparams"]["server"]
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'
```

Adding `-w` doesn't help - I get the same `KeyError: 'server'` error, whether I choose the Webroot or standalone authenticators.

**Comment by bmw** [comment]
@dandv, this problem is caused by taking a configuration file that was created with a newer version of `certbot`/`letsencrypt` (such as the one from `certbot-auto`/`letsencrypt-auto`) and then using it with the version found in Ubuntu 16.04. It can be fixed by appending the line to the end of your renewal config file:
```
server = https://acme-v01.api.letsencrypt.org/directory
```

**Comment by AldeBaranOZ** [comment]
I had the same issue and the @bmw change worked for me. 

One thing though - the `server = ....` needs to go before the `[[webroot_map]]` section in the configuration file.

**Comment by bmw** [comment]
@AldeBaranOZ, nice catch and thanks for clarifying. I updated my post above to reflect that.

**Comment by mcsilver** [comment]
Sounds like the same issue for me but, forgive me: what/where is the "renewal config file"?

**Comment by bmw** [comment]
@mcsilver, good question! I edited my post above, but the "renewal config files" are found in `/etc/letsencrypt/renewal`.

**Comment by mcsilver** [comment]
Thanks!  That worked.

**Comment by pajasevi** [comment]
Thank you guys, it worked! This is a nightmare...

**Comment by robfrancken** [comment]
Thank you @bmw and @AldeBaranOZ, you saved my day :)
