### ISSUE TITLE
Peep Error

### ISSUE THREAD

**Issue by dragonsvape** [letsencrypt/letsencrypt#2765]
Not sure why but this error has just started happening today

`peep: (3, 1, 1)
python: '2.7.11 (default, Dec  7 2015, 11:26:11) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.o3YNWqq6tk/peep.py', 'install', '-r', '/tmp/tmp.o3YNWqq6tk/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.o3YNWqq6tk/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.o3YNWqq6tk/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.o3YNWqq6tk/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.o3YNWqq6tk/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.o3YNWqq6tk/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal not in range(128)
`
It was working for 3 days and I am now getting this, any ideas why this is happening?

**Comment by bmw** [comment]
This is a known problem with `peep`, however, `peep` has been removed from `letsencrypt-auto` and this change will be pushed to our users in the next release coming in the next 24 hours or so.
