### ISSUE TITLE
DNS Issue While Registering For New Cert

### ISSUE THREAD

**Issue by richardwlu** [letsencrypt/letsencrypt#2777]
I'm running this for the first time and am receiving errors when entering my gmail.com email address. For one of them containing a `.` it would just error out and suggest to use `--register-unsafely-without-email`. I tried with another gmail account without a `.` and it brought me to the TOS agreement page but then was given another error. 

Logs give:

```
The provided email for a registration was invalid :: DNS problem: query timed out looking up MX for gmail.com
Please see the logfiles in /var/log/letsencrypt for more details.
root@lurichard:/opt/letsencrypt# tail /var/log/letsencrypt/letsencrypt.log
letsencrypt.log    letsencrypt.log.1  letsencrypt.log.2
root@lurichard:/opt/letsencrypt# tail /var/log/letsencrypt/letsencrypt.log
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 137, in update_registration
    regr, body=messages.UpdateRegistration(**dict(update)))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 112, in _send_recv_regr
    response = self.net.post(regr.uri, body)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 652, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 568, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:invalidEmail :: The provided email for a registration was invalid :: DNS problem: query timed out looking up MX for gmail.com
```

I am open to suggestions. Currently on a DigitalOcean server running Ubuntu 14.04 for nginx.

**Comment by bmw** [comment]
The Let's Encrypt server is having DNS issues at the moment [source](https://letsencrypt.status.io/). You should try running the client again when these issues are resolved.

**Comment by richardwlu** [comment]
@bmw Thank you for your response! I gave it another run and I got one step further. The issue I'm having now is:

```
root@lurichard:/opt/letsencrypt# !345
./letsencrypt-auto --config /etc/letsencrypt/configs/lurichard.com.conf certonly --verbose
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt --config /etc/letsencrypt/configs/lurichard.com.conf certonly --verbose
2016-04-07 15:00:46,725:INFO:letsencrypt.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-04-07 15:00:47,151:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:47,520:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:47,645:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:47,880:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:48,214:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:48,466:INFO:letsencrypt.auth_handler:Performing the following challenges:
2016-04-07 15:00:48,467:INFO:letsencrypt.auth_handler:http-01 challenge for lurichard.com
2016-04-07 15:00:48,467:INFO:letsencrypt.auth_handler:http-01 challenge for www.lurichard.com
2016-04-07 15:00:48,468:INFO:letsencrypt.auth_handler:http-01 challenge for ts.lurichard.com
2016-04-07 15:00:48,469:INFO:letsencrypt.plugins.webroot:Using the webroot path /var/www/lurichard.com/howlong for all unmatched domains.
2016-04-07 15:00:48,502:INFO:letsencrypt.auth_handler:Waiting for verification...
2016-04-07 15:00:48,519:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:48,743:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:49,031:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:52,209:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:52,424:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:52,671:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-04-07 15:00:52,815:INFO:letsencrypt.reporter:Reporting to user: The following errors were reported by the server:

Domain: www.lurichard.com
Type:   connection
Detail: DNS problem: NXDOMAIN looking up A for www.lurichard.com

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2016-04-07 15:00:52,816:INFO:letsencrypt.auth_handler:Cleaning up challenges
Failed authorization procedure. www.lurichard.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for www.lurichard.com

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.lurichard.com
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for www.lurichard.com

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

I issued `curl lurichard.com` from my local and the results look fine.

An `nslookup` shows the proper ip address of my server.
```
nslookup lurichard.com
Server:		10.200.5.101
Address:	10.200.5.101#53

Non-authoritative answer:
Name:	lurichard.com
Address: 104.131.58.197
```

and the webroot-path to the `/.well-known/acme-challenge/` file should be serving since I threw a `test.txt` file in `/.well-known/acme-challenge/` and it is currently serving.

No issues with firewall as 80/tcp is open.

Would you happen to have any suggestions here to help me debug and move forward?

**Comment by bmw** [comment]
So the problem here is there is there doesn't appear to be a DNS A record for `www.lurichard.com` which is one of the domains you requested in your config file.

```
$ nslookup www.lurichard.com
Server:		75.75.75.75
Address:	75.75.75.75#53

** server can't find www.lurichard.com: NXDOMAIN
```

**Comment by richardwlu** [comment]
@bmw That was a noobie mistake on my part. Now I know I need to create an A record with 'www` for my domains. Thank you for your help!

**Comment by vhp1360** [comment]
Hello guys,
I've had this issue too.
I got same messages:
>Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for officeapps.shomar.com
nginx:[warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/.../officeapps.shomar.com.crt"
nginx:[warn] "ssl_stapling" ignored,no OCSP responder URL in the certificate "/.../officeapps.shomar.com.crt"
Waiting for verification...
Cleaning up challenges
nginx:[warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/.../officeapps.shomar.com.crt"
nginx:[warn] "ssl_stapling" ignored,no OCSP responder URL in the certificate "/.../officeapps.shomar.com.crt"
Failed authorization procedure. officeapps.shomar.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for officeapps.shomar.com
>
>IMPORTANT NOTES:
 - The following errors were reported by the server:
>
  > Domain: officeapps.shomar.com
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for
   officeapps.shomar.com
>
>   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.

actually, on Centos7 Server I setup DNS, _officeapps.shomar.com_ point to own ,
`dig officeapps.shomar.com`:
>; <<>> DiG 9.9.4-RedHat-9.9.4-51.el7 <<>> officeapps.shomar.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18554
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 2
>
>;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;officeapps.shomar.com.         IN      A
>
>;; ANSWER SECTION:
officeapps.shomar.com.  86400   IN      A       bbb.bbb.bbb.bbb
officeapps.shomar.com.  86400   IN      A       aaa.aaa.aaa
>
>;; AUTHORITY SECTION:
officeapps.shomar.com.  86400   IN      NS      officeapps.shomar.com.
officeapps.shomar.com.  86400   IN      NS      root.officeapps.shomar.com.
>
>;; ADDITIONAL SECTION:
root.officeapps.shomar.com. 86400 IN    A       bbb.bbb.bbb.bbb
>
>;; Query time: 1 msec
;; SERVER: bbb.bbb.bbb.bbb#53(bbb.bbb.bbb.bbb)
;; WHEN: Wed Oct 25 09:30:17 +0330 2017
;; MSG SIZE  rcvd: 131

that __bbb.bbb.bbb.bbb__ is this server PublicIP.
`nslookup officeapps.shomar.com`
>Server:         bbb.bbb.bbb.bbb
Address:        bbb.bbb.bbb.bbb#53
>
>Name:   officeapps.shomar.com
Address: bbb.bbb.bbb.bbb
Name:   officeapps.shomar.com
Address: aaa.aaa.aaa.aaa

why I need valid certificate?
I tried to setup [SandStorm](https://sandstorm.io/) solution in my private lan, Server IP is public but _officeapps.shomar.com_ isn't public.
AnySubDomain of _officeapps.shomar.com_ should be accessible that solved by DNS(those setup on the saerver), SandStorm use _`iframe`_ and according this [answer](https://github.com/sandstorm-io/sandstorm/issues/2986#issuecomment-338444440)existing Broswers couldn't trust invalid(Self-Signed) certificate for that, therefor I'm gonna use your solution.
Could you please help me?

Thanks.

**Comment by vhp1360** [comment]
any update, please.

**Comment by bmw** [comment]
Are you using a server other than Let's Encrypt?

**Comment by vhp1360** [comment]
Sorry, I couldn't get you correct, but I follow the instruction.

**Comment by bmw** [comment]
Can you provide a full log from `/var/log/letsencrypt` showing the problem?

**Comment by vhp1360** [comment]
thanks for replay:
>2017-10-25 06:00:50,682:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:
>
>Domain: officeapps.shomar.com
Type:   connection
Detail: DNS problem: NXDOMAIN looking up A for officeapps.shomar.com
>
>To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2017-10-25 06:00:50,683:INFO:certbot.auth_handler:Cleaning up challenges
2017-10-25 06:00:52,389:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.18.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 755, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 606, in run
    certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 82, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 202, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. officeapps.shomar.com (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for officeapps.shomar.com

**Comment by vhp1360** [comment]
any update, please.
