### ISSUE TITLE
"Enter a new webroot" fails

### ISSUE THREAD

**Issue by strk** [letsencrypt/letsencrypt#2787]
- Run with "certonly",
- select "1  Place files in webroot directory (webroot)"
- enter domain name
- No webroot for given domain name is given, so dialog only shows a single entry "1 Enter a new webroot"
- Click OK on the only option

Expected result: get prompted for a webroot
Obtained result: 
```
An unexpected error occurred:
DialogError
Please see the logfiles in /var/log/letsencrypt for more details.
```

Happens as of 6a7b4a8e142eb392a8fe696d9536b52c0fc4b5e3 on a Debian GNU/Linux 8.3 (jessie)

**Comment by bmw** [comment]
Do you have the logfile from this run? As stated by the output, it should be in `/var/log/letsencrypt`.

**Comment by strk** [comment]
Is this snippet enough of it ?

```
6-04-08 10:14:39,243:INFO:letsencrypt.auth_handler:http-01 challenge for xxx.xxx.xxx
2016-04-08 10:15:15,444:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 72, in perform
    self._set_webroots(achalls)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 90, in _set_webroots
    known_webroots)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 107, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 141, in _prompt_for_new_webroot
    "Input the webroot for {0}:".format(domain))
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/display/util.py", line 198, in directory_select
    height=self.height, help_button=True, title=message)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 2407, in dselect
    kwargs, raw_help=True)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/home/strk/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1454, in _wait_for_program_termination
    child_output.strip()))
DialogError
```

**Comment by bmw** [comment]
Looking at the Python dialog source code, this is the error message thrown at that location:

> the dialog-like program exited with status {0} (which was passed to it as the DIALOG_ERROR environment variable). Sometimes, the reason is simply that dialog was given a height or width parameter that is too big for the terminal in use. Its output, with leading and trailing whitespace stripped, was:\n\n{1}

Is it possible your terminal window was very small when you got this error? `letsencrypt` always requests a dialog window that is 24 characters tall and 80 characters wide.

**Comment by strk** [comment]
It could be, yes, that my terminal was having less than 80 cols.
I'm also noticing that the terminal I'm using these days doesn't even fix the COLUMNS env variable as I make fonts larger/smaller, so maybe that also affects it.

I don't have a way to reproduce now though.

**Comment by bmw** [comment]
Okay. I'm going to assume that's the problem and I made #2812 and #2813 to track the issues of small terminals and poor error messages respectively.

If you have the problem again and have reason to believe it's due to something else, please make a new issue or comment here and I'll reopen. Thanks for reporting the problem!

**Comment by axfelix** [comment]
I'm hitting this issue with identical logs on Ubuntu 14.04 + nginx, and my terminal is larger than 80x24. Could it be because I'm running it as root?

**Comment by axfelix** [comment]
Nope. Just made a user account on this system to test and getting the same error. This is just bash over ssh to DigitalOcean, fwiw ... I could try to export some more terminal variables to trick it if you think that's the issue?

**Comment by axfelix** [comment]
Going to 132x43 seemed to fix it.

**Comment by bmw** [comment]
Since enlarging your window seemed to fix the problem, it might be the same issue, however, the size 72 x 24 is [hard coded](https://github.com/certbot/certbot/blob/master/certbot/display/util.py#L12) in the client this is a little strange (I was incorrect before when I said 80 x 24 and I have edited my post above).

Resolving #2813 should help so we stop losing potentially helpful error messages from dialog.

**Comment by iquidus** [comment]
also countered this issue. increasing the size of my terminal as suggested works like a charm.

**Comment by karlsebal** [comment]
I think a proper error message would be nice :)

**Comment by bmw** [comment]
@karlsebal, a fix to display the NCurses error message to the user has landed in master and will be in our next release.

**Comment by Committing** [comment]
I made my terminal taller but I still cannot work out how to enter my webroot
https://i.gyazo.com/f8b50887288ee0fa3e3822653ce48846.png

**Comment by Committing** [comment]
Making my terminal bigger worked. Thanks
