### ISSUE TITLE
KeyError: 'server'

### ISSUE THREAD

**Issue by hryamzik** [letsencrypt/letsencrypt#2842]
```
2016-04-14 04:14:01,645:INFO:letsencrypt.cli:Auto-renewal forced with --force-renewal...
2016-04-14 04:14:01,645:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1993, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 707, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 454, in _auth_from_domains
    original_server = lineage.configuration["renewalparams"]["server"]
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'server'
```

I get this error when running:
```
/root/.local/share/letsencrypt/bin/letsencrypt certonly --webroot --webroot-path /var/www/letsencrypt -d example.org --renew-by-default 
```

My version is 9d7519ca25684b81455696ceea2a22bc94ca8862

**Comment by bmw** [comment]
If you look in your `letsencrypt` configuration directory (which is in `/etc/letsencrypt` by default), you should see a directory named `renewal`. In that directory, you should see a file `example.com.conf`. Can you post the contents of this file? Feel free to redact whatever values you'd like.

**Comment by hryamzik** [comment]
Here you are:

```
cert = /etc/letsencrypt/live/example.org/cert.pem
privkey = /etc/letsencrypt/live/example.org/privkey.pem
chain = /etc/letsencrypt/live/example.org/chain.pem
fullchain = /etc/letsencrypt/live/example.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = webroot
installer = None
account = ***************
webroot_path = /var/www/letsencrypt,
[[webroot_map]]
example.org = /var/www/letsencrypt
```

**Comment by bmw** [comment]
It looks like you're still on an old release of `letsencrypt`. If you run `letsencrypt-auto` again, you'll be updated a newer version which does not suffer from this problem.

**Comment by hryamzik** [comment]
Yep, update and change ```/root/.local/share/letsencrypt/bin/letsencrypt``` to ```/opt/letsencrypt/letsencrypt-auto``` fixed the issue. Thanks!
