### ISSUE TITLE
Exception when expanding an existing certificate

### ISSUE THREAD

**Issue by micwic** [letsencrypt/letsencrypt#2903]
Letsencrypt is exiting abnormally when expanding an existing certificate by adding a new domain name with command 

```
./letsencrypt-auto certonly --standalone -d os-vps276.projet-okinawa.org -d confluence.projet-okinawa.ch -d jira.projet-okinawa.ch -d openam.projet-okinawa.ch -d repo.projet-okinawa.ch -d www.projet-okinawa.ch -d www.blonay-lecentre.ch
Checking for new version...
Requesting root privileges to run letsencrypt...
   sudo /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --test-cert -d os-vps276.projet-okinawa.org -d confluence.projet-okinawa.ch -d jira.projet-okinawa.ch -d openam.projet-okinawa.ch -d repo.projet-okinawa.ch -d www.projet-okinawa.ch -d www.blonay-lecentre.ch
```

2016-04-29 13:43:28,473:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 90, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/renewal.py", line 241, in renew_cert
    prior_version = lineage.latest_common_version()
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 513, in latest_common_version
    return max(n for n in versions[0] if all(n in v for v in versions[1:]))
ValueError: max() arg is an empty sequence

**Comment by micwic** [comment]
ubuntu@os-vps276:/opt/letsencrypt$ ./letsencrypt-auto --version
Checking for new version...
Requesting root privileges to run letsencrypt...
   sudo /home/ubuntu/.local/share/letsencrypt/bin/letsencrypt --version
letsencrypt 0.5.0

**Comment by micwic** [comment]
[letsencrypt.log.zip](https://github.com/letsencrypt/letsencrypt/files/242600/letsencrypt.log.zip)

**Comment by bmw** [comment]
Any thoughts @schoen?

**Comment by schoen** [comment]
@bmw, discussed at https://community.letsencrypt.org/t/got-an-exception-when-expanding-an-existing-certificate/15123 (this was due to manually modifying stuff within `/etc/letsencrypt`; @micwic has now successfully solved it by adjusting the links and renewal configuration).

I'm filing a new issue on giving a useful error message in this case, though (#2918).
