### ISSUE TITLE
StandaloneAuthenticator process not shut down correctly

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#365]
```
# letsencrypt -ted "asd12345.pl"
INFO:root:Performing the following challenges:
INFO:root:  DVSNI challenge for asd12345.pl.
INFO:root:Waiting for verification...
Traceback (most recent call last):
  File "/root/lets-encrypt-preview/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/root/lets-encrypt-preview/letsencrypt/scripts/main.py", line 229, in main
    cert_file, chain_file = acme.obtain_certificate(doms)
  File "/root/lets-encrypt-preview/letsencrypt/client/client.py", line 122, in obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 79, in get_authorizations
    self._respond(cont_resp, dv_resp, best_effort)
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 137, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 187, in _poll_challenges
    "Failed Authorization procedure for %s" % domain)
letsencrypt.client.errors.AuthorizationError: Failed Authorization procedure for asd12345.pl
# letsencrypt -ted "asd12345.pl"
INFO:root:Performing the following challenges:
INFO:root:  DVSNI challenge for asd12345.pl.

-------------------------------------------------------------------------------
The program letsencrypt (process ID 6081) is already listening on TCP port 443.
This will prevent us from binding to that port. Please stop the letsencrypt
program temporarily and then try again.
-------------------------------------------------------------------------------
Press Enter to Continue
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
Traceback (most recent call last):
  File "/root/lets-encrypt-preview/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/root/lets-encrypt-preview/letsencrypt/scripts/main.py", line 229, in main
    cert_file, chain_file = acme.obtain_certificate(doms)
  File "/root/lets-encrypt-preview/letsencrypt/client/client.py", line 122, in obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 75, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 109, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/root/lets-encrypt-preview/letsencrypt/client/plugins/standalone/authenticator.py", line 345, in perform
    raise ValueError(".perform() was called with pending tasks!")
ValueError: .perform() was called with pending tasks!
```

looks like another argument for threads over forks

**Comment by schoen** [comment]
Apart from making the client not crash, we should probably detect when the conflicting listener is a process that's already exited (where we're just waiting for socket reuse). The advice to stop the other program doesn't make sense when the other program is no longer running.

**Comment by bmw** [comment]
I tried to recreate this locally and was unable to do so. @kuba, if this is still an issue, please reopen.
