### ISSUE TITLE
ApacheConfigurator infinite loop

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#377]
Just did `apt-get install apache` on fresh box (no configuration or whatsover) and am getting the following error
```
(venv)root@le:~/lets-encrypt-preview# letsencrypt -t

-------------------------------------------------------------------------------
This is a PREVIEW RELEASE of a client application for the Let's Encrypt
certificate authority and other services using the ACME protocol. The Let's
Encrypt certificate authority is NOT YET ISSUING CERTIFICATES TO THE PUBLIC.

Until publicly-trusted certificates can be issued by Let's Encrypt, this
software CANNOT OBTAIN A PUBLICLY-TRUSTED CERTIFICATE FOR YOUR WEB SERVER.  You
should only use this program if you are a developer interested in experimenting
with the ACME protocol or in helping to improve this software.  If you want to
configure your web site with HTTPS in the meantime, please obtain a certificate
from a different authority.

For updates on the status of Let's Encrypt, please visit the Let's Encrypt home
page at https://letsencrypt.org/.
-------------------------------------------------------------------------------
(A)gree/(C)ancel: A

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Apache Web Server
2: Standalone Authenticator
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1

-------------------------------------------------------------------------------
No names were found in your configuration files.
You should specify ServerNames in your config files in order to allow for
accurate installation of your certificate.
If you do use the default vhost, you may specify the name manually. Would you
like to continue?
-------------------------------------------------------------------------------
(Y)es/(N)o: Y
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel):foo.com
INFO:root:Generating key (2048 bits): /etc/letsencrypt/keys/0000_key-letsencrypt.pem
INFO:root:Performing the following challenges:
INFO:root:  DVSNI challenge for foo.com.
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
Traceback (most recent call last):
  File "/root/lets-encrypt-preview/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/root/lets-encrypt-preview/letsencrypt/scripts/main.py", line 220, in main
    cert_file, chain_file = acme.obtain_certificate(doms)
  File "/root/lets-encrypt-preview/letsencrypt/client/client.py", line 93, in obtain_certificate
    self.auth_handler.get_authorizations()
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 89, in get_authorizations
    self._satisfy_challenges()
  File "/root/lets-encrypt-preview/letsencrypt/client/auth_handler.py", line 170, in _satisfy_challenges
    dv_resp = self.dv_auth.perform(flat_dv)
  File "/root/lets-encrypt-preview/letsencrypt/client/plugins/apache/configurator.py", line 1016, in perform
    for i, resp in enumerate(sni_response):
TypeError: 'NoneType' object is not iterable
```

**Comment by jdkasten** [comment]
Yes.... this has also been fixed.

**Comment by jdkasten** [comment]
I will try to make a stop-gap PR...

**Comment by jdkasten** [comment]
I was working on Apache when I was interrupted with a partial recovery_contact PR and was transferred responsibility of handling boulder integration.

**Comment by kuba** [comment]
Hmm, the output I pasted above smells like pre-boulder (EULA first), doesn't it? The current master goes into infinite loop:

```
# echo 1 | letsencrypt -ted foo.com 2>&1 | head -n 50
INFO:root:Performing the following challenges:
INFO:root:  DVSNI challenge for foo.com.
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
INFO:root:Waiting for verification...
INFO:root:Cleaning up challenges
ERROR:root:No vhost exists with servername or alias of: foo.com
ERROR:root:No _default_:443 vhost exists
ERROR:root:Please specify servernames in the Apache config
...
```

I guess you fixed this as well, didn't you?

Also, `choose_names` might return `None` which is not respected by `deploy_cert` and when `vhost.path` is attempted... bum!
