### ISSUE TITLE
builds but fails to run @fedora 22u

### ISSUE THREAD

**Issue by lejeczek** [letsencrypt/letsencrypt#493]
./venv/bin/letsencrypt --help
Traceback (most recent call last):
  File "./venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/letsencrypt/cli.py", line 16, in <module>
    from letsencrypt import account
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/letsencrypt/account.py", line 9, in <module>
    from acme import messages2
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/acme/messages2.py", line 2, in <module>
    from acme import challenges
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/acme/challenges.py", line 8, in <module>
    from acme import jose
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/acme/jose/__init__.py", line 39, in <module>
    from acme.jose.json_util import (
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/acme/jose/json_util.py", line 13, in <module>
    import M2Crypto
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/M2Crypto/__init__.py", line 24, in <module>
    import ASN1
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 12, in <module>
    import BIO
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 221, in <module>
    class CipherStream(BIO):
  File "/home/pe243/rpmbuild/git.src/lets-encrypt-preview/venv/lib/python2.7/site-packages/M2Crypto/BIO.py", line 227, in CipherStream
    SALT_LEN = m2.PKCS5_SALT_LEN
AttributeError: 'module' object has no attribute 'PKCS5_SALT_LEN'

**Comment by kuba** [comment]
@lejeczek, could you please test #494?

**Comment by jdkasten** [comment]
Since we removed M2Crypto from the project, this specific error should no longer be a problem.
