### ISSUE TITLE
Server POST response did not include a replay nonce

### ISSUE THREAD

**Issue by jonathannoah** [letsencrypt/letsencrypt#521]
The issue I was having at #503 (`Error creating new authz`) looks to be resolved, but now every time I try to run letsencrypt, I get the following:

    $ sudo ./venv/bin/letsencrypt -d jn1.me auth
    Traceback (most recent call last):
          File "./venv/bin/letsencrypt", line 9, in <module>
            load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 406, in main
            return args.func(args, config, plugins)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 133, in auth
            plugins):
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/client.py", line 206, in obtain_and_enroll_certificate
            cert, privkey, chain = self.obtain_certificate(domains, csr)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/client.py", line 154, in obtain_certificate
            authzr = self.auth_handler.get_authorizations(domains)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 69, in get_authorizations
            domain, self.account.new_authzr_uri)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/network2.py", line 333, in request_domain_challenges
            typ=messages2.IDENTIFIER_FQDN, value=domain), new_authz_uri)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/network2.py", line 314, in request_challenges
            response = self._post(new_authzr_uri, new_authz)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/network2.py", line 178, in _post
            self._add_nonce(response)
          File "/home/deploy/lets-encrypt-preview/venv/local/lib/python2.7/site-packages/letsencrypt/network2.py", line 149, in _add_nonce
            response.request.method))
        letsencrypt.errors.NetworkError: Server POST response did not include a replay nonce

Deleting my `/etc/letsencrypt/accounts/` doesn't help, nor does removing and reinstalling letsencrypt. I noticed that the response to `dig jn1.me -t TYPE257 @lucy.ns.cloudflare.com` is the same "REFUSED" status as before; could that be the reason?

**Comment by davidar** [comment]
I'm seeing the same problem.

**Comment by kuba** [comment]
Are you running latest master, i.e. https://github.com/letsencrypt/lets-encrypt-preview/commit/99ff33e581ffa98c2405ceb03d56cff65de3ee10?

**Comment by davidar** [comment]
Yes.

**Comment by kuba** [comment]
There are 2 problems:
1. Server is currently broken, see https://github.com/letsencrypt/lets-encrypt-preview/issues/503#issuecomment-113769708. @jcjones, @jsha PTAL
2. Client tries to retrieve the nonce without noticing HTTP `500` error code first. I will fix this bug today.

Thanks for all reports. Managed to pin it down thanks to @GabLeRoux. To anyone else, next time please join #letsencrypt@Freenode to aid in debugging and in order to get quicker help. :)

**Comment by jonathannoah** [comment]
Is the server still broken? I receive the same "Maintenance Time" response as @GabLeRoux's [#503 comment](https://github.com/letsencrypt/lets-encrypt-preview/issues/503#issuecomment-113769708) when I run with -vvvvvv.

I'm Joe5150 in IRC, btw, so you can chat with me there if you need my help.

**Comment by kuba** [comment]
@davidar Are you using CloudFlare DNS as well?

For everyone using CloudFlare: https://github.com/letsencrypt/boulder/issues/391

**Comment by davidar** [comment]
@kuba Yes. Thanks, I'll follow that bug.

**Comment by GabLeRoux** [comment]
I confirm I am not getting this error message anymore (showing #503 again, but that's probably normal) Thanks :)

**Comment by Shadok** [comment]
Sorry to reopen that case but i'm not using CloudFlare and i'm getting this error (i just cloned the repository, i was still using the old letsencrypt client before, so i'm up-to-date).

```
2016-05-16 10:01:11,992:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-05-16 10:01:11,995:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2016-05-16 10:01:11,999:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x7fea23234050>
Prep: True
2016-05-16 10:01:12,000:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x7fea23234050> and installer None
2016-05-16 10:01:12,020:DEBUG:certbot.main:Picked account: <Account(b56df047775afaaa30793681b6814f7a)>
2016-05-16 10:01:12,021:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-05-16 10:01:12,024:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-16 10:01:12,308:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-05-16 10:01:12,309:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Mon, 16 May 2016 10:01:27 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 16 May 2016 10:01:27 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'puBQFbC5S2vJZTbj2ksTq8ny-rt3Sk9HT7yM37Ungw4'}.
Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-16 10:01:12,309:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Mon, 16 May 2016 10:01:27 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection':'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 16 May 2016 10:01:27 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'puBQFbC5S2vJZTbj2ksTq8ny-rt3Sk9HT7yM37Ungw4'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-16 10:01:12,325:DEBUG:root:Requesting fresh nonce
2016-05-16 10:01:12,325:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2016-05-16 10:01:12,326:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-16 10:01:49,254:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 503 0
2016-05-16 10:01:49,255:DEBUG:root:Received <Response [503]>. Headers: {'Content-Length': '175', 'Expires': 'Mon, 16 May 2016 10:02:04 GMT', 'Server': 'AkamaiGHost', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 16 May 2016 10:02:04 GMT', 'Content-Type': 'text/html', 'Mime-Version': '1.0'}. Content: ''2016-05-16 10:01:49,256:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 90, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 236, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 246, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 64, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 217, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 197, in request_challenges
    new_authz)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 649, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 644, in _get_nonce
    self._add_nonce(self.head(url))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 639, in _add_nonce
    raise errors.MissingNonce(response)
MissingNonce: Server HEAD response did not include a replay nonce, headers: {'Content-Length': '175', 'Expires': 'Mon, 16 May 2016 10:02:04 GMT', 'Server': 'AkamaiGHost', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 16 May 2016 10:02:04 GMT', 'Content-Type': 'text/html', 'Mime-Version': '1.0'}
```

**Comment by Shadok** [comment]
It worked on the second try.

**Comment by jsha** [comment]
@kuba: Looks like you had a fix for this going (https://github.com/kuba/letsencrypt/commit/04e934089e24b95b0ea96530af8da54ddaa651cb), but it doesn't appear to be merged. Could you finish it up and post for review?
