### ISSUE TITLE
Flaky Travis: failed to create new OS thread

### ISSUE THREAD

**Issue by kuba** [letsencrypt/letsencrypt#712]
After switching to Go 1.5 (#709), integration tests became flaky. They randomly throw:

```
started go install ./cmd/boulder-wfe && exec boulder-wfe --config test/boulder-config.json with pid 14816
started go install ./cmd/boulder-ra && exec boulder-ra --config test/boulder-config.json with pid 14818
started go install ./cmd/boulder-sa && exec boulder-sa --config test/boulder-config.json with pid 14824
started go install ./cmd/boulder-ca && exec boulder-ca --config test/boulder-config.json with pid 14830
started go install ./cmd/boulder-va && exec boulder-va --config test/boulder-config.json with pid 14838
started go install ./cmd/ocsp-responder && exec ocsp-responder --config test/boulder-config.json with pid 14845
started go install ./test/dns-test-srv && exec dns-test-srv --config test/boulder-config.json with pid 14852
Waiting for debug port 8000
[1mpy27 create: /home/travis/build/letsencrypt/letsencrypt/.tox/py27[0m
Waiting for debug port 8000
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/cloudflare/cfssl/crypto/pkcs7
runtime: failed to create new OS thread (have 13 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc820512900, 0xc8204bdfc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.systemstack(0xc80c20)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1173 +0x672 fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
fmt.(*pp).printArg(0xc820305c70, 0x790a00, 0xc820717020, 0x76, 0x0, 0x76)
	/usr/local/go/src/fmt/print.go:738
fmt.(*pp).handleMethods(0xc820305c70, 0xc800000076, 0x0, 0x7cae01)
	/usr/local/go/src/fmt/print.go:730 +0x6b4
fmt.(*pp).printArg(0xc820305c70, 0x7caec0, 0xc82032b180, 0x76, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:806 +0x4a5
fmt.(*pp).doPrintf(0xc820305c70, 0x80f260, 0x3, 0xc82072e780, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1219 +0x1dd8
fmt.Sprintf(0x80f260, 0x3, 0xc82072e780, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:203 +0x6f
cmd/compile/internal/gc.typefmt(0xc820406d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/fmt.go:549 +0xa2d
cmd/compile/internal/gc.Tconv(0xc820406d20, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/fmt.go:1636 +0x11c
cmd/compile/internal/gc.(*Type).String(0xc820406d20, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/fmt.go:1607 +0x36
fmt.(*pp).handleMethods(0xc820305ad0, 0xc800000076, 0x0, 0xc82071ac01)
	/usr/local/go/src/fmt/print.go:730 +0x633
fmt.(*pp).printArg(0xc820305ad0, 0x7caec0, 0xc820406d20, 0x76, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:806 +0x4a5
fmt.(*pp).doPrintf(0xc820305ad0, 0x8146b0, 0x4, 0xc82072f038, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1219 +0x1dd8
fmt.Sprintf(0x8146b0, 0x4, 0xc82072f038, 0x1, 0x1, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:203 +0x6f
cmd/compile/internal/gc.typefmt(0xc820406c40, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/fmt.go:558 +0x14b3
cmd/compile/internal/gc.Tconv(0xc820406c40, 0x0, 0x0, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/fmt.go:1636 +0x11c
cmd/compile/internal/gc.typelinksym(0xc820406c40, 0xa00000050)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:901 +0x6d
cmd/compile/internal/gc.dtypesym(0xc820406c40, 0xc820493180)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1273 +0x392
cmd/compile/internal/gc.dtypesym(0xc8204067e0, 0xc820493000)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1215 +0xc79
cmd/compile/internal/gc.dtypesym(0xc820406380, 0xc820493100)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1215 +0xc79
cmd/compile/internal/gc.dtypesym(0xc820405ea0, 0xc820399480)
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1215 +0xc79
cmd/compile/internal/gc.dumptypestructs()
	/usr/local/go/src/cmd/compile/internal/gc/reflect.go:1302 +0x435
cmd/compile/internal/gc.dumpobj()
	/usr/local/go/src/cmd/compile/internal/gc/obj.go:81 +0xd86
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:492 +0x1fb5
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/letsencrypt/go-jose
runtime: failed to create new OS thread (have 9 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82050a480, 0xc82006ffc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.systemstack(0xc820028000)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1173 +0x672 fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.Nod(0x1, 0x0, 0x0, 0x7eb900)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:385 +0xdd
cmd/compile/internal/gc.newname(0xc8201f7100, 0x0)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:372 +0x6c
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82005c048, 0x7f7923e90728, 0xda67e0, 0x0)
	go.y:2156 +0x178e2
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/cloudflare/cfssl/crypto/pkcs12
runtime: failed to create new OS thread (have 14 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc820622d80, 0xc8205effc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.systemstack(0xc820618640)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1173 +0x672 fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.yylex1(0x7f6362919728, 0xda67e0, 0xc820013780, 0x3b, 0x3f)
	yaccpar:118
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82005c0a0, 0x7f6362919728, 0xda67e0, 0x0)
	yaccpar:206 +0x1a9c3
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/cloudflare/cfssl/crypto/pkcs12
runtime: failed to create new OS thread (have 6 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc8200b4480, 0xc8200c7fc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.gc.func1()
	/usr/local/go/src/runtime/mgc.go:991 +0x95
runtime.systemstack(0xc80c20)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1005 +0x1db fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.parserline(0xc820624008)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:36
cmd/compile/internal/gc.Nod(0x1, 0x0, 0x0, 0x5dfd11)
	/usr/local/go/src/cmd/compile/internal/gc/subr.go:377 +0x74
cmd/compile/internal/gc.newname(0xc82030b080, 0x1)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:372 +0x6c
cmd/compile/internal/gc.addmethod(0xc82030b080, 0xc820621420, 0xc820600000)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1429 +0xb3e
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82005c0a0, 0x7fdd50a2e728, 0xda67e0, 0x0)
	go.y:1501 +0xfa96
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/letsencrypt/go-jose
runtime: failed to create new OS thread (have 13 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82069e900, 0xc820315fc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.gc.func1()
	/usr/local/go/src/runtime/mgc.go:991 +0x95
runtime.systemstack(0xc820032a00)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1005 +0x1db fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
cmd/compile/internal/gc.typenod(0xc820985260, 0xc8200c4ca8)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:400
cmd/compile/internal/gc.(*yyParserImpl).Parse(0xc82005c050, 0x7f42a07eb728, 0xda67e0, 0x0)
	go.y:2154 +0x17847
cmd/compile/internal/gc.yyparse()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:1854 +0xb4
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:348 +0x1b6f
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/streadway/amqp
runtime: failed to create new OS thread (have 18 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc820088d80, 0xc82068bfc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.gc.func1()
	/usr/local/go/src/runtime/mgc.go:991 +0x95
runtime.systemstack(0xc82066e4c0)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1005 +0x1db fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [running]:
	goroutine running on other thread; stack unavailable
# github.com/letsencrypt/boulder/Godeps/_workspace/src/gopkg.in/gorp.v1
runtime: failed to create new OS thread (have 19 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82120e900, 0xc82121dfc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b6b8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.startTheWorldWithSema()
	/usr/local/go/src/runtime/proc1.go:664 +0x1fc
runtime.systemstack(0xc820031500)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820059c98 sp=0xc820059c90
runtime.gc(0x0)
	/usr/local/go/src/runtime/mgc.go:1173 +0x672 fp=0xc820059f90 sp=0xc820059c98
runtime.backgroundgc()
	/usr/local/go/src/runtime/mgc.go:896 +0x3d fp=0xc820059fc0 sp=0xc820059f90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820059fc8 sp=0xc820059fc0
created by runtime.startGC
	/usr/local/go/src/runtime/mgc.go:869 +0x186

goroutine 1 [runnable]:
runtime.Gosched()
	/usr/local/go/src/runtime/proc.go:166 +0x14
cmd/compile/internal/gc.ggloblsym(0xc820422100, 0x800000010)
	/usr/local/go/src/cmd/compile/internal/gc/gsubr.go:237 +0xe8
cmd/compile/internal/gc.onebitwritesymbol(0xc820422600, 0x3, 0x4, 0xc820422100)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1756 +0x122
cmd/compile/internal/gc.liveness(0xc820880360, 0xc8214bc360, 0xc820422100, 0xc820422300)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1817 +0x3f8
cmd/compile/internal/gc.compile(0xc820880360)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:528 +0xe07
cmd/compile/internal/gc.funccompile(0xc820880360)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1484 +0x1c9
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:473 +0x1f08
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:26 +0x189
# github.com/letsencrypt/boulder/Godeps/_workspace/src/github.com/cloudflare/cfssl/crypto/pkcs12
runtime: failed to create new OS thread (have 2 already; errno=11)
fatal error: newosproc

runtime stack:
runtime.throw(0x81f8c0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82005e000, 0xc82006dfc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x89b7a8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0xc80c20)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820058770 sp=0xc820058768
runtime.main()
	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200587c0 sp=0xc820058770
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200587c8 sp=0xc8200587c0
Waiting for debug port 8000
Waiting for debug port 8000
Waiting for debug port 8000


These processes exited early (check above for their output):
	'go install ./cmd/boulder-ra && exec boulder-ra --config test/boulder-config.json' with pid 14818 exited 2
	'go install ./cmd/boulder-sa && exec boulder-sa --config test/boulder-config.json' with pid 14824 exited 2
	'go install ./cmd/boulder-va && exec boulder-va --config test/boulder-config.json' with pid 14838 exited 2
```

Any ideas? @jcjones, @jsha, @jmhodges, @rolandshoemaker?

**Comment by jmhodges** [comment]
It sounds like your thread ulimit is very low. Run 

    cat /proc/sys/kernel/threads-max

and 

    ulimit -u

for us?

**Comment by jmhodges** [comment]
(It's either very low or you're running very many threads in some scope. Possibly both!)

**Comment by kuba** [comment]
Note, this is about integration tests in Travis, e.g.:
- https://travis-ci.org/letsencrypt/letsencrypt/jobs/77108460
- https://travis-ci.org/letsencrypt/letsencrypt/jobs/77108448
- https://travis-ci.org/letsencrypt/letsencrypt/jobs/77050265

**Comment by kuba** [comment]
https://travis-ci.org/kuba/letsencrypt/builds/77202785#L287

```
$ cat /proc/sys/kernel/threads-max
1028079
$ ulimit -u
514039
```

**Comment by jmhodges** [comment]
Ah, okay, that is good context. This problem doesn't occur in the boulder tests. I will look at your travis config.

**Comment by jmhodges** [comment]
I have a suspicion this is because this code is running on the legacy TravisCI platform.

**Comment by jmhodges** [comment]
FYI here is a ticket to add `dialog` to the allowed packages in the TravisCI container builds which would let letsencrypt/letsencrypt on the container build hotness https://github.com/travis-ci/apt-package-whitelist/issues/1006

I've whipped up a branch to move to the new container platform and, in parallel, I've done some other work around chilling how fast we throw up commands with no results, yet.

**Comment by jmhodges** [comment]
I've posted https://github.com/letsencrypt/boulder/pull/663 which installs all of the boulder services in one command instead of forking off a bunch of simultaneous install commands vying for the same resources and doing duplicative work. It appears to stabilize the build but, as with all randomness, you can never be quite sure.

I believe the move to the new TravisCI container builds will also be a good idea! I'll do that when travis-ci/apt-package-whitelist#1006 closes.

**Comment by jmhodges** [comment]
Have these failures re-occurred since letsencrypt/boulder#663 went in?

**Comment by kuba** [comment]
Yes, this is still a problem.

Container based builds do not fix it: https://travis-ci.org/kuba/letsencrypt/builds/78451224. Other ideas?

**Comment by kuba** [comment]
1. I provided wrong link. It should've been https://travis-ci.org/kuba/letsencrypt/builds/78916150.
2. There was an error due to a syslog setup missing.
3. #746 (starting  86bfe61) is passing... after it's pulled in I'll keep an eye on all of the builds

**Comment by dickeyxxx** [comment]
After upgrading to Go 1.5 on the Heroku CLI, https://github.com/heroku/heroku-cli some ubuntu users have been reporting this same issue. Might be an issue with Go.

**Comment by jmhodges** [comment]
@kuba sorry, context gathering. is this still happening or did the containerization fix it?

**Comment by kuba** [comment]
@jmhodges I don't know, #746 was pulled in just 9 hours ago

**Comment by jmhodges** [comment]
How about now?

**Comment by jdkasten** [comment]
@jmhodges I believe it has been fixed (several PRs today without any problem).  Thanks!

**Comment by jmhodges** [comment]
That makes me very happy. Thanks, y'all.
