### ISSUE TITLE
problems importing zope.component

### ISSUE THREAD

**Issue by atkawa7** [letsencrypt/letsencrypt#774]
Traceback (most recent call last):
  File "/usr/local/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 17, in <module>
    import zope.component
  File "/usr/local/lib/python2.7/dist-packages/zope.component-4.2.2-py2.7.egg/zope/component/__init__.py", line 19, in <module>
    from zope.interface import named
ImportError: cannot import name named

Solved by reverting back to version 4.1

**Comment by pde** [comment]
What OS are you getting this on?  What installation method did you use?

(You can probably fix this by using virtualenv to install dependencies, as somewhat-documented here https://letsencrypt.readthedocs.org/en/latest/using.html#installation )

**Comment by kuba** [comment]
It's clear from the log that @atkawa7 did not use virtualenv setup. As described in the giant yellow box at https://letsencrypt.readthedocs.org/en/latest/using.html#installation, this is not supported, so I believe this should be closed now.
