### ISSUE TITLE
Test failures with new versions of mock

### ISSUE THREAD

**Issue by hlieberman** [letsencrypt/letsencrypt#779]
The ManualAuthenticatorTests fail with a recent version of mock (1.3.0).

I have filed issue testing-cabal/mock#323 to track this issue.

**Comment by hlieberman** [comment]
Isolated problem to PR #622; 9e2682a025f32dabe8fe7256141785a698d0c257 causes test regression in Python 2.x series.

**Comment by kuba** [comment]
Yup, I could verify this problem:
```
======================================================================
ERROR: test_perform_test_command_run_failure (letsencrypt.plugins.manual_test.AuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 2320, in create_autospec
    _name='()', _parent=mock)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 2359, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 228, in _check_signature
    _copy_func_details(func, checksig)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 254, in _copy_func_details
    funcopy.func_defaults = func.func_defaults
AttributeError: 'functools.partial' object has no attribute 'func_defaults'

======================================================================
ERROR: test_perform_test_mode (letsencrypt.plugins.manual_test.AuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 2320, in create_autospec
    _name='()', _parent=mock)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 2359, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 228, in _check_signature
    _copy_func_details(func, checksig)
  File "/home/jakub/dev/letsencrypt/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 254, in _copy_func_details
    funcopy.func_defaults = func.func_defaults
AttributeError: 'functools.partial' object has no attribute 'func_defaults'
```
