### ISSUE TITLE
letsencrypt tests fail with recent python-mock

### ISSUE THREAD

**Issue by fmarier** [letsencrypt/letsencrypt#798]
This is what I get when running the test suite on Debian unstable (using `mock 1.3.0`):

```
python /usr/bin/nosetests letsencrypt
.............................................................................EE.........................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: test_perform_test_command_run_failure (letsencrypt.plugins.manual_test.ManualAuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2320, in create_autospec
    _name='()', _parent=mock)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2359, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 228, in _check_signature
    _copy_func_details(func, checksig)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 254, in _copy_func_details
    funcopy.func_defaults = func.func_defaults
AttributeError: 'functools.partial' object has no attribute 'func_defaults'

======================================================================
ERROR: test_perform_test_mode (letsencrypt.plugins.manual_test.ManualAuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2320, in create_autospec
    _name='()', _parent=mock)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2359, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 228, in _check_signature
    _copy_func_details(func, checksig)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 254, in _copy_func_details
    funcopy.func_defaults = func.func_defaults
AttributeError: 'functools.partial' object has no attribute 'func_defaults'

----------------------------------------------------------------------
Ran 392 tests in 8.926s

FAILED (errors=2)
```

**Comment by hlieberman** [comment]
Dup of #779.

**Comment by fmarier** [comment]
Indeed, let's move the discussion there.
