### ISSUE TITLE
Apache listed as misconfigured when not installed

### ISSUE THREAD

**Issue by bmw** [letsencrypt/letsencrypt#864]
With freshly install Let's Encrypt on freshly installed Debian, I experienced the following:
```
letsencrypt -t -vvv --debug --agree-tos --agree-eula auth
2015-09-30 15:08:28,497:DEBUG:letsencrypt.cli:Root logging level set at 0
2015-09-30 15:08:28,498:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2015-09-30 15:08:28,498:DEBUG:letsencrypt.cli:Arguments: ['-t', '-vvv', '--debug', '--agree-tos', '--agree-eula', 'auth']
2015-09-30 15:08:28,499:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2015-09-30 15:08:28,608:ERROR:letsencrypt.le_util:Unable to run the command: apache2ctl configtest
2015-09-30 15:08:28,609:DEBUG:letsencrypt.plugins.disco:Misconfigured PluginEntryPoint#apache: Unable to run the command: apache2ctl configtest
Traceback (most recent call last):
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 141, in prepare
    self.config_test()
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 1068, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Unable to run the command: apache2ctl configtest
2015-09-30 15:08:28,609:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#nginx): Could not find configuration root
Traceback (most recent call last):
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_nginx/configurator.py", line 111, in prepare
    self.conf('server-root'), self.mod_ssl_conf)
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_nginx/parser.py", line 29, in __init__
    self.loc = self._set_locations(ssl_options)
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_nginx/parser.py", line 179, in _set_locations
    root = self._find_config_root()
  File "/root/le/venv/local/lib/python2.7/site-packages/letsencrypt_nginx/parser.py", line 202, in _find_config_root
    "Could not find configuration root")
NoInstallationError: Could not find configuration root
2015-09-30 15:08:28,610:DEBUG:letsencrypt.display.ops:Multiple candidate plugins: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f698b309110>
Prep: Unable to run the command: apache2ctl configtest

* manual
Description: Manual Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: manual = letsencrypt.plugins.manual:Authenticator
Initialized: <letsencrypt.plugins.manual.Authenticator object at 0x7f698b2eff90>
Prep: True

* standalone
Description: Standalone Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone.authenticator:StandaloneAuthenticator
Initialized: <letsencrypt.plugins.standalone.authenticator.StandaloneAuthenticator object at 0x7f698b2efcd0>
Prep: True

How would you like to authenticate with the Let's Encrypt CA?
-------------------------------------------------------------------------------
1: Apache Web Server - Alpha (apache) [Misconfigured]
2: Manual Authenticator (manual)
3: Standalone Authenticator (standalone)
-------------------------------------------------------------------------------
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 
```
The Apache plugin should raise `NoInstallationError` to prevent itself from being listed (as misconfigured) in prompts to the user when not installed.

**Comment by jdkasten** [comment]
Thanks!  

In the prepare() method... each of the executables should be verified to exist...

There is a function for this in letsencrypt/le_util.py
le_util.exe_exists(apache_ctl)

if not raise NoInstallationError
