### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ArgParser'

### ISSUE THREAD

**Issue by webhtb** [letsencrypt/letsencrypt#881]
An unexpected error occurred.
AttributeError: 'module' object has no attribute 'ArgParser'
Please see the logfile 'letsencrypt.log' for more details.

letsencrypt.log:

Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 929, in main
    parser, tweaked_cli_args = create_parser(plugins, cli_args)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 647, in create_parser
    helpful = HelpfulArgumentParser(args, plugins)
  File "/usr/lib/python2.7/site-packages/letsencrypt-0.1-py2.7.egg/letsencrypt/cli.py", line 514, in __init__
    self.parser = configargparse.ArgParser(
AttributeError: 'module' object has no attribute 'ArgParser'

**Comment by bmw** [comment]
Hi @webhtb, did you install Let's Encrypt inside of `virtualenv` as described [here](https://letsencrypt.readthedocs.org/en/latest/using.html#installation)?

**Comment by webhtb** [comment]
inside, with virtualenv not working

**Comment by bmw** [comment]
It seems fairly clear that the original traceback you posted was not from inside `virtualenv`.

Are you saying you reinstalled inside of `virtualenv` and it's still not working? Can you tell me more? Error? Traceback? Logs?

**Comment by webhtb** [comment]
Last login: Fri Oct  2 15:13:06 2015 from 5.14.108.216
[root@soft-manager ~]# cd letsencrypt-master/
acme/                           examples/                       letsencrypt-nginx/
bootstrap/                      letsencrypt/                    letshelp-letsencrypt/
build/                          letsencrypt-apache/             tests/
dist/                           letsencrypt-compatibility-test/ tools/
docs/                           letsencrypt.egg-info/
[root@soft-manager ~]# cd letsencrypt-master/bootstrap/
[root@soft-manager bootstrap]# virtualenv --no-site-packages -p python2 venv                      Already using interpreter /usr/bin/python2
New python executable in venv/bin/python2
Not overwriting existing python script venv/bin/python (you must use venv/bin/python2)
Installing setuptools, pip...done.
[root@soft-manager bootstrap]# ./venv/bin/pip install -r requirements.txt acme/ . letsencrypt-apache/ letsencrypt-nginx/
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 181, in from_line
    isolated=isolated)
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/req/req_install.py", line 54, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in parse
    reqs = list(parse_requirements(s))
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2820, in parse_requirements
    "version spec")
  File "/root/letsencrypt-master/bootstrap/venv/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'acme/', 'at', '/')

[root@soft-manager bootstrap]#

**Comment by bmw** [comment]
Ah. The problem is you're inside the `bootstrap` directory and the files you're specifying for `pip` are not there. Run the command from root of the project. `requirements.txt` and all of the folders you are specifying on the command line are found there.

**Comment by webhtb** [comment]
im in bootstrap dir

**Comment by bmw** [comment]
Right. You should be outside it. Using the directory structure that you posted, you should be inside `letsencrypt-master` when installing Let's Encrypt.

**Comment by webhtb** [comment]
it working i think, thank you!

**Comment by bmw** [comment]
No problem! If you encounter another problem, please post an issue here or on the [community forum](https://community.letsencrypt.org).
